opencart/opencart

- upload/admin/controller/extension/module.php
Except for English, any other languages module names not in good order, hard to follow where the module you want. This will fix it
> Sort modules by name

- upload/catalog/view/theme/default/stylesheet/stylesheet.css
> Fixed a bug when product layouts were used in left and right columns.

- upload/admin/controller/sale/customer.php
> Fix default value of error_address

- upload/catalog/controller/payment/sagepay_direct.php
> removing debug code in the cron job method

- upload/admin/controller/module/amazon_login.php
- upload/admin/controller/module/amazon_pay.php
- upload/admin/controller/payment/amazon_login_pay.php
> - updating event methods from tool/event to extension/event

- upload/catalog/view/theme/default/template/product/product.tpl
Clearing float, fixing unclickable product review submit button on mobile, fixing #2752
> clear review buttons

- upload/catalog/view/theme/default/template/payment/amazon_login_pay_address.tpl
- upload/catalog/view/theme/default/template/payment/amazon_login_pay_payment.tpl
> Amazon - warning class to alert class

- upload/catalog/model/account/customer.php
error when sending the e-mail to admin if to register the client
> BUG when sending the e-mail to admin

- upload/admin/controller/sale/customer.php
- upload/admin/controller/sale/order.php
- upload/admin/view/template/sale/customer_form.tpl
- upload/admin/view/template/sale/order_form.tpl
- upload/admin/view/template/sale/order_info.tpl
- Edit Customer
- Order Info
- Edit Order
> Position correction of custom fields in admin panel

- upload/admin/view/template/sale/order_invoice.tpl
- upload/admin/view/template/sale/order_shipping.tpl
Added missing jQuery link to order invoice and order shipping.
> Added missing jQuery link to order invoice and order shipping.

- upload/admin/controller/fraud/fraudlabspro.php
- upload/admin/language/english/fraud/fraudlabspro.php
- upload/admin/model/fraud/fraudlabspro.php
- upload/admin/view/template/fraud/fraudlabspro.tpl
- upload/admin/view/template/fraud/fraudlabspro_info.tpl
- upload/catalog/model/fraud/fraudlabspro.php
Added a new fraudlabs pro anti-fraud module
> added fraudlabs pro module

- upload/system/startup.php
no need for else when using return
> ensure it's a file, include_once

- upload/admin/controller/payment/firstdata.php
- upload/admin/controller/payment/firstdata_remote.php
- upload/admin/model/payment/firstdata.php
- upload/admin/model/payment/firstdata_remote.php
- upload/catalog/controller/payment/firstdata.php
- upload/catalog/view/theme/default/template/payment/firstdata.tpl
- installation bug (standard and remote)
- email parameter sent in payment form (standard)
> FAO James - Bug fixes First Data:

- upload/admin/model/catalog/product.php
Admin dashboard was throwing fatal error
> Fix syntax error

- upload/admin/controller/fraud/fraudlabspro.php
- upload/admin/controller/fraud/maxmind.php
- upload/catalog/model/fraud/maxmind.php
> Fixed Maxmind not load on order info page

- upload/admin/model/setting/setting.php
> Bug fix #3015

- upload/admin/controller/setting/setting.php
- upload/admin/language/english/setting/setting.php
I found a security issue on the setting controller that make you able to read and delete every file.
Admin panel access is a requirement so it is not so dangerous, but for just 2 line of code I think it's better to fix it.
> Fixed security issue on log filename

- upload/admin/model/localisation/language.php
> add event *.admin.language.*

- upload/admin/view/template/marketing/affiliate_form.tpl
See issue description in bug report #3121 .
> Fixed issue 3121

- .gitignore
Prevents commit of `/tests/phpunit/bootstrap.php` which contains credentials
> Added PHPUnit bootstrap.php file to .gitignore

- upload/catalog/controller/information/contact.php
> Contact POST url with regards to SSL

- upload/system/helper/vat.php
Croatia was missing from the list of countries, so I've added it to the end of the list.
> Added Croatia to the list of EU countries

- upload/catalog/model/payment/pp_standard.php
doc https://developer.paypal.com/docs/classic/api/currency_codes/#paypal
> add russian ruble to pp_standart

- upload/catalog/model/payment/amazon_login_pay.php
> LPA - updating platform id code

- upload/catalog/model/fraud/maxmind.php
Removed duplicate ip_city as per issue posted by @shibinv
https://github.com/opencart/opencart/issues/3331
> Removed Duplicate ip_city In maxmind.php

- upload/catalog/view/theme/default/template/product/compare.tpl
> redundant array access

- upload/catalog/view/theme/default/template/product/product.tpl
for product left & right sections
> remove redundant conditions

- upload/catalog/view/javascript/common.js
> Checkout register login

- upload/catalog/view/theme/default/template/checkout/checkout.tpl
> Reset payment method continue button if terms are not agreed

- upload/catalog/controller/account/wishlist.php
> Bug fix #3412

- upload/admin/controller/customer/customer.php
Hi guys,
Could you please accept a request with this tiny fix?
> Removed declaration of unused array variable `$json = array();`.

- upload/catalog/controller/checkout/checkout.php
- upload/catalog/language/english/checkout/checkout.php
Updated controller file to assign checkout step numbers based on whether or not shipping is required.
Replaced the step number with %s in the language file.
> Added Checkout Step Reassignment When Shipping Not Required

- upload/admin/controller/extension/openbay.php
> Removed unused local variable

- upload/admin/view/template/common/header.tpl
This is not a bug fix, but rather a design change suggestion.  I've broken the store list out from the support list.
See images below:
http://opencartaddons.com/image/examples/admin_header_store.jpg
http://opencartaddons.com/image/examples/admin_header_support.jpg
Regards,
Joel.
> Update To Header Menu

- upload/admin/controller/marketing/contact.php
From email now correctly corresponds with selected store for marketing mail.
> Updated From Email For Marketing Mail

- upload/catalog/view/theme/default/template/product/product.tpl
There is already support for the image checkbox in product details. 
In tpl there is no code to display the image related to type checkbox.
> Adding image to option type checkbox in product details

- upload/catalog/model/payment/securetrading_ws.php
replace $this->model_checkout_order->update(...) by ->addOrderHistory(...)
> [securetrading_ws.php] addOrderHistory

- upload/admin/controller/customer/customer.php
added missing "filter_ip" query to the url
> [customer.php] forgot params "filter_ip"

- upload/system/library/cart/tax.php
i believe that method is not even used anyway.
> correct private variable name

- upload/admin/view/template/payment/securetrading_ws_order.tpl
the tables are using old table class layout (.list & .form) I change them to "table table-bordered"
> [securetrading_ws_order.tpl] fix table layout

- upload/admin/controller/payment/securetrading_ws.php
> [securetrading_ws.php] fix template rendering

- upload/admin/language/english/catalog/information.php
Fixed language string for error_store to match others.
> Updated error_store Language

- upload/catalog/model/total/reward.php
The Comparision Condition was placed wrongly it was supped to check if balance is more than required for order but it was doing opposite
> The Comparision Condition was placed wrongly

- upload/admin/language/english/catalog/product.php
Capitalized "Comma" to match other help text.
> Language Text Update

- upload/install/controller/step_2.php
as per Issue #3616
https://github.com/opencart/opencart/issues/3614
> Extra Slash deleted on Storage/cache

- upload/catalog/controller/common/seo_url.php
Issue #3606 solved, as per instructions in the ticket. 
Thank you.
> Solved issue #3606

- upload/admin/controller/module/featured.php
> Featured Products Fix (Bug #3551)

- upload/system/library/pagination.php
Remove `?page=1` from paginate urls
> Fix pagination

- upload/catalog/controller/api/order.php
> no need for substr()

- upload/admin/controller/customer/custom_field.php
- upload/admin/language/english/customer/custom_field.php
- upload/admin/model/customer/custom_field.php
- upload/admin/view/template/customer/custom_field_form.tpl
- upload/catalog/controller/account/register.php
- upload/catalog/controller/checkout/register.php
- upload/catalog/language/english/account/register.php
- upload/catalog/language/english/checkout/checkout.php
- upload/catalog/model/account/custom_field.php
- upload/install/index.php
- upload/install/opencart.sql
> Add field to validate the custom fields.

- upload/catalog/model/total/voucher.php
$order_query and $order_voucher_query are only used to check the record existence, there is non need to SELECT *.
I believe they could also be merged into 1 query with inner join berween order_voucher and order since both conditions must be satisfied
regards
> optimized check queries

- upload/catalog/controller/account/register.php
- upload/catalog/controller/account/return.php
- upload/catalog/controller/affiliate/register.php
- upload/catalog/controller/information/contact.php
The issue described here https://github.com/opencart/opencart/issues/3553
When you try to send incorrect form with any captha after reload and running $this->validate() the language variable $_['heading_title'] overwrites by same captcha variable.
> This resolve the issue #3553

- upload/catalog/model/shipping/usps.php
$this->config->get('usps_girth') is not editable, so it never gets set.  Use the girth calculation from the US instead.
> Fix missing international girth

- upload/catalog/model/module/pp_login.php
Fixed Log in With PayPal endpoint changes. #3695 and #3640 
@jamesallsup
> Endpoint changes for Log in With PayPal

- upload/catalog/view/theme/default/template/product/product.tpl
Added customer_name variable to review name field in template file.  customer_name was already defined within the controller file.
> [product.tpl] Customer Name in Review Name Field

- upload/admin/view/template/module/special.tpl
> special.tpl missing </div>

- upload/catalog/controller/api/login.php
Replace config_api_id with api_id.
> Check fo api_id

- upload/system/library/db/mpdo.php
> Provide error message with real failure instead of misleading statement

- upload/admin/view/template/module/featured.tpl
the autocomplete field uses the same name "product" as the array "product[]"
when submitting the form without selecting any product we get error message (..Invalid argument supplied for foreach()...)
> [featured.tpl] Conflict Post "product"

- upload/admin/controller/setting/store.php
Undefined variable: config_theme in admin\view\template\setting\store_form.tpl on line 84
> corrected variable name from config_template to config_theme

- upload/admin/model/report/product.php
``admin/index.php?route=report/product_purchased``
Right now in the model ``admin/report/product.php``, the ``getPurchased()`` method calculate the total by multiplying the
``(total + tax) * the quantity``
it should be 
``(price of the product + tax) * the quantity``
> Calculation error

- upload/admin/view/template/dashboard/map.tpl
- upload/admin/view/template/dashboard/online.tpl
World Map -using fa-globe instead of fa-eye
People Online - using fa-users instead of fa-eye
> Update several icon for better view for dashboard area in backend

- upload/admin/model/design/layout.php
Small tweak to show module list by position and sort_order in Layout
> Module order by position and sort_order in layout

- upload/admin/controller/extension/analytics.php
at admin\controller\extension\analytics.php
> fix missing model setting/setting

- upload/admin/view/javascript/common.js
> Fixed tooltip remove

- upload/admin/controller/common/forgotten.php
@danielkerr : im sorry, im not really understand by what you mean on this comment > https://github.com/opencart/opencart/pull/3895, perhaps you want me to open a pull request with 1 commit only. thanks
> Fix the issue with admin password reset link in email

- upload/catalog/controller/common/column_left.php
- upload/catalog/controller/common/column_right.php
- upload/catalog/controller/common/content_bottom.php
- upload/catalog/controller/common/content_top.php
If module not return, empty column left or right is visible.
> Skip module if not return

- upload/catalog/controller/checkout/guest.php
> [guest.php] wrong comment

- upload/catalog/controller/event/theme.php
Removed 'theme/' from template path that is already included in DIR_TEMPLATE constant in config.php
> removed duplicate 'theme/'  from template path

- upload/admin/language/en-gb/fraud/fraudlabspro.php
- upload/admin/view/template/fraud/fraudlabspro_info.tpl
- upload/catalog/model/fraud/fraudlabspro.php
Changes
* get user name for validation
* fixed the url issue on login to FraudLabs Pro merchant area
* UI enhancement
> new improvement for user validation

- upload/admin/controller/extension/modification.php
Fix T_VARIABLE error from #3950
> fix modification T_VARIABLE error

- upload/catalog/view/theme/default/template/account/address_list.tpl
- upload/catalog/view/theme/default/template/account/download.tpl
- upload/catalog/view/theme/default/template/account/return_list.tpl
- upload/catalog/view/theme/default/template/account/wishlist.tpl
standarize account template with .table-responsive to wrap table
> Add .table-responsive to account template

- upload/admin/controller/event/theme.php
- upload/system/config/admin.php
> Admin templates backward compability

- upload/admin/model/report/customer.php
> Need to change $order_data to $customer_data

- upload/system/.htaccess
Prevent people from gaining direct access to important files such as log files, downloads, uploads, etc.  
Some extensions (e.g. payment gateways) include customer's personal information in their debug.
> Prevent Access To System Files

- upload/catalog/view/theme/default/template/product/product.tpl
fix style cart-total (add product to cart in product.tpl
see https://github.com/opencart/opencart/blob/master/upload/catalog/view/javascript/common.js#L157
> fix style cart-total  in product.tpl

- upload/admin/controller/extension/modification.php
Modifications log hurts my eyes. Added little clarity.
This is just a rewrite of original and a CRLF between <file>
> [2.2.0.0.b1] Rewrite + comment added for clarity

- upload/admin/view/stylesheet/stylesheet.css
> Update admin stylesheet.css for form-group inside the modal-body

- upload/catalog/controller/account/address.php
Fixed an error in displaying the page.
> PHP Parse error:  syntax error, unexpected T_BOOLEAN_AND, expecting ')'

- upload/catalog/controller/startup/error.php
- upload/system/config/default.php
Fix https://github.com/opencart/opencart/issues/4062
> fix error display and log

- upload/admin/controller/common/filemanager.php
- upload/admin/view/stylesheet/stylesheet.css
- upload/admin/view/template/common/filemanager.tpl
Better view folder size(same W x H with image) on desktop and 2 column on mobile device a43d4cf
Check request post method and create index.html in new directory 89838f3
> Better view for small device grid on filemanger

- upload/catalog/controller/checkout/cart.php
add missing success message upon cart update
> update cart.php controller to show success message upon cart update

- upload/admin/controller/extension/modification.php
@danielkerr : fixing the variable
> Update modification.php fix

- upload/system/library/template.php
Notice: Undefined variable: expire in /var/www/laptophatinh/system/library/template.php on line 9
> Fix error Undefined variable: expire

- upload/catalog/controller/startup/startup.php
- upload/system/config/admin.php
- upload/system/config/default.php
- upload/system/framework.php
Add url_autostart and in catalog move url to startup.
> Url update

- upload/install/model/upgrade/1000.php
- upload/install/model/upgrade/1001.php
- upload/install/model/upgrade/1002.php
- upload/install/model/upgrade/1003.php
- upload/install/model/upgrade/1004.php
- upload/install/model/upgrade/1005.php
- upload/install/model/upgrade/1006.php
- upload/install/model/upgrade/1007.php
- upload/install/view/template/upgrade/upgrade.tpl
upgrade fix v2 includes dynamic script and fix for name changes in primary key.
Should work as far back as 1.5.0
> upgrade fix v2 includes dynamic script and fix for name changes in primary key

- upload/admin/controller/analytics/google_analytics.php
Fix MultiStore issue, because "google_analytics_code" show always the setting of the defaut store
> google_analytics.php : Fix MultiStore issue

- upload/install/opencart.sql
adding china zone
(4232, 44, 'Qinghai', 'QH', 1)
> adding china zone

- upload/catalog/controller/payment/authorizenet_sim.php
Issue #4159 has been addressed and fixed here. The template loading code is changed according to the new 2.2.x standards.
> Update template loading according to 2.2.x

- upload/system/config/catalog.php
> Fix customer data and API

- upload/install/index.php
- upload/install/model/upgrade/1001.php
- upload/install/model/upgrade/1002.php
- upload/install/model/upgrade/1003.php
- upload/install/model/upgrade/1004.php
- upload/install/model/upgrade/1005.php
- upload/install/model/upgrade/1006.php
- upload/install/model/upgrade/1007.php
- upload/install/php.ini
- upload/install/view/template/upgrade/upgrade.tpl
Qphoria: More upgrade improvements. This should be good for most upgrades from 1.5.0 or later.
> More upgrade improvements

- upload/catalog/controller/account/login.php
The additional check will redirect the user to the account page in case the login has been executed from the logout page
> immediate logout after login fix

- upload/admin/model/tool/image.php
- upload/catalog/model/tool/image.php
fix issue reported in https://github.com/opencart/opencart/issues/4273
> fix IMG_XX to IMAGETYPE_XX constants

- upload/admin/controller/sale/order.php
- upload/admin/language/en-gb/localisation/location.php
1. Update location.php - fix 'error_name'
2. Fix "Class 'Controllerpayment' not found" if remove payment module
> Fix some errors

- upload/install/view/template/install/step_4.tpl
Fixed issue #4263:
```php
<div class="alert alert-success"><?php echo $text_success; ?></div>
```
Changed this to 
```php
<div class="alert alert-success"><?php echo $success; ?></div>
```
The undefined index notice should be gone now.
> Fixed Issue #4263

- upload/system/engine/loader.php
using is_callable as method_exists also includes private methods
> check model method visibility

- upload/system/library/image.php
http://stackoverflow.com/questions/5398147/copying-a-transparent-image-over-another-transparent-image
> fix watermark method

- upload/admin/view/javascript/summernote/opencart.js
this is not a IIFE, just a jQuery document ready call
> fix summernote opencart.js javascript error

- upload/install/model/upgrade/1006.php
- Fix for cleaning up old folders
- Fix for language db fields (although they appear to no longer be used)
- Moved /storage/ adjustment code to its own section
- Added download to the move to storage/download
> Additional upgrade fixes

- upload/catalog/controller/api/order.php
$json was swapped for $order_info
> Fix wrong variable being used - Fixes #4318 

- upload/admin/view/javascript/common.js
- JS will hoist var declaration so it's better to put at the beginning of scope. It's also better to define local scope variables (ex the html string)
- also declare loop iteration  variables (when all used browsers will be compatibile with emca 6 we will be able to use `let` for the loop block scope)
Please Daniel verify:
- category has string keys so it's better to define it as a simpler standard object (we are using for/in not using Array.length() in a std for loop)
- we are using category names as keys so we can simplify the category object: each key will represent an array of items related to the category represented by the key itself.
```js
// category will be something like 
{
'Category 1': [
{
label: 'item 1-1',
value: 11,
},
{
label: 'item 1-2',
value: 12,
},
//...
],
'Category …
```
> explicitly hoist scope var declarations

- upload/system/library/cache/apc.php
+ delete all cached entries having keys starting with ... to get the same behaviour of the `file` adapter
> check if apc extension is installed

- composer.json
- upload/admin/controller/payment/divido.php
- upload/admin/language/en-gb/payment/divido.php
- upload/admin/model/payment/divido.php
- upload/admin/view/template/payment/divido_order.tpl
- upload/catalog/controller/payment/divido.php
- upload/catalog/model/payment/divido.php
- Added Divido lib to composer.json!
- Change name and description of target status
- Add lookup column for deposit
- Log deposit
- Show deposit in order info
- Filter plans based on total sum - smallest deposit
- Removed unecessary call to getOrder
- Added new status "lender action"
- Changed divido status => order status mapping
- Add fault tolerance to divido status messages
- Don't send too many emails
- Use delivery address if available
@davidteal
> Divido dependencies, small fixes and updates

- upload/admin/view/stylesheet/stylesheet.css
Reverts opencart/opencart#4394
> Revert "Update CSS file"

- upload/admin/model/payment/bluepay_redirect.php
If you try to edit the amount for release on an order using Bluepay, it does not send that new amount. https://github.com/opencart/opencart/issues/4413
> fixed editing release amount for bluepay

- upload/admin/model/localisation/language.php
- upload/install/model/upgrade/1001.php
- upload/install/model/upgrade/1004.php
- upload/install/model/upgrade/1006.php
- upload/install/opencart.sql
- Removed wildcard search for config files because it was matching other stores in subfolders on the same site
- Add most common chrome match for en browsers (en-US) to language locale
- Fix image path change in welcome module conversion.
> A few fixes to the upgrade script.

- upload/admin/view/template/sale/return_form.tpl
> Fix: Error missing #4469

- upload/admin/controller/sale/order.php
- upload/admin/controller/sale/recurring.php
> Fix Cleaning based on #4473

- upload/admin/view/template/localisation/geo_zone_form.tpl
> Fix: #4398 and saving empty zone_id at first added country

- upload/system/library/pagination.php
It occurs when seo urls are on and there is no other url parameter aside from page (&page is ?page)
> Pagination page 1 issue

- upload/admin/view/template/extension/module.tpl
> Better button icons and colors

- upload/catalog/model/catalog/product.php
If a product was tagged with the tags "Foo" and "Bar" it didn't show up when you searched for "Foo Bar".
> Support for multiple tags when searching for a product

- upload/catalog/controller/account/recurring.php
> OC 2.2.0.0 undefined index for currency in catalog/controller/payment/account/recurring.php #4145

- upload/admin/controller/report/customer_credit.php
- upload/admin/controller/report/customer_order.php
- upload/admin/controller/report/customer_reward.php
- upload/admin/language/en-gb/report/customer_credit.php
- upload/admin/language/en-gb/report/customer_order.php
- upload/admin/language/en-gb/report/customer_reward.php
- upload/admin/model/report/customer.php
- upload/admin/view/template/report/customer_credit.tpl
- upload/admin/view/template/report/customer_order.tpl
- upload/admin/view/template/report/customer_reward.tpl
On pages:
Customer Orders Report
Customer Reward Points Report
Customer Credit Report
> Added filter by customer

- upload/.htaccess.txt
update for apache 2.4 Access Control
> Update .htaccess.txt for apache 2.4 Access Control

- upload/admin/controller/extension/shipping/fedex.php
Looks like this should be `fedex_height`.
> Duplicate subexpression in Fedex.php

- upload/admin/controller/catalog/review.php
- upload/admin/model/catalog/review.php
- upload/admin/view/template/catalog/review_form.tpl
> Added field "date_added" in review edit form

- upload/install/model/upgrade/1004.php
- upload/install/model/upgrade/1005.php
- Fix for upgrade script for featured products, encryption hash, and welcome module removal after conversion.
> - Additional Fixes for upgrade script

- upload/admin/controller/marketing/contact.php
- upload/admin/language/en-gb/marketing/contact.php
- upload/admin/view/template/marketing/contact.tpl
> Added an error text if message is not sent to anyone email

- upload/admin/controller/catalog/product.php
- upload/admin/model/catalog/product.php
- upload/admin/view/template/catalog/product_list.tpl
> Added filter by image on product list

- upload/admin/view/stylesheet/stylesheet.css
> Admin platform CSS update

- upload/admin/view/stylesheet/stylesheet.css
Reverts opencart/opencart#4557
> Revert "Admin platform CSS update"

- upload/admin/model/catalog/product.php
Fixed issue of empty seo keyword added in url_alias table on new product creation.
This is my first commit on github. If any issues sorry for that.
> Fixed: Empty seo keyword added in url_aliad table on new product

- upload/catalog/controller/product/compare.php
> Fix compare success

- upload/catalog/view/javascript/common.js
> Added active state buttons "display view"

- upload/catalog/view/theme/default/template/product/category.tpl
- upload/catalog/view/theme/default/template/product/manufacturer_info.tpl
- upload/catalog/view/theme/default/template/product/search.tpl
- upload/catalog/view/theme/default/template/product/special.tpl
> Stylized and better adaptive sorting block

- upload/catalog/view/theme/default/template/extension/payment/pp_payflow.tpl
> Removing undefined help/tooltips

- upload/admin/controller/design/translation.php
- upload/admin/language/en-gb/design/translation.php
- upload/admin/view/template/design/translation.tpl
finish download language file, unzip and move to upload folder 
then move the language file in the admin/catalog folder
then delete the language file from upload folder.
> Translation

- upload/catalog/controller/extension/payment/pp_express.php
> Sending code instead of name for some countries in the SHIPTOSTATE field

- upload/admin/controller/setting/setting.php
- upload/admin/controller/startup/startup.php
- upload/admin/language/en-gb/setting/setting.php
- upload/admin/model/setting/setting.php
- upload/admin/view/template/setting/setting.tpl
- upload/catalog/controller/startup/startup.php
- upload/system/config/default.php
- upload/system/framework.php
- upload/system/startup.php
Reverts opencart/opencart#4584
> Revert "Added Timezone"

- upload/admin/controller/extension/extension/total.php
- upload/admin/controller/sale/order.php
- Fixed issue that prevented editing/updating orders when moving to a new domain or testing on a subdomain.
> - Fixed issue with 2.3.0 not allowing anyone to install/uninstall totals

- upload/system/.htaccess
Hi.
There was a bug with ```upload/system/.htaccess``` file. It basically blocked JavaScript and CSS assets. This has been now fixed.
Solves issue #4638. Thank you.
> Solved Issue #4638

- upload/admin/controller/extension/payment/amazon_login_pay.php
- upload/admin/view/template/extension/payment/amazon_login_pay.tpl
Amazon changed the variable format for the language field in SimplePath
> LPA - simple path language variable format

- upload/catalog/controller/extension/payment/klarna_checkout.php
Fixing Klarna Checkout session spoof
> Klarna checkout session

- upload/admin/controller/extension/payment/cardconnect.php
- upload/admin/language/en-gb/extension/payment/cardconnect.php
> CardConnect Changes

- upload/admin/controller/extension/payment/laybuy.php
> Lay-Buy Changes

- upload/catalog/controller/extension/payment/klarna_checkout.php
> 2.3 klarna checkout fix

- upload/system/library/language.php
Fix for backwards compatibility https://github.com/opencart/opencart/issues/4645
> Backwards Compatibility Fix

- upload/admin/index.php
- upload/admin/language/en-gb/extension/dashboard/activity.php
- upload/admin/language/en-gb/extension/dashboard/chart.php
- upload/admin/language/en-gb/extension/dashboard/customer.php
- upload/admin/language/en-gb/extension/dashboard/map.php
- upload/admin/language/en-gb/extension/dashboard/online.php
- upload/admin/language/en-gb/extension/dashboard/order.php
- upload/admin/language/en-gb/extension/dashboard/recent.php
- upload/admin/language/en-gb/extension/dashboard/sale.php
- upload/index.php
- Updated version to 2.3.0.3 in index files
> - Fix for entry_width in dashboard modules

- upload/catalog/view/javascript/common.js
> missing ">" for closing div tag

- upload/admin/model/localisation/language.php
> - banner_image_description reference in language model removed

- upload/admin/model/localisation/language.php
https://github.com/opencart/opencart/issues/4768#issuecomment-240175600
> Add banner image to language insert and delete

- upload/catalog/view/theme/default/stylesheet/stylesheet.css
Fixed issue by removing same line of CSS code existing twice in the file
> Fixed Issue #4764

- upload/admin/controller/extension/payment/klarna_checkout.php
- upload/admin/language/en-gb/extension/payment/klarna_checkout.php
- upload/admin/model/extension/payment/klarna_checkout.php
- upload/admin/view/template/extension/payment/klarna_checkout.tpl
- upload/catalog/controller/extension/module/klarna_checkout_module.php
- upload/catalog/controller/extension/payment/klarna_checkout.php
- upload/catalog/model/extension/payment/klarna_checkout.php
- upload/catalog/view/theme/default/template/extension/payment/klarna_checkout_sidebar.tpl
Adds ability to pass in shipping countries to iFrame + several bug fixes
@jamesallsup
> Klarna Checkout shipping countries

- upload/catalog/controller/product/category.php
Category links (canonical, prev, next) points to https if it is enabled
> Category links (canonical) points to https

- upload/admin/controller/extension/payment/klarna_checkout.php
- upload/admin/language/en-gb/extension/payment/klarna_checkout.php
- upload/admin/view/template/extension/payment/klarna_checkout.tpl
> Klarna Checkout version number

- upload/admin/model/extension/fraud/fraudlabspro.php
- upload/catalog/model/extension/payment/securetrading_pp.php
- upload/catalog/model/extension/payment/securetrading_ws.php
Organizing model. Creating space between = and '.
> Organizing model. Creating space between = and '.

- upload/admin/controller/extension/shipping/ec_ship.php
- upload/admin/language/en-gb/extension/shipping/ec_ship.php
- upload/admin/view/template/extension/shipping/ec_ship.twig
- upload/catalog/language/en-gb/extension/shipping/ec_ship.php
- upload/catalog/model/extension/shipping/ec_ship.php
> Adding EC-ship integration

- upload/admin/controller/common/reset.php
- upload/admin/controller/customer/customer.php
- upload/admin/controller/marketing/affiliate.php
- upload/admin/controller/user/user.php
- upload/catalog/controller/account/password.php
- upload/catalog/controller/account/register.php
- upload/catalog/controller/account/reset.php
- upload/catalog/controller/affiliate/password.php
- upload/catalog/controller/affiliate/register.php
- upload/catalog/controller/checkout/register.php
Adding html_entity_decode on password checking
> Adding html_entity_decode on password checking

- upload/admin/view/template/sale/order_form.tpl
Fixed issue with shipping methods error not showing because of json variable name being wrong.
> Fixed issue with shipping methods error

- upload/catalog/model/checkout/order.php
- upload/catalog/model/extension/fraud/fraudlabspro.php
* Fix the issue of fraud extension not being calling by changing "model_fraud_" to "model_extension_fraud_"
* Add device validation feature into fraudlabspro extension
> fix model_fraud_ issue and add device validation feature

- upload/admin/controller/design/menu.php
- upload/admin/model/design/menu.php
Signed-off-by: Lukáš Piják lukaspijak@gmail.com
> Typing error in upload/admin/model/design/menu.php in SQL "menut_id" and missing method getMenuModules()

- upload/admin/controller/extension/payment/klarna_checkout.php
- upload/admin/language/en-gb/extension/payment/klarna_checkout.php
- upload/admin/model/extension/payment/klarna_checkout.php
- upload/admin/view/template/extension/module/klarna_checkout_module.twig
- upload/admin/view/template/extension/payment/klarna_checkout.twig
- upload/admin/view/template/extension/payment/klarna_checkout_order_ajax.twig
- upload/catalog/controller/extension/module/klarna_checkout_module.php
- upload/catalog/controller/extension/payment/klarna_checkout.php
- upload/catalog/language/en-gb/extension/payment/klarna_checkout.php
- upload/catalog/model/extension/payment/klarna_checkout.php
- upload/catalog/view/theme/default/template/extension/payment/klarna_checkout_main.twig
- upload/catalog/view/theme/default/template/extension/payment/klarna_checkout_sidebar.twig
> Klarna Checkout 1.2 with Twig port

- upload/admin/controller/extension/payment/klarna_checkout.php
- upload/admin/language/en-gb/extension/payment/klarna_checkout.php
- upload/admin/model/extension/payment/klarna_checkout.php
- upload/admin/view/template/extension/payment/klarna_checkout.tpl
- upload/admin/view/template/extension/payment/klarna_checkout_order_ajax.tpl
- upload/catalog/controller/extension/module/klarna_checkout_module.php
- upload/catalog/controller/extension/payment/klarna_checkout.php
- upload/catalog/language/en-gb/extension/payment/klarna_checkout.php
- upload/catalog/model/extension/payment/klarna_checkout.php
- upload/catalog/view/theme/default/template/extension/payment/klarna_checkout_main.tpl
Fixes and new features
@jamesallsup
> Klarna Checkout 1.2

- upload/catalog/controller/extension/payment/klarna_checkout.php
> Klarna Checkout - Fix use of old order status

- upload/install/opencart.sql
> Made `shipping_company` the same character limit as `payment_company` in `oc_order`

- upload/admin/view/template/extension/extension/analytics.tpl
Only one extension can be installed.
Fixed endforeach.
> FIX analytics.tpl

- upload/system/library/session.php
> Check create_sid method

- upload/admin/controller/extension/payment/pp_express.php
Fix for Notice: Undefined index: parent_id in /upload/admin/model/payment/pp_express.php on line 64
> Fix for Notice: Undefined index: parent_id in pp_express.php on line 64

- upload/admin/view/stylesheet/stylesheet.css
- upload/admin/view/template/extension/store_list.tpl
> store list CSS fixed

- upload/system/.htaccess
If any module put there font and css inside config folder then it restricted to load.
> fix forbidden to load image and font file

- upload/admin/controller/extension/extension/dashboard.php
Fixed issue. Was not able to install and uninstall extension in dashboard.
Removed extra **dashboard_**
> Fixed issue with installing and uninstalling dashboard extensions

- upload/catalog/model/account/custom_field.php
Removed cf.status = '1' duplicated check (line 15)
> Removed duplicate-check in SQL-query

- upload/admin/controller/extension/modification.php
Fixing issue #5189 where 
> after refreshing modifications, the success message is not displayed.
> Fix issue #5189

- upload/admin/controller/setting/setting.php
- upload/admin/view/template/setting/setting.twig
- upload/catalog/controller/mail/affiliate.php
- upload/catalog/controller/mail/order.php
- upload/catalog/controller/mail/register.php
- upload/catalog/model/catalog/review.php
Replaced `config_alert_mail` with `config_mail_alert_mail` as per settings page.
> Fixed Additional Alert Emails

- upload/admin/controller/setting/setting.php
- upload/admin/view/template/setting/setting.twig
- upload/catalog/controller/mail/affiliate.php
- upload/catalog/controller/mail/order.php
- upload/catalog/controller/mail/register.php
- upload/catalog/model/catalog/review.php
Reverts opencart/opencart#5259
> Revert "Fixed Additional Alert Emails"

- upload/admin/language/en-gb/extension/shipping/auspost.php
- upload/admin/language/en-gb/extension/shipping/citylink.php
- upload/admin/language/en-gb/extension/shipping/fedex.php
- upload/admin/language/en-gb/extension/shipping/flat.php
- upload/admin/language/en-gb/extension/shipping/free.php
- upload/admin/language/en-gb/extension/shipping/item.php
- upload/admin/language/en-gb/extension/shipping/parcelforce_48.php
- upload/admin/language/en-gb/extension/shipping/pickup.php
- upload/admin/language/en-gb/extension/shipping/royal_mail.php
- upload/admin/language/en-gb/extension/shipping/ups.php
- upload/admin/language/en-gb/extension/shipping/usps.php
- upload/admin/language/en-gb/extension/shipping/weight.php
https://github.com/opencart/opencart/issues/5271
> Fixed Missing Text_Extension

- upload/install/model/install/install.php
> Incorrect name field in oc_api table when install

- upload/admin/controller/localisation/language.php
- upload/admin/controller/localisation/length_class.php
> line break in 2 controllers (into dev branch)

- upload/system/library/document.php
> typo "postion" in library document (into master branch)

- upload/system/library/session.php
Fix for https://github.com/opencart/opencart/issues/5100
> Update system/library/session.php remove session character limitation

- upload/.htaccess.txt
Also some spelling corrections
> Update htaccess download path

- upload/catalog/model/extension/shipping/sf_express.php
Update sf_express.php mistyped.
> Update sf_express.php mistyped

- upload/install/opencart.sql
Increased "key" character limit as per https://github.com/opencart/opencart/issues/5408
> Increase "key" Character Limit In oc_setting

- upload/admin/controller/marketplace/marketplace.php
- upload/admin/view/template/marketplace/marketplace_info.twig
> Fixed Extension Info Page Formatting & Popup Images

- upload/admin/view/stylesheet/stylesheet.css
- upload/admin/view/template/marketplace/marketplace_info.twig
@danielkerr 
Changed extension info to fixed width to match formatting of OpenCart website
> Extension Info Page Formatting

- upload/admin/controller/marketplace/marketplace.php
- upload/admin/language/en-gb/marketplace/marketplace.php
- upload/admin/view/template/marketplace/marketplace_info.twig
- upload/admin/view/template/marketplace/marketplace_list.twig
@danielkerr 
https://github.com/opencart/opencart/issues/5440
> Added Rating Total To Extension Page

- upload/admin/view/stylesheet/stylesheet.css
- upload/admin/view/template/marketplace/marketplace_list.twig
@danielkerr 
Changed it from 4 extensions to 6 extensions per row.  The extension div sizes are now closer to the OpenCart site.
> Updated Marketplace List

- upload/admin/controller/catalog/category.php
- upload/admin/controller/catalog/information.php
- upload/admin/controller/catalog/product.php
- upload/admin/controller/extension/module/html.php
- upload/admin/controller/extension/openbay/ebay.php
- upload/admin/controller/marketing/contact.php
- upload/admin/view/template/catalog/category_form.tpl
- upload/admin/view/template/catalog/information_form.tpl
- upload/admin/view/template/catalog/product_form.tpl
- upload/admin/view/template/extension/module/html.tpl
- upload/admin/view/template/extension/openbay/ebay_new.tpl
- upload/admin/view/template/marketing/contact.tpl
> Add multilingual summernote

- upload/admin/controller/catalog/category.php
- upload/admin/controller/catalog/information.php
- upload/admin/controller/catalog/product.php
- upload/admin/controller/extension/module/html.php
- upload/admin/controller/extension/openbay/ebay.php
- upload/admin/controller/marketing/contact.php
- upload/admin/view/template/catalog/category_form.tpl
- upload/admin/view/template/catalog/information_form.tpl
- upload/admin/view/template/catalog/product_form.tpl
- upload/admin/view/template/extension/module/html.tpl
- upload/admin/view/template/extension/openbay/ebay_new.tpl
- upload/admin/view/template/marketing/contact.tpl
Reverts opencart/opencart#4530
> Revert "Add multilingual summernote"

- upload/admin/view/stylesheet/stylesheet.css
- upload/admin/view/template/marketplace/marketplace_list.twig
Reverts opencart/opencart#5471
> Revert "Updated Marketplace List"

- upload/catalog/model/design/translation.php
@danielkerr 
Added global text support to translator.  (e.g. route = en-gb)
> Fixed Global Text Support In Translator

- upload/system/library/session/file.php
strrpos parameters reversed. substr needs pos + 1.
> Update session path

- upload/admin/controller/sale/order.php
Bug where opencart instantiate an variable with quotation marks where it should be a number
> Bug with php 7

- upload/admin/view/stylesheet/bootstrap.css
- upload/admin/view/stylesheet/stylesheet.css
- upload/admin/view/template/common/column_left.twig
- upload/admin/view/template/extension/dashboard/customer_info.twig
- upload/admin/view/template/extension/dashboard/online_info.twig
- upload/admin/view/template/extension/dashboard/sale_info.twig
> CSS updated and commit test

- upload/admin/view/stylesheet/bootstrap.css
- upload/admin/view/stylesheet/stylesheet.css
> Admin CSS updated

- upload/admin/view/stylesheet/bootstrap.css
- upload/admin/view/stylesheet/sass/bootstrap/_variables.scss
> Admin button CSS fixed

- upload/admin/view/javascript/common.js
- upload/admin/view/stylesheet/bootstrap.css
- upload/admin/view/stylesheet/sass/bootstrap/_alerts.scss
- upload/admin/view/stylesheet/sass/bootstrap/_breadcrumbs.scss
- upload/admin/view/stylesheet/sass/bootstrap/_navbar.scss
- upload/admin/view/stylesheet/sass/bootstrap/_variables.scss
- upload/admin/view/stylesheet/stylesheet.css
- upload/admin/view/template/common/header.twig
> Admin header html & CSS fixed

- upload/admin/view/stylesheet/bootstrap.css
- upload/admin/view/stylesheet/sass/bootstrap/_variables.scss
- upload/admin/view/stylesheet/sass/bootstrap/mixins/_alerts.scss
> CSS updated

- upload/admin/view/stylesheet/stylesheet.css
hidden opencart font-awesome icon on mobile view
> hidden opencart font-awesome icon on mobile view

- upload/admin/model/report/statistics.php
@danielkerr 
- Removed `echo $code;`
> Removed Testing Code From Statistics

- upload/admin/view/stylesheet/stylesheet.css
@danielkerr 
- Fixed ASC & DESC symbols to display the correct orientation when sorting lists.
> Fixed ASC / DESC Symbols

- upload/admin/controller/design/translation.php
- upload/admin/language/en-gb/design/translation.php
- upload/admin/model/design/translation.php
- upload/admin/view/template/design/translation_list.twig
@danielkerr 
- Added Value column
- Fixed sorting for route & key columns
> Updated Translation List

- upload/admin/view/template/customer/customer_form.twig
@danielkerr 
- Added missing `</div>`
> Customer Form - Missing </div>

- upload/catalog/controller/mail/order.php
Fix missing order_status #5593
> Fix missing order_status

- upload/admin/controller/tool/backup.php
Take a look if it OK. Posible fix for #5512
> Posible backup fix

- upload/admin/controller/extension/shipping/usps.php
- upload/admin/view/template/extension/shipping/usps.twig
- upload/catalog/model/extension/shipping/usps.php
https://github.com/opencart/opencart/issues/5574
> Fix For USPS

- upload/catalog/model/extension/total/coupon.php
- upload/catalog/model/extension/total/reward.php
- upload/catalog/model/extension/total/voucher.php
Prevent totals language to replace cart language values
> Prevent totals language replacement

- upload/admin/view/template/marketplace/marketplace_info.twig
Missing language variables.
Still missing (because not in language file, therefore cannot be replaced):
Progress
Available Installs
Download Name
Action
View all extensions
Member since
Get Support
> Update marketplace_info.twig (missing language vars)

- upload/admin/controller/startup/error.php
- upload/admin/controller/tool/backup.php
- upload/admin/language/en-gb/tool/backup.php
- upload/admin/view/template/tool/backup.twig
During import success messages is removed all the time. I think is better a progress line and at the end of import is the success message.
> Import progress

- upload/catalog/model/extension/shipping/weight.php
> Fix shipping weight

- upload/catalog/controller/extension/payment/bank_transfer.php
Details missing from comment during checkout
> Fix bank transfer

- upload/admin/controller/sale/order.php
Error Print Shipping List in PHP 7.1
admin/index.php?route=sale/order/shipping&user_token=...
Warning: A non-numeric value encountered in ...\admin\controller\sale\order.php on line 1818
> Fix Print Shipping List in PHP 7.1

- upload/admin/controller/extension/shipping/fedex.php
Removed duplicate code in fedex shipping module on admin side for postcode error display
> Fedex module : Removed duplicate code in admin side for postcode error display

- upload/admin/controller/tool/backup.php
Replace:
ini_get('upload_tmp_dir')
For:
DIR_UPLOAD
Same as installer.php
> Fix backup.php for Windows and Linux

- upload/admin/controller/design/theme.php
When editing a theme (not default), the default template files are not displayed for editing, if template files are not found.
Tested with multiple themes. 👍
> Fix theme.php

- upload/admin/controller/design/translation.php
- upload/admin/view/template/design/translation_form.twig
Language Editor for multiple languages.
- Fix breadcrumb
- Default language automatic in add translation
- Blocks fields while loading in add translation
- Locate language file selected in add translation
- Removed language files reading in edit translation
- Blocks fields in edit translation
Tested with multiple languages. 👍
> Fix Language Editor for multiple languages

- upload/admin/view/template/tool/backup.twig
> Fix template backup.twig

- upload/admin/language/en-gb/design/seo_url.php
> Fix language seo_url.php in admin

- upload/admin/controller/marketplace/marketplace.php
> Fix marketplace.php

- upload/install/controller/install/step_3.php
After install...
Parse error: syntax error, unexpected 'language' (T_STRING), expecting ',' or ')' in
Error:
config.php
admin/config.php
> Fix install step_3.php in write config.php

- upload/admin/view/template/design/translation_list.twig
Replace:
{{ text_edit }}
For:
{{ text_list }}
> Fix template translation_list.twig

- upload/admin/view/template/customer/customer_list.twig
Add in table:
`<div class="table-responsive"></div>`
> Fix table responsive in customer_list.twig

- upload/admin/view/template/sale/order_list.twig
Add in table:
`<div class="table-responsive"></div>`
> Fix table responsive in order_list.twig

- upload/admin/language/en-gb/marketplace/marketplace.php
- upload/admin/view/template/catalog/category_form.twig
- upload/admin/view/template/catalog/information_form.twig
- upload/admin/view/template/catalog/product_form.twig
- upload/admin/view/template/marketplace/marketplace_info.twig
Included:
Added summernote translation in product_form.twig, information_form.twig and category_form.twig
https://github.com/opencart/opencart/pull/5321
> Missing language in marketplace

- upload/system/library/squareup.php
This has been done in compliance with the latest requirements by Square.
> Add PAYMENTS_WRITE scope to Square payment extension.

- upload/system/library/document.php
> typo "postion" in library document (into dev branch)

- upload/admin/view/template/extension/total/sub_total.twig
https://github.com/opencart/opencart/pull/5475
> Missing " in sub_total.twig

- upload/admin/view/template/marketplace/marketplace_info.twig
Included:
Modified minus for trash icon
* Icon more understandable for newbies
> Missing language in marketplace_info.twig

- upload/admin/view/template/marketplace/installer_history.twig
Icon more understandable for newbies
> Modified minus for trash in installer_history.twig

- upload/catalog/model/catalog/category.php
- upload/catalog/model/catalog/information.php
- upload/catalog/model/catalog/product.php
- upload/catalog/model/design/layout.php
- upload/catalog/model/extension/openbay/amazon_order.php
- upload/catalog/model/extension/openbay/amazonus_order.php
Model. strong typing return integer
> Model. strong typing return integer

- upload/catalog/controller/extension/payment/cardinity.php
- upload/catalog/view/theme/default/template/extension/payment/cardinity.twig
- Fixed issue related with #5200.
- Changed default submitted country from shipping to payment, which is more important.
> Cardinity payment gateway fixes

- upload/admin/language/en-gb/marketplace/marketplace.php
- upload/admin/view/template/marketplace/marketplace_info.twig
Add button "Forgot PIN" in marketplace_info purchase pop-up. This will link to Contact Us page on OpenCart.com.
> Add button "Forgot PIN" in marketplace_info purchase pop-up

- upload/catalog/view/theme/default/template/account/address_form.twig
- upload/catalog/view/theme/default/template/account/edit.twig
- upload/catalog/view/theme/default/template/account/forgotten.twig
- upload/catalog/view/theme/default/template/account/newsletter.twig
- upload/catalog/view/theme/default/template/account/password.twig
- upload/catalog/view/theme/default/template/account/reset.twig
> Re-order buttons continue/back

- upload/catalog/controller/startup/seo_url.php
> Correct common/home SEO URL

- upload/install/controller/install/step_3.php
- upload/system/library/db/mysqli.php
> mysqli error message check for connect_errno

- upload/catalog/controller/startup/startup.php
$language_codes = array_column($languages, 'code');
will make the array being like
[ 0 => 'code1', 1 => 'code2']
which will that this function array_key_exists($code, $language_codes)
all through the class failed.
I changed the Line 48 to
$language_codes = array_column($languages, 'language_id', 'code');
make the array being like
['code1' => language_id1, 'code2' => language_id2]
And also change the code on Line 123 to
$this->config->set('config_language_id', $language_codes[$code]);
Readjustment The if statment to reduce the array search
Tested on my store and checked with phpcs.
> fix language switch problem and reduce array key search times

- upload/admin/controller/tool/upgrade.php
- upload/admin/language/en-gb/tool/upgrade.php
- upload/admin/view/stylesheet/stylesheet.css
- upload/admin/view/template/tool/upgrade.twig
tool/upgrade page, link, css fixed
> tool/upgrade page, link, css fixed

- upload/catalog/view/theme/default/template/extension/payment/pp_express.twig
> Paypal express fix

- upload/admin/controller/startup/permission.php
- upload/admin/view/template/extension/extension/menu.twig
> Added Edit button to Menu extensions

- upload/admin/controller/common/reset.php
- upload/catalog/controller/account/reset.php
> Fix reset action url

- upload/admin/controller/extension/fraud/fraudlabspro.php
- upload/admin/view/template/extension/fraud/fraudlabspro_info.twig
- upload/catalog/model/extension/fraud/fraudlabspro.php
minor fixes and support billing address and ship-to name validation for FraudLabs Pro fraud extension
> [fraud_fraudlabspro] minor fixes and support billing address and ship-to name validation

- upload/catalog/controller/account/edit.php
**Replacing:**
`$custom_fields = $this->model_account_custom_field->getCustomFields('account', $this->config->get('config_customer_group_id'));`
**For:**
`$custom_fields = $this->model_account_custom_field->getCustomFields($this->config->get('config_customer_group_id'));`
> Fix catalog edit account validate

- upload/admin/controller/mail/customer.php
- upload/admin/language/en-gb/mail/customer_approve.php
- upload/admin/language/en-gb/mail/customer_deny.php
- upload/admin/view/template/mail/customer_approve.twig
- upload/admin/view/template/mail/customer_deny.twig
- upload/catalog/controller/mail/affiliate.php
- upload/catalog/controller/mail/forgotten.php
- upload/catalog/controller/mail/order.php
- upload/catalog/controller/mail/register.php
- upload/catalog/controller/mail/transaction.php
- upload/catalog/language/en-gb/mail/affiliate.php
- upload/catalog/language/en-gb/mail/forgotten.php
- upload/catalog/language/en-gb/mail/register.php
- upload/catalog/view/theme/default/template/mail/affiliate.twig
- upload/catalog/view/theme/default/template/mail/affiliate_alert.twig
- upload/catalog/view/theme/default/template/mail/forgotten.twig
- upload/catalog/view/theme/default/template/mail/order_alert.twig
- upload/catalog/view/theme/default/template/mail/order_edit.twig
- upload/catalog/view/theme/default/template/mail/register.twig
- upload/catalog/view/theme/default/template/mail/register_alert.twig
- upload/catalog/view/theme/default/template/mail/transaction.twig
> Mail html updated

- upload/system/library/url.php
Some of the fixes from #6196 where done in e034783. This pr. avoids conflicts with the latest changes and aims to comply with the comments given by @danielkerr given in #6196.
> Clean up phpDoc in url class

- upload/admin/controller/marketplace/install.php
Required for some payment extensions
> Add permission in image/payment

- upload/admin/controller/user/api.php
- upload/admin/view/template/user/api_form.twig
- upload/catalog/view/theme/default/template/extension/module/featured.twig
Also adjust for the twig prevent the ip list disappear
when the user submit the form without modify permission.
> Edition for issue #6118 & #5876

- upload/admin/controller/common/security.php
- upload/admin/language/en-gb/common/security.php
- upload/admin/view/template/common/security.twig
Update Security Notification in admin area
> Update Security Notification

- upload/catalog/language/en-gb/product/category.php
Fix product/category language key.
> Fix product/category language key.

- upload/admin/controller/setting/setting.php
- upload/admin/model/design/seo_url.php
- upload/admin/view/template/extension/payment/pp_express_refund.twig
- upload/admin/view/template/extension/payment/securetrading_ws.twig
- upload/admin/view/template/extension/payment/squareup.twig
- upload/admin/view/template/mail/customer_approve.twig
- upload/admin/view/template/mail/customer_deny.twig
- upload/admin/view/template/setting/setting.twig
Add timezone setting on store setting page
> Add timezone setting on store setting page

- upload/admin/controller/extension/payment/bluepay_redirect.php
- upload/admin/controller/extension/payment/g2apay.php
- upload/admin/model/extension/payment/bluepay_redirect.php
- upload/admin/model/extension/payment/g2apay.php
- upload/admin/model/extension/payment/pp_payflow_iframe.php
- upload/catalog/controller/extension/payment/bluepay_redirect.php
- upload/catalog/controller/extension/payment/g2apay.php
- upload/catalog/model/extension/payment/bluepay_redirect.php
- upload/catalog/model/extension/payment/g2apay.php
- upload/catalog/model/extension/payment/sagepay_direct.php
- upload/catalog/model/extension/payment/sagepay_server.php
Change the class name where errors according to PSR.
Change the class name to words according to the underscore in the file name.
> differences in class name

- upload/admin/controller/startup/startup.php
- upload/catalog/controller/extension/payment/sagepay_server.php
Check config_timezone is exists or not
Fix the error Notice: date_default_timezone_set(): Timezone ID '' is invalid in C:\xampp\htdocs\OpenCart\master-test\admin\controller\startup\startup.php on line 17
And JSON error popup
> Error from admin/controller/startup/startup.php

- upload/admin/controller/setting/setting.php
The previous function that display the time zone difference in hours it is wrong.
> Fixed list Time Zone

- upload/admin/view/template/extension/payment/securetrading_ws.twig
the second loop is wrong it should be an IF statement
> Fix bug with loop inside loop

- upload/catalog/controller/startup/sass.php
- upload/catalog/view/theme/default/stylesheet/_stylesheet.scss
- upload/catalog/view/theme/default/stylesheet/bootstrap.css
- upload/catalog/view/theme/default/stylesheet/stylesheet.css
- upload/catalog/view/theme/default/template/account/account.twig
- upload/catalog/view/theme/default/template/account/address_list.twig
- upload/catalog/view/theme/default/template/account/affiliate.twig
- upload/catalog/view/theme/default/template/account/download.twig
- upload/catalog/view/theme/default/template/account/newsletter.twig
- upload/catalog/view/theme/default/template/account/order_list.twig
- upload/catalog/view/theme/default/template/account/password.twig
- upload/catalog/view/theme/default/template/account/recurring_list.twig
- upload/catalog/view/theme/default/template/account/return_form.twig
- upload/catalog/view/theme/default/template/account/return_list.twig
- upload/catalog/view/theme/default/template/account/reward.twig
- upload/catalog/view/theme/default/template/account/tracking.twig
- upload/catalog/view/theme/default/template/account/transaction.twig
- upload/catalog/view/theme/default/template/account/wishlist.twig
- upload/catalog/view/theme/default/template/affiliate/login.twig
- upload/catalog/view/theme/default/template/affiliate/register.twig
- upload/catalog/view/theme/default/template/common/cart.twig
- upload/catalog/view/theme/default/template/common/header.twig
- upload/catalog/view/theme/default/template/common/success.twig
- upload/catalog/view/theme/default/template/product/category.twig
- upload/catalog/view/theme/default/template/product/manufacturer_info.twig
- upload/catalog/view/theme/default/template/product/product.twig
- upload/catalog/view/theme/default/template/product/search.twig
- upload/catalog/view/theme/default/template/product/special.twig
Store Front CSS and bugs fixed
> Store Front CSS and bugs fixed

- upload/admin/controller/extension/module/amazon_login.php
- upload/admin/controller/extension/module/amazon_pay.php
- upload/admin/controller/extension/payment/amazon_login_pay.php
- upload/admin/language/en-gb/extension/payment/amazon_login_pay.php
- upload/admin/model/extension/payment/amazon_login_pay.php
- upload/admin/view/template/extension/module/amazon_login.twig
- upload/admin/view/template/extension/module/amazon_pay.twig
- upload/admin/view/template/extension/payment/amazon_login_pay.twig
- upload/admin/view/template/extension/payment/amazon_login_pay_order.twig
- upload/catalog/controller/extension/module/amazon_login.php
- upload/catalog/controller/extension/module/amazon_pay.php
- upload/catalog/controller/extension/payment/amazon_login_pay.php
- upload/catalog/model/extension/payment/amazon_login_pay.php
- upload/catalog/view/theme/default/template/extension/module/amazon_login.twig
- upload/catalog/view/theme/default/template/extension/module/amazon_pay.twig
- upload/catalog/view/theme/default/template/extension/payment/amazon_login_pay_address.twig
- upload/catalog/view/theme/default/template/extension/payment/amazon_login_pay_confirm.twig
- upload/catalog/view/theme/default/template/extension/payment/amazon_login_pay_payment.twig
- Improvement: The language 'American' is renamed to 'American English'.
- Improvement: Error reporting in Sandbox mode is now in the JavaScript console instead of HTML elements.
- Improvement: ModelExtensionPaymentAmazonLoginPay:validateResponse now skips debug logging if the request is for details validation.
- Improvement: Debug logger no longer throws an error in case the class index is not defined.
- Improvement: Set a maximum of 150 characters for the IPN URL.
- Improvement: Action buttons in Payment Address and Payment Method are now the same width as the main container.
- Improvement: IPN token and IPN URL inputs have been moved after the mandatory app credentials.
- Bug fix: OffAmazonPayments.Button now uses the Merchant ID instead ot the Client ID.
- Bug fix: The redirect after …
> Various fixes and improvements to Amazon Login/Pay.

- upload/catalog/view/theme/default/template/extension/payment/pp_express.twig
Always in sandbox mode (credit @howdu)
> Paypal express fix (re-apply #5983)

- upload/catalog/view/theme/default/template/extension/payment/cardinity.twig
> Fix Cardinity payment view

- upload/catalog/controller/extension/feed/google_sitemap.php
> escape XML in Google Sitemap output

- upload/admin/view/template/catalog/category_list.twig
Issue resolved #6990 for the category page sort column classes.
> [Issue Fixed #6990 : Category Listing page sorting column issue.]

- upload/admin/view/template/catalog/product_option_form.twig
> [Issue Fixed #7003 : language index added for product reward point in product option section].

- upload/catalog/model/extension/payment/amazon_login_pay.php
The previous pull request was missing this final amendment.
> Bug fix: Add missing SELECT field for Amazon Pay and Login with Amazon.

- upload/catalog/view/theme/default/template/checkout/cart.twig
https://fontawesome.com/icons?d=gallery&q=refresh
> Change refresh icon to sync-alt

- upload/system/library/cart/customer.php
It tries to use the customer_id prop before setting it.
> Fix customer password rehash

- upload/admin/language/en-gb/extension/extension/promotion.php
> Missing translation file: promotion.php

- upload/admin/model/sale/order.php
Fixed issue for the admin side sale/order model wrong alias used in the filter clause: issue #7501
> Fixed issue for the sale/order model wrong alias : issue #7501

- upload/admin/controller/mail/customer.php
Proposed solution for - [3.0.3.2 - master] Customer registration - mail login link is wrong #7390
> Update customer.php - [solution for] Customer registration - mail login link is wrong #7390

- upload/catalog/model/extension/shipping/ups.php
https://forum.opencart.com/viewtopic.php?f=198&t=201339#p712017
> Update UPS shipping URL

- upload/catalog/model/setting/store.php
$data is parameterized but not being used in model **catalog/model/setting/store.php**
> removed unused parameter

- upload/admin/view/template/catalog/option_form.twig
Fixed option values sort order placeholder issue
> fixed placeholder issue on option page

- upload/admin/controller/catalog/recurring.php
- upload/admin/view/template/catalog/recurring_list.twig
Fixed Admin end recurring column sort issue
> Fixed Admin end recurring column sort issue

- upload/admin/view/javascript/jquery/datetimepicker/bootstrap-datetimepicker.js
Everywhere in admin where datetimepicker is used error is showing in Console when we click on  it.
> Fixed console error for the datetimepicker js library

- upload/admin/view/stylesheet/stylesheet.css
Fixed CSS issue of the warning message
> Fixed CSS issue of the warning message

- upload/admin/controller/setting/setting.php
Fixed get heading_title captcha in the store settings
> Fixed get heading_title captcha in the store settings

- upload/admin/controller/sale/return.php
- upload/admin/model/sale/return.php
- upload/admin/view/template/sale/return_list.twig
> fixed admin panel returns bug in status sorting

- upload/catalog/view/theme/default/template/account/newsletter.twig
> fixed newsletter label issue with radio buttons

- upload/admin/controller/sale/recurring.php
fixed recurring order sorting issue.
[https://github.com/opencart/opencart/issues/7686](https://github.com/opencart/opencart/issues/7686)
> fixed recurring order sorting issue

- upload/catalog/view/javascript/common.js
> fixed modal close button issue on pages like register or affiliate

- upload/admin/controller/customer/custom_field.php
fixed Admin end add new custom field page showing fatal error
[https://github.com/opencart/opencart/issues/7688](https://github.com/opencart/opencart/issues/7688)
> fixed Admin end add new custom field page showing fatal error

- upload/admin/model/design/seo_url.php
> fixed admin panel SEO url sorting issue

- upload/admin/controller/customer/customer.php
- upload/admin/view/template/customer/customer_form.twig
fixed fatal error issue in customer form page
> fixed fatal error issue in customer form page

- upload/admin/controller/setting/store.php
> issue fixed #7677

- upload/catalog/model/extension/total/reward.php
- upload/catalog/view/theme/default/template/extension/total/reward.twig
> fixed reward point bug

- upload/catalog/view/theme/default/template/account/download.twig
> fixed download icon bug under customer downloads list

- upload/catalog/model/extension/total/voucher.php
> fixed voucher system issues

- upload/admin/view/template/localisation/language_form.twig
Resolved design issue at language add form page.
http://i.prntscr.com/bEsZhVdCSDu-ff-wdEk-aw.png
> Resolved design issue at language add form page.

- upload/admin/view/template/localisation/currency_form.twig
Resolved currency page layout  issue
> Resolved currency page layout  issue

- upload/admin/view/template/catalog/product_form.twig
fixed option value not saving issue
> fixed option value not saving issue

- upload/admin/view/template/catalog/download_form.twig
- upload/admin/view/template/catalog/review_form.twig
- upload/admin/view/template/marketing/coupon_form.twig
- upload/admin/view/template/marketing/marketing_form.twig
- upload/admin/view/template/sale/return_form.twig
- upload/admin/view/template/sale/voucher_form.twig
- upload/admin/view/template/setting/setting.twig
- upload/admin/view/template/setting/store_form.twig
fixes for all admin pages. @jeffreyeng-opencart similar issues #7722  #7719 but considered only two pages.
> fixed some layout issues when error message is displayed

- upload/admin/view/stylesheet/stylesheet.css
fixed css issue for the error message on textarea field,checkbox etc.
> fixed css issue for the error message on textarea field,checkbox etc

- upload/admin/controller/catalog/attribute.php
- upload/admin/controller/catalog/attribute_group.php
- upload/admin/controller/catalog/category.php
- upload/admin/controller/catalog/download.php
- upload/admin/controller/catalog/filter.php
- upload/admin/controller/catalog/information.php
- upload/admin/controller/catalog/manufacturer.php
- upload/admin/controller/catalog/option.php
- upload/admin/controller/catalog/product.php
- upload/admin/controller/catalog/recurring.php
- upload/admin/controller/catalog/review.php
fixed the blank space issue in the admin end catalog section
> fixed the blank space issue in the admin end catalog section

- upload/catalog/controller/extension/module/latest.php
Function name has been changed in master branch.
> Latest Module Model Function Name

- upload/admin/model/catalog/product.php
The order of options changes every time the product is edited
> Product Options Sort Order

- upload/admin/controller/marketing/coupon.php
See: https://github.com/opencart/opencart/issues/8063
> Set correct length for code

- upload/admin/language/en-gb/marketing/coupon.php
According to this commit https://github.com/opencart/opencart/commit/6b83ae0895cae5277e72bcd0121e68d303d1433c
is here the corrected text.
> Update coupon error text

- upload/admin/view/template/sale/order_form.twig
Line 747: Added the missing `else` value for the input's value attribute for the custom field of type `text`
> Fix admin order_form view template

- upload/catalog/view/theme/default/template/account/register.twig
> Multi Customer Group Display on Register Page

- upload/admin/controller/common/pagination.php
- upload/catalog/controller/common/pagination.php
Pagination does not appear when all the items on page are deleted. If there is more than one page, pagination is required to go back. Enabled pagination for go to previous page.
> Enabled pagination for go to previous page.

- upload/admin/controller/common/filemanager.php
Replace function array_splice to array_slice.
> Fixed error in Pagination in Filemanager

- upload/admin/controller/catalog/filter.php
- upload/admin/language/en-gb/catalog/filter.php
> fixed filter values issue

- upload/admin/view/template/common/security.twig
- upload/catalog/view/theme/default/template/account/reset.twig
- upload/catalog/view/theme/default/template/information/tracking.twig
- upload/install/view/template/upgrade/upgrade.twig
Typos in html: duplicated code and wrong tags,
> Fix twig typos from Issue #7774

- upload/system/config/admin.php
- upload/system/config/catalog.php
- upload/system/config/default.php
- upload/system/framework.php
- upload/system/library/url.php
> Several fixes

- upload/admin/view/template/catalog/attribute_form.twig
fixed attribute required mark issue
> fixed attribute required mark issue

- upload/catalog/view/theme/default/template/extension/module/slideshow.twig
Removed slide swiping when there is only one banner
> Fixed slideshow module

- upload/admin/model/sale/order.php
Add an ability to admin/model/sale/order.php::getOrders() by user's e-mail address
> Add filter_email; close #6429

- upload/admin/view/template/sale/order_shipping.twig
Reverts opencart/opencart#6709
> Revert "fixes Jquery and fontawesome link"

- upload/admin/view/javascript/common.js
listen for click events only in IE
> fix admin form repeat submit bug

- docs/Coding-Standards.md
- docs/Creating-a-pull-request.md
- docs/Engine.md
- docs/Events-System-2.0.x.x-&-2.1.x.x.md
- docs/Events-System.md
- docs/Extension-Building-Tutorial-Part-1.md
- docs/Extension-System.md
- docs/Helpers.md
- docs/Home.md
- docs/Library.md
- docs/Log-In-with-PayPal.md
- docs/Modification-System.md
- docs/OpenCart-Basics.md
- docs/OpenCart-Extension-Development-Guide.md
- docs/Upgrading-themes-from-2.3-to-3.0.md
- docs/_-Wiki-Home-_.md
- docs/_Footer.md
- docs/_Sidebar.md
Since github doesn't allow to create PRs into wiki repository, there is no way how to make contributions from community and improve developer docs.
**Proposal:** move wiki to main repo, so that any body can edit it.
**To be done:** put `_Header.md` into wiki with content:
```
```
> Move wiki to main repo

- upload/catalog/controller/extension/module/featured.php
We have several featured modules across the page with different headers.
This change introduces flexibility for the module header.
> Flexible featured module header

- upload/.htaccess.txt
Added missing escape character for .twig extension in .htaccess.txt
> Added missing escape character in .htaccess.txt

- upload/admin/view/template/marketing/contact.twig
Fix duplicate entries not being removed for customers, affiliates, & products.
> Fix duplicate entries not being removed in Admin > Marketing > Mail

- upload/admin/view/stylesheet/stylesheet.css
'control-label' is a class from the old version of bootstrap
> Wrong class in stylesheet.css

- upload/catalog/view/theme/default/template/extension/module/bestseller.twig
- upload/catalog/view/theme/default/template/extension/module/featured.twig
- upload/catalog/view/theme/default/template/extension/module/latest.twig
- upload/catalog/view/theme/default/template/extension/module/special.twig
- upload/catalog/view/theme/default/template/product/manufacturer_info.twig
- upload/catalog/view/theme/default/template/product/product.twig
> Updated product-list view

- upload/catalog/model/account/address.php
Update session address values when customer changes default address
> Customer change default address

- upload/admin/controller/setting/store.php
- upload/catalog/view/theme/default/template/information/contact.twig
[Issue Fixed #6892 : Store Location related issue resolved on admin and catalog end for the multistore.]
> [Issue Fixed #6892 : Store Location related issue resolved on admin and catalog end for the multistore.]

- upload/admin/language/en-gb/mail/gdpr_export.php
- upload/catalog/language/en-gb/information/gdpr.php
- upload/catalog/language/en-gb/mail/gdpr.php
Source: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32016R0679
> GDPR abbreviates to General Data Protection Regulation, not General Data Personal Request

- upload/admin/controller/common/header.php
- upload/catalog/controller/common/header.php
- upload/catalog/language/en-gb/common/header.php
> Remove unused code

- upload/catalog/view/theme/default/template/extension/module/carousel.twig
Removed slide swiping when there are only five or fewer banners.
> Fixed carousel module

- upload/catalog/controller/common/language.php
There is already a status check in the getLanguages method of the model
> Fix Language Controller

- upload/system/library/session/file.php
Incorrect condition when calculating probability
> Fix __destruct method in the class Session\File

- upload/catalog/controller/product/manufacturer.php
https://github.com/opencart/opencart/pull/8173/commits/ca186d9dfa8f239c351522dc74757f328b9a023c
> [3.0.x.x_] Removed tool/image from manufacturer index function

- upload/robots.txt
https://github.com/opencart/opencart/commit/8f0c7237a79ed7fa7fa6d6abf72938006f7930a6
> [3.0.x.x_Maintenance] Empty GET request causes errors and creates duplicates with different canonical URLs

- upload/catalog/controller/api/order.php
https://github.com/opencart/opencart/commit/045fa0b43c0a5c7545d918f9849b45e02849e036
> [3.0.x.x_Maintenance] When order editing is completed, delete added order status

- upload/admin/controller/common/dashboard.php
**01 - Extensions (Settings)**
**02 - Before modification**
**03 - After modification**
> fix: add extra modules to the dashboard

- upload/admin/controller/common/dashboard.php
https://github.com/opencart/opencart/pull/8154/files
> [3.0.x.x_] add extra modules to the dashboard fix

- upload/install/controller/event/theme.php
https://github.com/opencart/opencart/commit/9ad8639399d868201c70de1de4e745f403d18352
> [3.0.x.x_Maintenance] Added fix upgrade issue in oc version 2.x

- upload/catalog/controller/extension/module/featured.php
Unacceptable for multiple languages on the site
> Fix: module featured

- upload/catalog/controller/extension/module/bestseller.php
- upload/catalog/controller/extension/module/featured.php
- upload/catalog/controller/extension/module/latest.php
- upload/catalog/controller/extension/module/special.php
- upload/catalog/controller/product/category.php
- upload/catalog/controller/product/compare.php
The review status is defined in the controller ControllerProductThumb
> Fix: review status

- upload/admin/controller/sale/order.php
https://github.com/opencart/opencart/commit/fcb6ac11804eec600eff310fd9bb44d9a7fdab87
> Fix $option_weight non-numeric value warning

- upload/admin/controller/customer/customer.php
https://github.com/opencart/opencart/pull/6320
> Fix admin customer login by store

- upload/admin/controller/extension/report/customer_search.php
https://github.com/opencart/opencart/commit/37563807d31155fea1fcef914d13c5140a5f601a
> Fix customer search report pagination

- upload/install/opencart.sql
Regexp for route 'product/file_name'
> Fix: changed regexp for route

- upload/catalog/controller/information/information.php
https://github.com/opencart/opencart/pull/8263 for 3.0.x.x_Maintenance.
> Prevent terms pop up from being indexed

- upload/catalog/view/template/checkout/guest.twig
An unpleasant bug that adds spaces in value, which is why the placeholder and additional user fields are not displayed. Just replaced with ternary operator
> change if else to ternary in guest checkout

- upload/catalog/controller/product/manufacturer.php
https://github.com/opencart/opencart/pull/8444 and https://github.com/opencart/opencart/commit/e337ab755c802859667c0f3552e1fef3177bba26 for 3.0.x.x_Maintenance.
> Fix manufacturer canonical, next and prev links

- upload/extension/opencart/catalog/controller/payment/bank_transfer.php
https://github.com/opencart/opencart/compare/master...straightlight:patch-1
> Added isset to $this->session->data payment code.

- upload/admin/controller/sale/order.php
'Warning: A non-numeric value encountered php7.3 when generating the shipping note form admin end for the order
> Warning: A non-numeric value encountered php7.3

- upload/catalog/model/extension/shipping/fedex.php
https://github.com/opencart/opencart/issues/8611 resolved the issue
> resolved Fedex Error #8611

- upload/admin/controller/sale/order.php
Reverts opencart/opencart#8642
> Revert "Warning: A non-numeric value encountered php7.3"

- upload/catalog/model/extension/shipping/fedex.php
Resolved Fedex Error, changes done as suggested. #8643
> resolved the issue

- upload/catalog/model/localisation/currency.php
When the currency is disabled, it remains with the buyers
> currency cookie

- upload/admin/language/en-gb/marketing/contact.php
> Language text error

- upload/catalog/view/theme/default/template/account/affiliate.twig
The required symbol is missing at add affiliate account #8655
> Required symbol is missing at add affiliate account

- upload/admin/model/catalog/product.php
fixed recurring profile duplicate issue
> fixed recurring profile duplicate issue

- upload/install/controller/common/column_left.php
> Fixed a bug where languages in installation wouldn't load correctly

- upload/admin/model/catalog/product.php
https://github.com/opencart/opencart/commit/02ba790b06c2d901b8944398e3d4e70a36fdf30e
> Recurring profile duplicate fix

- upload/catalog/controller/startup/startup.php
https://github.com/opencart/opencart/pull/8439/files
> [3.0.x.x_Ma] Added PHP v7.4+ compatibility for country / zone - catalog/controller/startup/startup file.

- upload/catalog/controller/product/category.php
- upload/catalog/controller/product/manufacturer.php
- upload/catalog/controller/product/product.php
- upload/catalog/controller/product/search.php
- upload/catalog/controller/product/special.php
Necessary locatitions of https://github.com/opencart/opencart/issues/7218 for 3.0.x.x_Maintenance.
> Fix non well formed numeric value caused by bots

- upload/catalog/model/localisation/currency.php
https://github.com/opencart/opencart/pull/8653/files
> [3.0.x.x] Currency cookie fix

- upload/catalog/model/account/download.php
fixed Customer account download section listing issue [https://github.com/opencart/opencart/issues/8685](https://github.com/opencart/opencart/issues/8685)
> fixed Customer account download section listing issue

- upload/admin/controller/marketing/contact.php
- upload/admin/language/en-gb/extension/module/store.php
- upload/admin/view/template/extension/module/google_hangouts.twig
- upload/admin/view/template/extension/module/store.twig
Tooltip fixed [https://github.com/opencart/opencart/issues/8698](https://github.com/opencart/opencart/issues/8698)
> Tooltip fix

- upload/catalog/controller/common/footer.php
- upload/catalog/view/theme/default/template/common/footer.twig
- upload/system/library/document.php
Footer js and CSS suggestion  [https://github.com/opencart/opencart/issues/8705](https://github.com/opencart/opencart/issues/8705)
> implement the footer js and css link add point

- upload/admin/controller/sale/voucher.php
Besides, it should be added in a mail/voucher event.
> The mail instantiation does not need to be looped - controller/sale/voucher.php file.

- upload/admin/controller/report/online.php
Added string to filter_customer
> Update online.php - admin/controller/report/online.php file.

- upload/admin/controller/marketing/contact.php
Otherwise, new instantiation in a loop can be stopped after 200-300 times by default from Apache.
> Mail instantiation does not need to be looped - admin/controller/marketing/contact.php file.

- upload/admin/view/template/common/header.twig
fixed Header - Logged bar
[https://github.com/opencart/opencart/issues/8619](https://github.com/opencart/opencart/issues/8619)
> fixed Header - Logged bar

- upload/catalog/view/theme/default/stylesheet/stylesheet.css
Resolved issue https://github.com/opencart/opencart/issues/8701
> added scroll in cart

- upload/admin/controller/customer/customer.php
- upload/admin/view/template/customer/customer_form.twig
> displayed error on tracking field

- upload/catalog/controller/extension/total/reward.php
Added suggestion https://github.com/opencart/opencart/issues/8704
> Resolved reward validation issue

- upload/admin/controller/marketing/marketing.php
fixed marketing default ordering issue [https://github.com/opencart/opencart/issues/8829](https://github.com/opencart/opencart/issues/8829)
> fixed marketing default ordering issue

- upload/admin/controller/marketing/contact.php
- upload/admin/view/template/marketing/contact.twig
fixed [https://github.com/opencart/opencart/issues/8836](https://github.com/opencart/opencart/issues/8836)
> fixed mail counter issue

- upload/catalog/controller/event/activity.php
fixed [https://github.com/opencart/opencart/issues/8715](https://github.com/opencart/opencart/issues/8715)
> fixed register address issue

- upload/catalog/controller/account/address.php
Code Error: on customer address on putting random id in the URL 
>> Resolved issue
> Resolved issue #8665

- upload/admin/model/localisation/currency.php
fixed [https://github.com/opencart/opencart/issues/8866](https://github.com/opencart/opencart/issues/8866)
> fixed currency refresh issue

- upload/admin/controller/common/reset.php
Line   admin/controller/common/reset.php
------ --------------------------------------------------------
62     Syntax error, unexpected ')', expecting ']' on line 62
67     Syntax error, unexpected ')', expecting ']' on line 67
> Fix syntax error reset.php #8787

- upload/admin/controller/catalog/product.php
Not an issue, just for consistency.
> Cast limit to int

- upload/catalog/view/template/product/thumb.twig
fa fa-star-o - doesn't exist anymore = far fa-star
https://fontawesome.com/icons/star?style=solid
https://fontawesome.com/icons/star?style=regular
> fa fa-star-o - doesn't exist anymore = far fa-star

- upload/admin/view/template/common/header.twig
datepicker is broken
https://i.imgur.com/zjrwpOJ.png
After adding styles:
https://i.imgur.com/w7mxKf6.png
> OC4 Add admin bootstrap-datetimepicker styles

- upload/extension/opencart/admin/view/template/dashboard/online_info.twig
> security token

- upload/admin/view/template/report/online.twig
- upload/extension/opencart/admin/view/template/dashboard/online_info.twig
I return it back and insert it where I wanted.
Also, this parameter needs to be added to:
extension/opencart/admin/language/en-gb/extension/analytics/google.php
extension/opencart/admin/language/en-gb/extension/captcha/google.php
extension/opencart/admin/language/en-gb/extension/feed/google_base.php
> Security user_token

- upload/admin/controller/marketplace/modification.php
fixed [https://github.com/opencart/opencart/issues/8971](https://github.com/opencart/opencart/issues/8971)
> fixed Backslash in OCMOD file path causes

- upload/catalog/controller/information/contact.php
fix errors when sending a request without filling data
> fix error request post

- upload/catalog/controller/startup/startup.php
add default customer group
fix [https://github.com/opencart/opencart/issues/6688](https://github.com/opencart/opencart/issues/6688)
> add default customer group

- upload/catalog/view/theme/default/template/product/review.twig
https://github.com/opencart/opencart/issues/7806
> Resolved the issue(https://github.com/opencart/opencart/issues/7806) 

- upload/admin/model/localisation/currency.php
fix [https://github.com/opencart/opencart/issues/9035](https://github.com/opencart/opencart/issues/9035)
> fixed currency issue

- upload/admin/language/en-gb/catalog/product.php
I didn't found where that 3 columns are used. Not seen in Product form or List.
> Removed unused language variable Product

- upload/catalog/controller/extension/module/pilibaba_button.php
- upload/catalog/language/en-gb/extension/module/divido_calculator.php
- upload/catalog/language/en-gb/extension/module/pilibaba_button.php
- upload/catalog/language/en-gb/extension/payment/divido.php
- upload/catalog/language/en-gb/extension/payment/eway.php
- upload/catalog/language/en-gb/extension/payment/firstdata_remote.php
- upload/catalog/language/en-gb/extension/payment/klarna_account.php
- upload/catalog/language/en-gb/extension/payment/klarna_checkout.php
- upload/catalog/language/en-gb/extension/payment/klarna_invoice.php
- upload/catalog/view/theme/default/template/extension/module/divido_calculator.twig
- upload/catalog/view/theme/default/template/extension/module/pilibaba_button.twig
- upload/catalog/view/theme/default/template/extension/payment/divido.twig
- upload/catalog/view/theme/default/template/extension/payment/divido_calculator.twig
- upload/catalog/view/theme/default/template/extension/payment/eway.twig
- upload/catalog/view/theme/default/template/extension/payment/eway_iframe.twig
- upload/catalog/view/theme/default/template/extension/payment/firstdata_remote.twig
- upload/catalog/view/theme/default/template/extension/payment/klarna_account.twig
- upload/catalog/view/theme/default/template/extension/payment/klarna_checkout_sidebar.twig
- upload/catalog/view/theme/default/template/extension/payment/klarna_invoice.twig
fixed catalog end as well
[https://github.com/opencart/opencart/issues/6706](https://github.com/opencart/opencart/issues/6706)
> fixed catalog hardcoded text

- upload/catalog/controller/api/login.php
fix [https://github.com/opencart/opencart/issues/7327](https://github.com/opencart/opencart/issues/7327)
> fixed api login undefined indexes issue

- upload/admin/view/javascript/summernote/opencart.js
SummerNote - fontsize (wrong parameter) #9066 -- Resolved this issue
> SummerNote - fontsize (wrong parameter) #9066 -- Resolved this issue

- upload/catalog/controller/event/translation.php
If translation contain HTML code, it will be not parsed.
> [Maintenance] Update translation.php

- upload/admin/language/en-gb/user/api.php
https://github.com/opencart/opencart/pull/9027 for 3.0.x.x_Maintenance.
> Typo in language api.php

- upload/catalog/model/extension/total/handling.php
fix [https://github.com/opencart/opencart/issues/7110](https://github.com/opencart/opencart/issues/7110)
> add validation for the handling fee only for physical products

- upload/catalog/view/theme/default/template/product/product.twig
fix [https://github.com/opencart/opencart/issues/7792](https://github.com/opencart/opencart/issues/7792)
> product tag issue fixed

- upload/admin/controller/common/filemanager.php
fix [https://github.com/opencart/opencart/issues/7850](https://github.com/opencart/opencart/issues/7850)
> add image size validation in filemanager

- upload/install/model/upgrade/1005.php
fix [https://github.com/opencart/opencart/issues/7849](https://github.com/opencart/opencart/issues/7849)
> fix upgrade oc_customer table issue

- upload/system/library/db/mysqli.php
fix [https://github.com/opencart/opencart/issues/9075](https://github.com/opencart/opencart/issues/9075)
> add mysql version 8 sql mode code

- upload/install/model/upgrade/1009.php
https://forum.opencart.com/viewtopic.php?f=199&t=219496
> [3.0.x.x_Maintenance] Fixed Api upgrade bug

- upload/admin/language/en-gb/en-gb.php
The search for these phrases did not return any results
> Removed unused language phrases

- upload/system/library/image.php
https://github.com/opencart/opencart/commit/42332f196a8164c892c70c5b0b53a824b5f544da
> [3.0.x.x] PHP 7.4 image warning fix

- upload/catalog/view/theme/default/template/extension/recurring/pp_express.twig
fix https://github.com/opencart/opencart/issues/9105
> added the missing twig file of paypal express recurring payments view

- upload/admin/controller/sale/order.php
- upload/admin/view/template/sale/order_invoice.twig
fixed https://github.com/opencart/opencart/issues/9122
> fixed the wrong invoice header

- upload/install/opencart.sql
https://github.com/opencart/opencart/issues/6074
> [3.0.x.x_Maintenance] Fixed return event

- upload/admin/controller/extension/module/klarna_checkout_module.php
- upload/admin/controller/sale/recurring.php
- upload/admin/view/template/extension/module/klarna_checkout_module.twig
- upload/admin/view/template/sale/recurring_list.twig
-- https://prnt.sc/xsjzlg (fixed)
-- https://prnt.sc/xsk5q7 (fixed)
-- https://prnt.sc/xskaev (fixed)
-- https://prnt.sc/xslmet (fixed)
> fixed the recurring order filters and klarna checkout status

- upload/catalog/controller/extension/module/banner.php
- upload/catalog/controller/extension/module/carousel.php
- upload/catalog/controller/extension/module/slideshow.php
We have added the minify js for banner, carousel and slideshow
https://github.com/opencart/opencart/issues/9377
> We have added the minify js for banner, carousel and slideshow

- upload/admin/controller/design/seo_url.php
- upload/admin/language/en-gb/design/seo_url.php
- upload/admin/model/design/seo_url.php
fixed the SEO query duplicate and keyword issue
> fixed the SEO query duplicate and keyword issue

- upload/admin/controller/marketplace/install.php
Resolved the language issue  https://github.com/opencart/opencart/issues/9247
> Resolved the language issue  https://github.com/opencart/opencart/issues/9247

- upload/catalog/controller/product/product.php
- upload/catalog/language/en-gb/product/product.php
https://github.com/opencart/opencart/issues/9417
> add product id validation on adding review

- upload/catalog/controller/extension/payment/pp_standard.php
- upload/catalog/view/theme/default/template/extension/payment/pp_standard.twig
https://github.com/opencart/opencart/issues/9463
> fixed the PayPal Payments Standard issue

- upload/catalog/controller/extension/payment/pp_standard.php
- upload/catalog/view/theme/default/template/extension/payment/pp_standard.twig
Fixed the issue https://github.com/opencart/opencart/issues/9463
> Fixed the issue https://github.com/opencart/opencart/issues/9463

- upload/install/opencart.sql
https://github.com/opencart/opencart/commit/7cbe14016e5a42526444a09dc5f314ce6fbeeb09 for 3.0.x.x_Maintenance.
> Update config_logo to match filename

- upload/catalog/controller/product/product.php
- upload/catalog/model/catalog/product.php
fix [https://github.com/opencart/opencart/issues/9363](https://github.com/opencart/opencart/issues/9363)
> fixed the product page URL issue

- upload/catalog/controller/extension/payment/pp_standard.php
https://github.com/opencart/opencart/issues/6353 for 3.0.x.x_Maintenance.
> Fix PayPal Standard when option name too long

- upload/install/language/en-gb/install/step_3.php
- upload/system/library/db/pdo.php
> rename mPdo ro Pdo

- upload/admin/controller/extension/extension/module.php
- upload/admin/language/en-gb/extension/extension/module.php
add validation for module code
> add validation for module code

- upload/catalog/controller/extension/total/shipping.php
https://github.com/opencart/opencart/issues/9465
> Fixed the shipping quote tax issue

- upload/admin/model/localisation/language.php
added missing syntax for SQL to execute correctly in the admin/model/localization/language.php
> missing syntax

- upload/admin/view/template/catalog/review_list.twig
> Remove review list space

- upload/admin/controller/common/header.php
- upload/catalog/view/theme/default/template/checkout/checkout.twig
> fixed checkout registration same billing/shipping address issue

- upload/admin/language/en-gb/common/security.php
Fixed a typo in security message in language file upload/admin/language/en-gb/common/security.php
> fixed typo in upload/admin/language/en-gb/common/security.php

- upload/admin/controller/customer/customer.php
- upload/admin/model/customer/customer.php
> fix affiliate typo

- upload/admin/language/en-gb/common/security.php
https://github.com/opencart/opencart/pull/9543 for 3.0.x.x_Maintenance
> Fix typo in language security

- upload/admin/index.php
Reverts opencart/opencart#9269
> Revert "[Maintenance v3.x] - Changed indent to 4 - admin/index.php file."

- upload/index.php
Reverts opencart/opencart#9266
> Revert "[Maintenance v3.x] - Changed to indent of 4 - index.php file."

- upload/catalog/controller/account/order.php
https://github.com/opencart/opencart/issues/7097 for 3.0.x.x_Maintenance.
> Fix file option on reorder

- upload/catalog/controller/extension/total/reward.php
Reward point validation, allow integer value only
> Reward point validation, allow integer value only

- upload/admin/controller/marketplace/modification.php
- upload/admin/view/javascript/common.js
the LOG line with the "FILE: " indication is written at beginning of each file processing, and also when a file is already in the modification array with a note saying 'sub modification'.
I think is useful when you have an error in the log.
> common.js popover product images fix AND modification.php log  FILE name in modification loop

- upload/admin/view/stylesheet/stylesheet.css
> add admin end RTL CSS

- upload/install/opencart.sql
Default session time
First installation fix
> Default session time

- upload/admin/model/user/user.php
- upload/catalog/model/account/customer.php
Fix for https://github.com/opencart/opencart/issues/10084
> Fixed multiple IP issue of login attempts

- composer.json
Due the latest changes, check correct php version (>= 8.0.0)
> Update correct php version

- upload/admin/view/template/sale/order_form.twig
Put {% endif %} on line 302 before <tbody> tag
> Fix for issue #10216

- upload/catalog/language/en-gb/checkout/checkout.php
The same text translation may be available in other language files as well, but it is missing here.
> added missing word translation

- upload/admin/controller/customer/customer.php
https://github.com/opencart/opencart/blob/master/upload/admin/controller/marketing/affiliate.php#L366
> [3.0.x.x] Autogenerate tracking code when add a customer from admin

- upload/admin/model/tool/upload.php
https://github.com/opencart/opencart/pull/7951 for 3.0.x.x_Maintenance.
> Fix upload date filter

- upload/admin/view/javascript/common.js
Autocomplete should hide dropdown after selection
> OC4 - fix autocomplete

- upload/catalog/model/catalog/product.php
> Null value should not be rounded.

- upload/system/library/mail/mail.php
PHP 8 mail() requires all headers to end CRLF.
> Fix mail line endings for PHP 8

- upload/admin/model/extension/payment/firstdata.php
- upload/admin/model/extension/payment/globalpay.php
- upload/admin/model/extension/payment/globalpay_remote.php
- upload/admin/model/extension/payment/realex.php
- upload/admin/model/extension/payment/realex_remote.php
- upload/catalog/controller/extension/credit_card/sagepay_direct.php
- upload/catalog/controller/extension/credit_card/sagepay_server.php
- upload/catalog/controller/extension/payment/authorizenet_aim.php
- upload/catalog/controller/extension/payment/bluepay_redirect.php
- upload/catalog/controller/extension/payment/cardinity.php
- upload/catalog/controller/extension/payment/eway.php
- upload/catalog/controller/extension/payment/firstdata_remote.php
- upload/catalog/controller/extension/payment/globalpay.php
- upload/catalog/controller/extension/payment/globalpay_remote.php
- upload/catalog/controller/extension/payment/perpetual_payments.php
- upload/catalog/controller/extension/payment/pp_payflow.php
- upload/catalog/controller/extension/payment/pp_pro.php
- upload/catalog/controller/extension/payment/realex.php
- upload/catalog/controller/extension/payment/realex_remote.php
- upload/catalog/controller/extension/payment/sagepay_direct.php
- upload/catalog/controller/extension/payment/sagepay_server.php
- upload/catalog/controller/extension/payment/sagepay_us.php
- upload/catalog/controller/extension/payment/securetrading_ws.php
- upload/catalog/controller/extension/payment/web_payment_software.php
- upload/catalog/model/extension/payment/cardconnect.php
- upload/catalog/model/extension/payment/globalpay_remote.php
- upload/catalog/model/extension/payment/realex_remote.php
- upload/catalog/model/extension/payment/sagepay_direct.php
- upload/catalog/model/extension/payment/sagepay_server.php
vendor\braintree would also need updating in someway.
> Don't use strftime as deprecated in PHP 8.1

- upload/system/library/session/db.php
For https://github.com/opencart/opencart/issues/10403 and to match file adaptor.
> Change session read return type to array

- upload/catalog/view/theme/default/template/extension/payment/paypal.twig
This TWIG file's coding is terrible.
> [Maintenance] - Removed console.log entry - catalog/view/theme/default/template/extension/payment/paypal.twig file

- upload/admin/controller/startup/error.php
- upload/catalog/controller/startup/error.php
- upload/catalog/model/extension/payment/amazon_login_pay.php
- upload/install/cli_install.php
- upload/system/framework.php
- upload/system/library/googleshopping/googleshopping.php
error_reporting() no longer returns 0 when suppressed with @.
> Fix error handler for PHP 8

- upload/system/library/googleshopping/googleshopping.php
For https://github.com/opencart/opencart/issues/10358.
> Fix passed by reference warning in PHP 8

- upload/install/view/template/install/step_4.twig
Also added a note for product quality sold online regarding dangerous goods in order to inform store owners prior to add any products to their stores.
> [Master] - Made various changes - install/view/template/install/step_4.twig file

- upload/install/view/template/install/step_4.twig
Fix [issue #10878](https://github.com/opencart/opencart/issues/10878)
> Correct facebook icon

- upload/catalog/controller/account/login.php
fix error auto login customer by admin
> fix error auto login customer by admin

- upload/admin/view/javascript/jquery/jqvmap/jqvmap.css
something wrong with +/- sign with Open Sans font by issue #10499
> Fix world map zoom in/out button issue

- upload/catalog/model/setting/store.php
Removed code duplication.
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/setting.php#L7
> [Master] - Model getStorageByHostName didn't use a function argument.

- upload/catalog/view/stylesheet/stylesheet.scss
https://github.com/opencart/opencart/issues/10911
> Fixed hover color for header cart button

- upload/.htaccess.txt
Add:
+ More explaination
* IndexIgnore
* header nosniff
* header to prevent FLOC
About FLOC read more here:
https://www.theverge.com/2021/3/30/22358287/privacy-ads-google-chrome-floc-cookies-cookiepocalypse-finger-printing
https://web.dev/floc/
https://wicg.github.io/floc/
> Add IndexIngore, header nosniff, prevent FLOC

- upload/admin/view/stylesheet/stylesheet.css
> OC4 straighten .row.mb-3 + .row.mb-3 border

- upload/install/opencart.sql
https://github.com/opencart/opencart/pull/10407 for master branch.
> Fix default report settings

- upload/install/view/template/install/step_4.twig
This commit may need to be merged as well if {{ text_sale_info }} is to be considered: https://github.com/opencart/opencart/pull/10844 .
> Removed trailing space - install/view/template/install/step_4.twig file

- upload/extension/opencart/catalog/controller/module/banner.php
https://github.com/opencart/opencart/issues/10950
> status template

- upload/admin/view/template/localisation/tax_class_list.twig
for issue [#10948](https://github.com/opencart/opencart/issues/10948) is raised by atomicsp
> Fix delete tax class

- upload/admin/controller/sale/returns.php
https://github.com/opencart/opencart/issues/10969
> return to returns

- upload/extension/opencart/catalog/controller/module/featured.php
https://github.com/opencart/opencart/issues/10960
> Undefined variable $products

- upload/admin/view/template/catalog/filter_list.twig
https://github.com/opencart/opencart/issues/10980
> Fixed deleting filter

- upload/catalog/view/template/checkout/register.twig
Fixed missing id for the terms checkbox in register.twig
> Added id and for statement to click on the label to check the terms

- upload/catalog/language/en-gb/tool/upload.php
https://github.com/opencart/opencart/issues/10990
> Typo upload.php language file

- upload/admin/view/template/marketplace/installer.twig
=( https://github.com/opencart/opencart/issues/11026
> accept="application/zip,.zip" for  Safari

- upload/admin/view/template/marketplace/installer.twig
Reverts opencart/opencart#11040
> Revert "accept="application/zip,.zip" for  Safari"

- upload/admin/controller/sale/order.php
https://github.com/opencart/opencart/issues/11036
> Fixed $data['icons'] URL

- upload/admin/controller/setting/setting.php
https://github.com/opencart/opencart/issues/11155
> Fixed Affiliate status

- upload/catalog/view/template/account/affiliate.twig
https://github.com/opencart/opencart/issues/11255
> Fixed Affiliate custom fields cannot be saved

- upload/admin/controller/sale/order.php
> jquery file match

- upload/system/helper/db_schema.php
- https://github.com/opencart/opencart/blob/master/upload/catalog/model/account/subscription.php#L5
- https://github.com/opencart/opencart/blob/master/upload/catalog/model/account/subscription.php#L47
> Added missing fields - system/helper/db_schema.php file

- upload/system/helper/db_schema.php
https://github.com/opencart/opencart/blob/master/upload/catalog/model/account/subscription.php#L29
> Added reference field in subscriptions

- upload/admin/controller/setting/setting.php
- upload/admin/controller/startup/notification.php
- upload/admin/controller/startup/session.php
- upload/admin/language/en-gb/setting/setting.php
- upload/admin/view/template/setting/setting.twig
- upload/catalog/controller/common/cookie.php
- upload/catalog/controller/startup/marketing.php
- upload/catalog/controller/startup/session.php
- upload/install/opencart.sql
Added ability to change session samesite cookie from admin panel server settings
> Ability to change session samesite cookie

- upload/system/library/session/redis.php
A faster way to store sessions. Since Redis uses in-memory key-value storage with optional persistence to disk, the read and write functions are significantly faster. [https://redis.com/solutions/use-cases/session-management/]
> Redis Session Adaptor

- upload/admin/controller/tool/backup.php
- upload/admin/language/en-gb/tool/backup.php
- upload/admin/view/template/tool/backup.twig
- upload/system/helper/general.php
Fix upload file size check for tool/backup, including adding the missing **error_upload_size** language string.
> Fix Upload file size check for System > Maintenance > Backup / Restore

- .gitignore
- upload/admin/controller/common/security.php
- **Remove installation folder:**
- wrong trim in glob -> fixed
- **Move storage folder:**
- Wrong trim in glob -> fixed
- Source storage folder was not deleted -> fixed
- **Rename admin folder:**
- Wrong trim in glob (`function admin()`, `function delete()`) -> fixed
- Error while building redirection url -> fixed
> [OC 4 master] Fix post install security checks

- upload/admin/view/template/catalog/category_form.twig
- upload/admin/view/template/catalog/information_form.twig
- upload/admin/view/template/catalog/product_form.twig
- upload/admin/view/template/catalog/review_form.twig
- upload/admin/view/template/catalog/subscription_plan_form.twig
- upload/admin/view/template/common/developer.twig
- upload/admin/view/template/customer/custom_field_form.twig
- upload/admin/view/template/customer/customer_form.twig
- upload/admin/view/template/customer/customer_group_form.twig
- upload/admin/view/template/design/banner_form.twig
- upload/admin/view/template/localisation/country_form.twig
- upload/admin/view/template/localisation/currency_form.twig
- upload/admin/view/template/localisation/language_form.twig
- upload/admin/view/template/localisation/zone_form.twig
- upload/admin/view/template/marketing/affiliate_form.twig
- upload/admin/view/template/marketing/coupon_form.twig
- upload/admin/view/template/sale/order_info.twig
- upload/admin/view/template/sale/voucher_form.twig
- upload/admin/view/template/setting/store_form.twig
- upload/admin/view/template/user/api_form.twig
- upload/admin/view/template/user/user_form.twig
Completion of the promised work in https://github.com/opencart/opencart/pull/11431
Description: Handle form 0/1 checkboxes, namely when the value is toggled between 0 and 1 with a checkbox, and the checkbox is unchecked, in the post is missing an entry with value 0.
> [OC 4.0 Master] Admin Checkboxes Unchecked Values

- upload/admin/controller/tool/upgrade.php
- upload/install/controller/upgrade/upgrade_2.php
fix for OpenCart update failure
> fix: upgrade dirname failure fix

- buildspec.yml
- composer.json
- template-configuration.json
> build yml file

- upload/admin/view/template/marketplace/installer.twig
Issue was loading indicator only work for first request and after that it get reset even next request was pending
> Fixed loading button if more than one request

- upload/admin/view/stylesheet/bootstrap.css
- upload/admin/view/stylesheet/bootstrap.scss
- upload/catalog/view/stylesheet/bootstrap.css
- upload/catalog/view/stylesheet/bootstrap.scss
- upload/catalog/view/stylesheet/stylesheet.css
- upload/catalog/view/stylesheet/stylesheet.scss
- upload/catalog/view/template/common/cart.twig
Admin - removed unused body background
Frontend - fixed gigantic font-size for inputs and buttons
Frontend - fix cart button size
> Bootstrap minor fixes

- upload/admin/controller/marketplace/extension.php
Exclude 'promotion' from extensions list types.
> 3.0.x.x maintenance

- upload/admin/controller/mail/subscription.php
These methods might still be under development. I am not sure.
> Sentence correction. Methods unfinished - admin/controller/mail/subscription.php file

- upload/system/library/language.php
Method clear, is it really about void or array? Since an array is being emptied.
> Added comment text on methods - system/library/language.php file

- upload/admin/controller/user/user_permission.php
Added `startup/application` in the list of _'Routes to ignore'_ in **user_permission.php**
> Added "startup/authorize" in user_permission.php

- upload/extension/opencart/admin/controller/module/banner.php
- upload/extension/opencart/admin/controller/module/bestseller.php
- upload/extension/opencart/admin/controller/module/featured.php
- upload/extension/opencart/admin/controller/module/html.php
- upload/extension/opencart/admin/controller/module/latest.php
- upload/extension/opencart/admin/controller/module/special.php
- upload/extension/opencart/admin/view/template/module/banner.twig
- upload/extension/opencart/admin/view/template/module/bestseller.twig
- upload/extension/opencart/admin/view/template/module/featured.twig
- upload/extension/opencart/admin/view/template/module/html.twig
- upload/extension/opencart/admin/view/template/module/latest.twig
- upload/extension/opencart/admin/view/template/module/special.twig
Prevent to Save multiple times form data when press save button to first form save in **Banner, Bestsellers, Featured, HTML Content, Latest & Special** modules.
When we press 5x times save button in add form its save same form data 5x times.
> Prevent to Save multiple times form data in Banner, Bestsellers, Featured, HTML Content, Latest & Special modules.

- upload/catalog/controller/account/payment_method.php
addPaymentMethod also seem to lead nowhere from catalog/model/account/payment_method.php file. No controllers makes the call for it.
> Added int cast on customer_payment_id - catalog/controller/account/payment_method.php file

- upload/admin/model/sale/subscription.php
> Added the mandatory fields in the parameters - admin/model/sale/subscription.php file

- upload/admin/model/sale/subscription.php
Method does not originally exist in sale/subscription model.
> Added editSubscriptionPlan method - admin/model/sale/subscription.php file

- upload/admin/controller/sale/subscription.php
> Completing addTransaction() from sale/subscription - admin/controller/sale/subscription.php file

- upload/admin/view/javascript/jquery/jqvmap/jquery.vmap.js
See https://github.com/10bestdesign/jqvmap/issues/166
> [Maintainance] Fix onRegionClick

- upload/admin/controller/sale/subscription.php
This validation would also be a good addition in the cron/subscription as a subscription status total from the catalog. However, in the addTransaction() method, this would indeed be needed since, not only it doesn't validate anywhere else in the sale/subscription controller but also that the config set can be manipulated from the browser as opposed to the database.
> Added subscription status lookup in addTransaction - admin/controller/sale/subscription.php file

- upload/system/library/cart/cart.php
Issued from: https://github.com/opencart/opencart-3/issues/145 .
> Added trial_remaining since it's a mandatory field - system/library/cart/cart.php file

- upload/catalog/view/template/account/subscription_info.twig
Related with this commit: https://github.com/opencart/opencart/pull/11904 .
> Renamed recurring_description to description - catalog/view/template/account/subscription_info.twig file

- upload/admin/controller/sale/subscription.php
Need to replace the comment text from the old recurring version into the new subscription.
> subscription status ID comment text correction - admin/controller/sale/subscription.php file

- upload/catalog/model/account/subscription.php
For: https://github.com/opencart/opencart/pull/11927 and cron/subscription controllers
> Added filters in account/subscription model - catalog/model/account/subscription.php file

- upload/catalog/controller/cron/subscription.php
The addTransaction() method also needed to match the same parameters as the account/subscription/addTransaction model
> Modified active transaction status for new order - catalog/controller/cron/subscription.php file

- upload/catalog/view/template/mail/subscription.twig
A bit of work might still be needed. For now, could be as a suggestion in case something else might be needed.
> Suggesting this change for TWIG file - catalog/view/template/mail/subscription.twig file

- upload/catalog/controller/mail/subscription.php
I wasn't satisfied enough of the previous one. You were right though, we don't need the ```abs``` function to achieve this.
> Another improvement of cycle and frequency - catalog/controller/mail/subscription.php file

- upload/admin/language/en-gb/catalog/subscription_plan.php
because the trial duration start with 1 and the normal duration start with 0
> Seperate help disription for trial language file

- upload/catalog/controller/startup/marketing.php
SameSite is used. I believe config session path should go there.
> Replaced '/' with config session path - catalog/controller/startup/marketing.php file

- upload/system/library/mail.php
- upload/system/library/mail/mail.php
- upload/system/library/mail/smtp.php
Fixes for the files:
system/library/mail.php
system/library/mail/mail.php
system/library/mail/smtp.php
> mail classes fixes for PHP 8.2

- upload/admin/model/tool/image.php
- upload/catalog/model/tool/image.php
Add support for images of type *.webp
In addition return proper path for images/files not resized for any reason.
It is like in [master] branch.
> [3.0.x.x_Maintenance] Add support for images of type *.webp

- upload/system/helper/db_schema.php
As per: https://github.com/opencart/opencart/issues/12064 .
> Changed varchar(11) to int(11) - system/helper/db_schema.php file

- upload/admin/view/template/sale/order_form.twig
Fixes an issue with doubly escaped ampersands or other special characters in order editor.
> Bugfix order editor for special characters in form fields

- upload/admin/controller/sale/order.php
Also replaced 'order_id' with 'filter_order_id' since the model uses 'filter_order_id' and 'filter_order_product_id', not: 'order_product_id' with filtering.
> Replaced | with . - admin/controller/sale/order.php file

- upload/system/library/session/file.php
https://github.com/opencart/opencart/pull/6093 for 3.0.x.x_Maintenance.
> Fix double slash in session path

- upload/admin/controller/tool/backup.php
https://github.com/opencart/opencart/pull/12296 for master.
> Fix backup with NULL values

- upload/admin/view/template/marketplace/marketplace_info.twig
https://github.com/opencart/opencart/pull/12264
> Display Compatibility info for Extension in Marketplace

- upload/catalog/controller/api/sale/payment_address.php
- upload/catalog/controller/api/sale/shipping_address.php
City length check must be 128 characters.
> Update city length check

- upload/admin/view/template/design/banner_form.twig
modified the input tag
Earlier : <input type="hidden" name="banner_image[{{ language.language_id }}][{{ image_row }}][image]" value="{{ banner_image.image }}" id="input-image-{{ language.language_id }}-{{ image_row }}"/>
To: <input type="hidden" name="banner_image[{{ language.language_id }}][{{ image_row }}][image]" value="{{ banner_image.image }}" id="input-image-{{ language.language_id }}-{{ image_row }}-image"/>
> fixed #12231 issue

- upload/catalog/view/theme/default/template/product/product.twig
No more addthis, see Notice of Termination of AddThis Services at https://www.addthis.com/
> no more addthis

- upload/admin/view/javascript/summernote/opencart.js
- upload/catalog/view/theme/default/stylesheet/stylesheet.css
Match summernote editor default fontsize with the ones on the corresponding frontend pages
> matching default fontsizes

- upload/system/library/mail/smtp.php
https://github.com/opencart/opencart/issues/12380 for 3.0.x.x_Maintenance.
> Fix SMTP line lengths

- upload/admin/language/en-gb/design/theme.php
> Update Twig docs link

- upload/admin/view/template/sale/order_invoice.twig
to get a reliable print result
> remove  media="screen" from order_invoice.twig

- upload/admin/view/template/sale/order_shipping.twig
to get a reliable print result
> remove  media="screen" from order_shipping.twig

- upload/admin/view/template/customer/customer.twig
> Change page location on admin customer filter

- upload/admin/view/template/sale/order.twig
> Change page location on admin order filter

- upload/catalog/model/tool/image.php
code to action this param in system/image is already there, just not being used
> allow pass through $default to system resize

- upload/admin/view/template/customer/customer_approval.twig
> Change page location on admin customer_approval filter

- upload/admin/view/template/design/seo_url.twig
> Change page location on admin seo_url filter

- upload/admin/view/template/customer/gdpr.twig
> Change page location on admin gdpr filter

- upload/admin/view/template/sale/returns.twig
> Change page location on admin returns filter

- upload/admin/view/template/localisation/zone.twig
> Change page location on admin zone filter

- upload/admin/view/template/localisation/country.twig
> Change page location on admin country filter

- upload/admin/view/template/marketing/affiliate.twig
> Change page location on admin affiliate filter

- upload/admin/view/template/marketing/marketing.twig
> Change page location on admin marketing filter

- upload/admin/view/template/sale/subscription.twig
> Change page location on admin subscription filter

- upload/admin/model/catalog/product.php
https://github.com/opencart/opencart/issues/12329
> copyProduct support for variant/override fields

- upload/catalog/model/catalog/product.php
> Removed empty space in catalog/product model

- upload/admin/controller/catalog/download.php
Added a point to the filename check so that it is possible to upload files with an extension (e.g. name.txt)
> Update catalog download.php - Added . to filename check

- upload/catalog/view/theme/default/template/checkout/checkout.twig
See: https://forum.opencart.com/viewtopic.php?t=231969
> Fixed error displaying guest shipping

- upload/admin/view/javascript/codemirror/lib/codemirror.css
- upload/admin/view/javascript/codemirror/lib/codemirror.js
- upload/admin/view/javascript/codemirror/mode/css/css.js
- upload/admin/view/javascript/codemirror/mode/htmlmixed/htmlmixed.js
- upload/admin/view/javascript/codemirror/mode/javascript/javascript.js
- upload/admin/view/javascript/codemirror/mode/php/php.js
- upload/admin/view/javascript/codemirror/mode/sass/sass.js
- upload/admin/view/javascript/codemirror/mode/twig/twig.js
- upload/admin/view/javascript/codemirror/mode/xml/xml.js
- upload/admin/view/javascript/codemirror/theme/abbott.css
- upload/admin/view/javascript/codemirror/theme/ayu-dark.css
- upload/admin/view/javascript/codemirror/theme/ayu-mirage.css
- upload/admin/view/javascript/codemirror/theme/base16-dark.css
- upload/admin/view/javascript/codemirror/theme/bespin.css
- upload/admin/view/javascript/codemirror/theme/gruvbox-dark.css
- upload/admin/view/javascript/codemirror/theme/juejin.css
- upload/admin/view/javascript/codemirror/theme/material-ocean.css
- upload/admin/view/javascript/codemirror/theme/material-palenight.css
- upload/admin/view/javascript/codemirror/theme/material.css
- upload/admin/view/javascript/codemirror/theme/oceanic-next.css
- upload/admin/view/javascript/codemirror/theme/solarized.css
- upload/admin/view/template/design/theme.twig
https://codemirror.net/5/doc/releases.html
> Codemirror 5.65.15 update

- upload/cron.php
- upload/install/cli_cloud.php
- upload/install/cli_install.php
- upload/install/controller/install/step_3.php
- upload/install/controller/startup/database.php
- upload/install/controller/upgrade/upgrade_1.php
- upload/install/language/en-gb/install/step_3.php
- upload/install/model/install/install.php
- upload/install/view/template/install/step_3.twig
- upload/system/config/admin.php
- upload/system/config/catalog.php
- upload/system/framework.php
- upload/system/helper/db_schema.php
- upload/system/library/db.php
- upload/system/library/db/mysqli.php
- upload/system/library/db/pdo.php
- upload/system/library/db/pgsql.php
#12757 feature
An Advanced panel was added to step-3 UI while installing. The advanced panel is visible while using the MySQLi driver.
> #12757 mysql ssl connection support

- upload/install/cli_cloud.php
- upload/install/cli_install.php
- upload/install/controller/install/step_3.php
- upload/install/language/en-gb/install/step_3.php
- upload/system/config/catalog.php
- upload/system/library/db/mysqli.php
- Else statement fix
- Corrected certificate language text definition
> More code alignments

- upload/admin/model/catalog/product.php
- upload/index.php
[Fixed Model filter product.php](https://github.com/opencart/opencart/pull/12789/commits/8564a6eaa17970e7474fdb59d7729dd805695167)
> Update index.php and fixed Model Filter

- upload/admin/controller/marketing/contact.php
For https://forum.opencart.com/viewtopic.php?t=232144.
> Fix marketing message counter

- upload/.htaccess.txt
RewriteBase comment didn't make sense. register_globals and magic_quotes_gpc were removed in PHP 5.4. php_admin_value does not work in .htaccess. Added webp to RewriteCond.
> Corrections to .htaccess.txt

- upload/install/controller/startup/install.php
Introduced in 4.0.0.0: https://github.com/opencart/opencart/commit/853c76d8a573756d6a9a96f75a5e9638d178d65d
> Remove unused parameter from install.php

- upload/admin/model/catalog/attribute_group.php
Reverts opencart/opencart#12924
> Revert "Update attribute_group.php"

- upload/system/engine/registry.php
Correct various types that where not kept in sync when updated in https://github.com/opencart/opencart/commit/0dddbec63e8f9309e22a929219e730fb47bddfff
> Correct registry type hints

- upload/admin/view/template/catalog/product_form.twig
Needs to be in the right screen position
> attribute automcomplete fix

- upload/admin/controller/customer/custom_field.php
Fixes https://github.com/opencart/opencart/issues/12978
> Fix deprication error in custom_field.php

- upload/catalog/controller/account/wishlist.php
> fix: Undefined variable '$stock' bug fix

- upload/catalog/controller/account/login.php
- upload/catalog/controller/affiliate/login.php
- upload/catalog/controller/common/currency.php
- upload/catalog/controller/common/language.php
- upload/catalog/controller/extension/total/reward.php
> Fix redirect protection

- upload/catalog/model/catalog/product.php
It is necessary to add join with the table `product_to_store` in the method getTotalProducts()
> Method getTotalProducts() does not count correctly in a multi-store

- upload/admin/language/en-gb/setting/setting.php
> Update setting.php - remove $_['error_encryption']

- upload/admin/controller/mail/subscription.php
This was done using php-cs-fixer's indentation_type rule. Once all oustanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
> Fix incorrect indentation in mail subscription

- upload/admin/controller/tool/notification.php
> Update notification.php - time information

- upload/system/helper/db_schema.php
> Update db_schema.php - article index entries with _id

- upload/admin/controller/marketplace/installer.php
- upload/admin/model/setting/modification.php
> install modification description 

- upload/admin/view/template/catalog/product_form.twig
- upload/admin/view/template/catalog/product_list.twig
> Testing change with multiple files by merging commits

- upload/admin/view/template/catalog/category_form.twig
- upload/admin/view/template/catalog/option_form.twig
- upload/admin/view/template/catalog/product_form.twig
- upload/admin/view/template/cms/article_form.twig
- upload/admin/view/template/cms/comment_list.twig
- upload/admin/view/template/cms/topic_form.twig
- upload/admin/view/template/common/developer.twig
- upload/admin/view/template/customer/customer_list.twig
- upload/admin/view/template/design/banner_form.twig
- upload/admin/view/template/design/layout_form.twig
- upload/admin/view/template/extension/marketplace.twig
- upload/admin/view/template/mail/gdpr_deny.twig
- upload/admin/view/template/marketplace/marketplace_extension.twig
- upload/admin/view/template/marketplace/promotion.twig
- upload/admin/view/template/sale/order_info.twig
- upload/admin/view/template/sale/order_invoice.twig
- upload/admin/view/template/sale/subscription_info.twig
- upload/admin/view/template/tool/backup_history.twig
- upload/admin/view/template/tool/notification_list.twig
- upload/catalog/view/template/account/order_info.twig
- upload/catalog/view/template/account/subscription_list.twig
- upload/catalog/view/template/mail/gdpr_delete.twig
- upload/catalog/view/template/mail/order_invoice.twig
- upload/catalog/view/template/mail/subscription.twig
- upload/catalog/view/template/product/review_list.twig
There also seem to be something wrong with the original intend from file: admin/view/template/marketplace/promotion.twig . This file is synched from the MB. When looking at the code, we can notice the closing DIVs are over-spaced at the end of the file. This file might need a refresh to match the indents and tabs.
> Completed TD alignment on catalog and more in admin

- upload/admin/controller/common/header.php
- upload/catalog/controller/checkout/checkout.php
This was done using php-cs-fixer's control_structure_continuation_position rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
> Correct control structure continuation position

- upload/admin/controller/setting/setting.php
- upload/admin/controller/tool/backup.php
- upload/extension/opencart/admin/controller/module/bestseller.php
- upload/extension/opencart/admin/controller/module/featured.php
- upload/extension/opencart/admin/controller/module/latest.php
- upload/extension/opencart/admin/controller/module/special.php
This was done using php-cs-fixer's binary_operator_spaces rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
> Correct spaces around assigments

- upload/system/library/db/pdo.php
This was done using php-cs-fixer's array_syntax rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
> Modernize arrays

- upload/catalog/model/setting/startup.php
- upload/extension/opencart/catalog/model/shipping/flat.php
- upload/extension/opencart/catalog/model/shipping/free.php
- upload/extension/opencart/catalog/model/shipping/item.php
- upload/extension/opencart/catalog/model/shipping/pickup.php
- upload/system/library/cache/mem.php
- upload/system/library/cache/memcached.php
This was done using php-cs-fixer's visibility_required rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
> Add missing symbol visibility

- upload/system/engine/event.php
- upload/system/engine/registry.php
- upload/system/library/cart/customer.php
- upload/system/library/cart/user.php
- upload/system/library/db/pdo.php
- upload/system/library/db/pgsql.php
- upload/system/library/language.php
- upload/system/library/log.php
- upload/system/library/mail/smtp.php
- upload/system/library/session.php
- upload/system/library/session/db.php
- upload/system/library/session/file.php
- upload/system/library/session/redis.php
> Remove trailing whitespace from empty lines in system

- .github/workflows/Lint.yml
- .gitignore
- .php-cs-fixer.php
- upload/admin/controller/common/developer.php
- upload/admin/controller/mail/transaction.php
- upload/admin/controller/marketplace/api.php
- upload/catalog/controller/event/activity.php
- upload/catalog/controller/event/debug.php
- upload/catalog/model/cms/article.php
- upload/extension/opencart/admin/controller/report/subscription.php
- upload/extension/opencart/admin/model/report/subscription.php
- upload/system/engine/autoloader.php
- upload/system/engine/registry.php
- upload/system/library/cache.php
- upload/system/library/cache/apcu.php
- upload/system/library/cache/redis.php
- upload/system/library/db/pdo.php
- upload/system/library/db/pgsql.php
- upload/system/library/document.php
- upload/system/library/session/redis.php
- upload/system/library/url.php
This adds a php-cs-fixer rule set, checks that PRs complies with the configured rules and corrects any left over violations in the code base (mostly left out because of conflicts).
The tool can also correct any violations, developers can have it do so by simply running `php system/storage/vendor/bin/php-cs-fixer fix`, or even better there IDE might support integration with the tool so that it happens when they save there code changes.
> Check that PR has correct code style

- .php-cs-fixer.php
- upload/extension/opencart/catalog/controller/captcha/basic.php
- upload/system/library/cache/file.php
- upload/system/library/session/db.php
- upload/system/library/session/file.php
See notes on https://www.php.net/manual/en/function.rand.php
> Use modern random number generator

- upload/catalog/model/cms/topic.php
> [Master] topic.php

- .php-cs-fixer.php
- upload/system/engine/action.php
- upload/system/engine/loader.php
- upload/system/engine/proxy.php
- upload/system/library/image.php
This should be both faster and allow better error detection by code analyzers.
> Use native function calls

- upload/catalog/controller/cms/comment.php
Check if approval is required, get then correct text
> [MASTER] comment.php

- upload/admin/controller/user/user.php
> Update user.php - New version

- upload/admin/view/template/user/user.twig
> Update user.twig - New Version

- upload/admin/view/template/user/user_list.twig
Added sort entries and new columns
> Update user_list.twig - New version

- .github/workflows/Lint.yml
- .php-cs-fixer.php
https://github.com/opencart/opencart/pull/13385/commits/5deb6ed7a9606287b03e4734c44c9f6c2b9bd9b3
> [3.0.x.x] .php-cs-fixer.php

- upload/system/library/session/db.php
Reverts opencart/opencart#13390
> Revert "Fix for timezone change breaking session expiration"

- composer.json
- phpstan.neon
- tools/phpstan/LoadedProperty.php
- tools/phpstan/RegistryPropertyReflectionExtension.php
Enough issues have been solved that the PHPStan level can now be increased from 0 to 1
> Increase PHPStan level to 1

- upload/system/library/mail/mail.php
The version check was wrong, see comment below.
> Fix sending mail on PHP 7.4

- upload/catalog/controller/common/column_left.php
- upload/catalog/controller/common/column_right.php
- upload/catalog/controller/common/content_bottom.php
- upload/catalog/controller/common/content_top.php
Looks like this was not properly migrated in https://github.com/opencart/opencart/commit/038b962e8629577154bca2702f8d4d42c51029dc
> Fix loading article layout

- upload/catalog/model/checkout/order.php
Validate that the function is callable, and also add support for extensions that uses actual methods rather then callbacks in variables.
> Assert that model methods are callable

- upload/admin/controller/customer/customer.php
- upload/admin/controller/extension/language.php
- upload/admin/controller/marketplace/modification.php
Issues introduced in bdc79c4db07f170c1a41add4566cfe2c0f529f20, 94ec60ff74a425fed4ba5a906bc11ca29032c47d, and 0da669409629a3aca01aefe40c49765b34eb9491
> Fix calls to wrong methods on models

- upload/system/library/cart/tax.php
Introduced in https://github.com/opencart/opencart/commit/977710c5ba995d49261f20273e971482c584970b
> Correct getRateName() return type

- upload/system/library/cart/customer.php
Introduced in https://github.com/opencart/opencart/commit/5e7c0036ef81759ab821932feaddaf15826d2eb4
> Reset customer properties with correct types

- upload/system/library/cart/currency.php
Introduced in 977710c5ba995d49261f20273e971482c584970b
> Correct return type for getDecimalPlace()

- upload/system/engine/factory.php
Introduced here eaa91609e10158802a5d67ed369d72aced6f16fb
> Fix emitting error in Factory

- upload/admin/controller/customer/customer.php
- upload/admin/model/sale/subscription.php
Issue introduced in https://github.com/opencart/opencart/commit/8a00dffe8334133698dc863fe944bcf23735f7f4
> Implement missing function for deleting subscriptions

- upload/admin/controller/extension/language.php
Broke here https://github.com/opencart/opencart/commit/28f164f67013321743dceba4424347c18af52e6d
> Fix bad function call

- upload/admin/controller/customer/customer.php
- upload/admin/model/user/user.php
Broken in https://github.com/opencart/opencart/commit/ecaf35f7d43a55329308eb94038cad8fd04b6c1f
> Fix deleteAuthorize()

- upload/admin/model/extension/payment/sagepay_direct.php
>  [3.0.x.x]Undefined variable: $ - sagepay_direct.php

- upload/admin/model/extension/payment/sagepay_server.php
> [3.0.x.x] Undefined variable: $i - sagepay_server.php

- upload/catalog/view/javascript/paypal/paypal.js
https://forum.opencart.com/viewtopic.php?t=232822#p865518
> [3.0.x.x] Added Paypal language fix

- upload/catalog/controller/startup/router.php
> [3.0.x.x] Undefined variable: $data -  router controller

- upload/system/config/paypal.php
> [3.0.x.x] Removed duplicated array -  paypal.php

- upload/system/library/db/pgsql.php
https://github.com/opencart/opencart/pull/13449/files
> [3.0.x.x] Updated pgsql.php

- upload/system/engine/factory.php
This was incorrectly reverted in https://github.com/opencart/opencart/commit/137792c69dab5365828a971439e41b1c7747b70a
> Correct return types in Factory

- upload/system/library/db/pgsql.php
https://www.php.net/manual/en/function.pg-query.php
> Fix usage of PostgreSQL with PHP 8.1+

- upload/system/engine/router.php
> [3.0.x.x] Update router.php

- upload/admin/model/extension/payment/divido.php
> [3.0.x.x] Update divido.php

- upload/admin/controller/startup/startup.php
I think is the correct solution
> [3.0.x.x] Updated startup.php

- upload/admin/controller/event/language.php
- upload/system/config/admin.php
- upload/system/framework.php
Fix duplicate key in system/config/admin.php
Fix controller/admin/event/language.php missing template_code argument
> Fix duplicate key

- upload/catalog/controller/extension/recurring/pp_express.php
> [3.0.x.x] Update pp_express.php

- upload/admin/controller/extension/payment/squareup.php
https://github.com/opencart/opencart-3/blob/main/upload/admin/controller/extension/payment/squareup.php#L653
> [3.0.x.x] Update squareup.php

- upload/admin/controller/cms/comment.php
Partially reverts commit d8c97567b326790be2c894eaa2fbb10e3864c558
If this is still being worked on that's fine, but it would be nice if things where not left in a broken state in master since it affects everyone trying to test and work on things.
> Fix cms/comment.php

- upload/catalog/model/extension/payment/alipay.php
Method getSignContentUrlencode does not exist.
> 3.0.x.x bugfix alipay

- upload/admin/controller/extension/payment/opayo.php
Also use user_token from session.
> Add missing type cast for Opayo

- upload/system/library/cart/length.php
- upload/system/library/cart/weight.php
The key here is an `int` and not a `string`.
> Correct key type for length and weight library

- upload/admin/controller/marketing/contact.php
> Update contact.php - remove blank

- upload/catalog/controller/extension/payment/wechat_pay.php
Based on https://github.com/Wechat-Group/WxJava/issues/1088
This should fix the last of the issues found with wechat by phpstan at level 0
> [3.0.x.x] Fix WeChat XML response

- upload/admin/controller/extension/payment/securetrading_ws.php
https://github.com/opencart/opencart-3/commit/3fdd701fedad8b7636d498b64308232184ccf3f4#diff-0c711691d0c9b7dc8fbc05223c7b3e8d755ff42d46c8ce3df6dd93d2bf78d9f8
> [3.0.x.x]Update securetrading_ws.php

- upload/admin/controller/extension/payment/securetrading_pp.php
https://github.com/opencart/opencart-3/commit/3fdd701fedad8b7636d498b64308232184ccf3f4#diff-0c711691d0c9b7dc8fbc05223c7b3e8d755ff42d46c8ce3df6dd93d2bf78d9f8
> [3.0.x.x]Update securetrading_pp.php

- upload/admin/controller/localisation/location.php
Can't find a place where it is required on this place/form
> Update location.php - remove load model/store

- upload/admin/controller/extension/payment/opayo.php
- upload/admin/controller/localisation/geo_zone.php
- upload/admin/language/en-gb/extension/payment/opayo.php
- upload/admin/model/extension/payment/opayo.php
- upload/admin/model/localisation/geo_zone.php
- upload/admin/view/template/localisation/geo_zone_form.twig
- upload/catalog/model/extension/payment/opayo.php
Merging latest Opayo payment extension updates from Dreamvention, with additional bugfixes.
Fixed performance issues for editing geo zones in admin backend.
> Bugfixes for Opayo and Geo Zones

- phpstan.neon
- upload/admin/controller/extension/advertise/google.php
- upload/admin/controller/extension/module/pilibaba_button.php
- upload/admin/controller/extension/module/pp_braintree_button.php
- upload/admin/controller/extension/payment/klarna_invoice.php
- upload/admin/controller/extension/payment/securetrading_pp.php
- upload/admin/controller/extension/payment/securetrading_ws.php
- upload/admin/controller/extension/report/customer_activity.php
- upload/admin/controller/extension/report/customer_order.php
- upload/admin/controller/extension/report/customer_reward.php
- upload/admin/controller/extension/report/customer_search.php
- upload/admin/controller/extension/report/customer_transaction.php
- upload/admin/controller/extension/report/marketing.php
- upload/admin/controller/extension/report/product_purchased.php
- upload/admin/controller/extension/report/product_viewed.php
- upload/admin/controller/extension/report/sale_coupon.php
- upload/admin/controller/extension/report/sale_order.php
- upload/admin/controller/extension/report/sale_return.php
- upload/admin/controller/extension/report/sale_shipping.php
- upload/admin/controller/extension/report/sale_tax.php
- upload/admin/controller/marketplace/modification.php
- upload/admin/model/extension/payment/sagepay_direct.php
- upload/admin/model/extension/payment/sagepay_server.php
- upload/catalog/controller/extension/payment/g2apay.php
- upload/catalog/controller/mail/order.php
- upload/catalog/model/extension/payment/opayo.php
- upload/system/library/googleshopping/googleshopping.php
Updated phpstan.neon and various bugfixes as per phpstan level 1
> More bugfixes as per phpstan level 1

- upload/catalog/controller/extension/payment/cardinity.php
- upload/catalog/model/extension/payment/cardinity.php
Fixed cardinity payment extension to comply with phpstan level 1 checks.
> [3.0.x.x] More bugfixes as per phpstan level 1

- upload/admin/model/catalog/product.php
- upload/admin/model/cms/article.php
@danielkerr Don't know if you are still working on admin refactoring. 
But there are a few bugs which prevent editing products and articles.
> Fix admin refactoring bugs

- upload/catalog/controller/checkout/voucher.php
- upload/extension/opencart/admin/controller/payment/opayo.php
- upload/extension/opencart/catalog/controller/payment/opayo.php
- upload/extension/opencart/catalog/model/payment/opayo.php
third parameter expects a float and not a boolean
> Correct the type of input for Currency::format()

- upload/admin/controller/sale/order.php
If  no $order_info is provided fallback to the default currency settings
> Fix missing default order currency

- upload/catalog/view/javascript/common.js
- upload/catalog/view/template/common/search.twig
Search bar has been converted to a native HTML form,
unnecessary Jquery code associated with the old implementation has been removed
> Search bar wrap in HTML form

- upload/catalog/controller/product/category.php
> in pagination path double

- upload/admin/controller/sale/subscription.php
$result belong to a loop higher up and may have been improperly copied here.
> Fix subscription cycle

- upload/extension/opencart/catalog/model/shipping/weight.php
First argument of calculate() is a float.
> Cast cost to float

- upload/admin/model/catalog/product.php
After refactoring many model functions do not trigger events. 
If this fix is fine I will check other models.
> Admin product model fix events

- upload/system/config/paypal.php
Remove duplicate array key from system/config/paypal.php
> [3.0.x.x] Remove duplicate array key

- upload/extension/opencart/catalog/view/template/module/filter.twig
> Add missing escape to filter moule

- upload/admin/model/tool/backup.php
Bugfix for escaped line breaks in backup tool
> Bugfix backup tool

- upload/admin/controller/common/forgotten.php
Use existing validated admin email address for admin forgotten password reset
> Improved security for admin forgotten

- upload/admin/controller/design/theme.php
- upload/admin/controller/design/translation.php
Pagination fixes for theme and language editors
> Pagination fixes

- upload/admin/controller/design/theme.php
More pagination fixes for theme editor
> More pagination fixes

- upload/admin/controller/tool/backup.php
Added support for Windows line endings \r\n for restore function
> [3.0.x.x] Windows line endings

- upload/system/config/paypal.php
Removal of duplicate array entry in config/paypal.php
> [3.0.x.x] Minir bugfix for PayPal

- upload/admin/controller/tool/log.php
Security patch for displaying log contents
> [3.0.x.x] Security patch

- upload/system/helper/general.php
Use a secure random number generator and not something that is predictable.
> [3.0.x.x] Token generator

- upload/admin/model/localisation/currency.php
See https://github.com/opencart/opencart/issues/13745
> [3.0.x.x] Bugfix for currency cache

- tools/Dockerfile
> Add missing webp lib to docker file

- upload/admin/controller/extension/payment/paypal.php
- upload/admin/language/en-gb/extension/payment/paypal.php
- upload/admin/view/javascript/paypal/paypal.js
- upload/admin/view/stylesheet/paypal/card.css
- upload/admin/view/stylesheet/paypal/paypal.css
- upload/admin/view/template/extension/payment/paypal/applepay_button.twig
- upload/admin/view/template/extension/payment/paypal/auth.twig
- upload/admin/view/template/extension/payment/paypal/button.twig
- upload/admin/view/template/extension/payment/paypal/card.twig
- upload/admin/view/template/extension/payment/paypal/general.twig
- upload/admin/view/template/extension/payment/paypal/googlepay_button.twig
- upload/admin/view/template/extension/payment/paypal/message_configurator.twig
- upload/admin/view/template/extension/payment/paypal/message_setting.twig
- upload/catalog/controller/extension/payment/paypal.php
- upload/catalog/controller/extension/payment/paypal_applepay.php
- upload/catalog/controller/extension/payment/paypal_googlepay.php
- upload/catalog/view/javascript/paypal/paypal.js
- upload/catalog/view/theme/default/stylesheet/paypal/paypal.css
- upload/catalog/view/theme/default/template/extension/payment/paypal/paypal.twig
- upload/catalog/view/theme/default/template/extension/payment/paypal/paypal_applepay.twig
- upload/catalog/view/theme/default/template/extension/payment/paypal/paypal_applepay_modal.twig
- upload/catalog/view/theme/default/template/extension/payment/paypal/paypal_googlepay.twig
- upload/catalog/view/theme/default/template/extension/payment/paypal/paypal_googlepay_modal.twig
- upload/catalog/view/theme/default/template/extension/payment/paypal/paypal_modal.twig
- upload/catalog/view/theme/default/template/extension/payment/paypal/paypal_paylater.twig
- upload/catalog/view/theme/default/template/extension/payment/paypal/paypal_paylater_modal.twig
- upload/system/config/paypal.php
- upload/system/library/paypal/paypal.php
> PayPal upgrade

- upload/admin/language/en-gb/extension/payment/paypal.php
- upload/catalog/controller/extension/payment/paypal.php
- upload/catalog/view/javascript/paypal/paypal.js
- upload/system/config/paypal.php
Update to PayPal V3.0.2, has added bugfixes for Pay Later
> [3.0.x.x] Update PayPal

- docker-compose.yml
This is very useful during development. My proposed change allows to UP the [database management tool](https://www.adminer.org/) within all project.
> Add Adminer (Database management tool) to docker-compose file

- README.md
This updates the required version PHP graphic to match documentation at https://docs.opencart.com/en-gb/requirements/
> Update required PHP version graphic

- upload/install/opencart.sql
> Update opencart.sql - Stock status

- upload/catalog/controller/product/product.php
> Update product.php - Stock status

- upload/catalog/language/en-gb/product/compare.php
> Update compare.php - Stock status

- upload/admin/view/template/setting/setting.twig
> Update setting.twig - Stock status

- upload/admin/controller/setting/setting.php
> Update setting.php - Stock status

- upload/admin/controller/extension/extension/promotion.php
> Check promotion response is valid

- upload/admin/controller/setting/setting.php
https://github.com/pemaier/opencart/commit/48f1c578228d2e19d025afebdf2d28336392205e
> Update setting.php - missing part autocomplete_limit error handling

- upload/system/library/cart/cart.php
Fix typo which resets cart session_id to 0 or 1 on every page update.
> Fix cart session_id typo

- upload/admin/model/extension/dashboard/map.php
Fix DB query for orders with unknown or non-existing countries
> Bugfix for dashboard map

- upload/admin/controller/common/dashboard.php
make sure to use the configured currency engine for the auto-refresh.
> Bugfix auto currency refresh

- upload/catalog/model/extension/currency/ecb.php
Remove redundant load model from model/extension/currency/ecb
> Remove redundant  code

- upload/catalog/controller/product/category.php
- upload/catalog/controller/product/manufacturer.php
- upload/catalog/controller/product/search.php
- upload/catalog/controller/product/special.php
Improved pagination limit verifications
> pagination limit fixes

- upload/admin/controller/catalog/product.php
- upload/admin/language/en-gb/catalog/product.php
- upload/admin/model/catalog/product.php
- upload/admin/view/template/catalog/product.twig
Daniel, please add more functionality to admin product filters. OC users asked to do this for years. Existing product filters are insufficient when you have thousands of products in hundreds of categories.
1. Add filter by category/manufacturer
2. Add filter by price/quantity range
> Admin product list filters

- upload/system/library/mail/mail.php
- upload/system/library/mail/smtp.php
HTML and text parts are different
Make sure your TEXT version looks similar as the text inserted in your HTML version
> FIX - SpamAssassin does not like you - MPART_ALT_DIFF

- upload/admin/controller/catalog/category.php
- upload/admin/language/en-gb/catalog/category.php
- upload/admin/model/catalog/category.php
- upload/admin/view/template/catalog/category.twig
Modern stores have hundreds and even thousands of categories. Category list must have filters by name, parent, status
> Admin category list filters

- README.md
This is PR talks about running Open Cart Locally using Docker Desk top on windows
> Docker Desktop

- upload/catalog/controller/checkout/cart.php
could even be changed a bit more to be consistent with this if you want https://github.com/opencart/opencart/blob/e4c8d356614aeb634c39e85ecd42655000ad837d/upload/admin/controller/sale/order.php#L683
> display upload name in cart

- upload/catalog/controller/common/cart.php
could even be changed a bit more to be consistent with this if you want https://github.com/opencart/opencart/blob/e4c8d356614aeb634c39e85ecd42655000ad837d/upload/admin/controller/sale/order.php#L683
> show upload name in cart

- upload/admin/view/template/catalog/category.twig
> Update category.twig - Form reset

- upload/admin/controller/extension/extension/promotion.php
- upload/admin/index.php
- upload/index.php
Bugfix promotion.php for PHP 7.4
> Bugfix for promotion

- upload/admin/model/catalog/product.php
https://github.com/opencart/opencart/issues/14077
return getSeoUrls function
> https://github.com/opencart/opencart/issues/14077

- upload/admin/language/en-gb/setting/setting.php
- upload/admin/view/template/setting/setting.twig
https://github.com/opencart/opencart/issues/14100
> https://github.com/opencart/opencart/issues/14100

- upload/system/library/document.php
add addMeta and getMeta methods for managing metadata. These methods are essential for improving SEO.
> Add Meta in document.php

- upload/extension/opencart/catalog/controller/checkout/shipping.php
> fix wrong namespace

- upload/admin/controller/extension/currency/fixer.php
- upload/admin/language/en-gb/extension/currency/fixer.php
- upload/admin/model/extension/currency/fixer.php
- upload/admin/view/template/extension/currency/fixer.twig
- upload/catalog/controller/extension/currency/fixer.php
- upload/catalog/model/extension/currency/fixer.php
Useful for currencies not supported by the ECB.
> [3.0.x.x] Added fix.io currency converter engine

- upload/catalog/controller/checkout/payment_method.php
- upload/catalog/view/template/checkout/payment_method.twig
Pass session 'agree' to view so switch can be checked on load (eg: refreshed, or navigated away briefly)
> Checkout payment method controller and view updates

- upload/php.ini
Fixes https://github.com/opencart/opencart/issues/14201
> Fix php.ini

- upload/catalog/view/javascript/common.js
Remove "e.preventDefault();" to make search bar work
> https://github.com/opencart/opencart/issues/14205

- upload/catalog/view/stylesheet/stylesheet.scss
> Fix breadcrumb dividers height

- upload/catalog/controller/checkout/register.php
Fix error:
Undefined array key "confirm" in \catalog\controller\checkout\register.php on line 421
> Remove password confirm validation in the checkout registration

- upload/admin/model/catalog/product.php
Sort product attributes on product form in the same order as they are sorted on frontend product page.
> Sort product attributes

- upload/admin/view/stylesheet/bootstrap.css
Everything is visible in the picture
> Fixed the color of the statistics progressbar

- upload/admin/controller/catalog/category.php
- upload/admin/language/en-gb/catalog/category.php
- upload/admin/model/catalog/category.php
- upload/admin/view/template/catalog/category_list.twig
- For each category, its picture is displayed
- Disabled categories are highlighted with a gray background
> List of categories with images

- upload/admin/controller/catalog/manufacturer.php
- upload/admin/language/en-gb/catalog/manufacturer.php
- upload/admin/view/template/catalog/manufacturer_list.twig
> List of manufacturers with images

- upload/admin/view/stylesheet/stylesheet.css
> Vertical alignment in tables

- upload/admin/model/localisation/country.php
- upload/admin/model/localisation/zone.php
removed country_id from the function as it was unnecessary.
> removed country_id

- upload/admin/controller/localisation/country.php
- upload/admin/model/localisation/country.php
- upload/admin/view/template/catalog/download.twig
- upload/admin/view/template/catalog/product_form.twig
- upload/catalog/controller/product/review.php
- upload/catalog/view/template/product/product.twig
In accordance to: https://github.com/opencart/opencart/blob/master/upload/admin/model/catalog/option.php#L477 with a matched conventional name and only one parameter.
> Modified localisation/country controller and model delete descriptions method

- upload/admin/view/template/setting/store_form.twig
for https://github.com/opencart/opencart/issues/14731
> Update store_form.twig for cookie policy

- upload/catalog/language/en-gb/default.php
required in Extension Module Topic
> Update default.php - added text_all

- upload/admin/controller/sale/order.php
In Admin, while creating new order, Product is not being added.
Found print_r() which preventing response as JSON.
Commented out print_r
> Commented out print_r() order.php

- upload/catalog/view/theme/default/stylesheet/stylesheet.css
Fix for alert close button positioning
> stylesheet fix

- upload/catalog/model/account/return.php
Added missing space in SQL query
> Bugfix: getTotalReturns

- upload/admin/index.php
- upload/index.php
> Updated version number

- upload/system/config/paypal_carrier.php
Fix for system/config/paypal_carrier.php
> Added mssing semi-colon

- upload/catalog/controller/extension/recurring/paypal.php
- upload/catalog/controller/extension/recurring/squareup.php
Will also need applying to the original extension code bases.
Would need information relating to a customer so unlikely to be a major issue.
> [3.0.x.x] Protect against XSS in recurring extensions

- upload/admin/view/template/catalog/category.twig
- upload/admin/view/template/catalog/product.twig
- upload/admin/view/template/catalog/review.twig
- upload/admin/view/template/cms/comment.twig
- upload/admin/view/template/customer/customer.twig
- upload/admin/view/template/customer/customer_approval.twig
- upload/admin/view/template/customer/gdpr.twig
- upload/admin/view/template/design/seo_url.twig
- upload/admin/view/template/localisation/zone.twig
- upload/admin/view/template/marketing/affiliate.twig
- upload/admin/view/template/marketing/marketing.twig
- Fixes logout that occurs when submitting the filter form.
- Added to javascript:  e.preventDefault();
- Fixes opencart #14848
> [Master] Fix Admin Filter Submit logout

- tools/daux.io/src/js/search/index.js
Enhance search experience: retain query in URL and support back/close actions
- Search input now updates the URL with ?q= when a search is made
- Supports loading previous searches using browser back/forward (popstate)
- Clears query and search results from the page on pressing Escape
- Helps users share or revisit search results easily
> feat: Improve search experience by syncing URL with search query

- upload/system/library/cache/file.php
pls remove https://github.com/opencart/opencart/pull/14890
> Update file.php FIX my fall

- upload/catalog/controller/extension/feed/google_base.php
See https://forum.opencart.com/viewtopic.php?p=879643#p879643
> PHP 8.4 fix for extension/feed/google_base

- upload/catalog/controller/extension/feed/google_base.php
See https://github.com/opencart/opencart/pull/14956#issuecomment-2997306458
> [3.0.x.x] google base fix

- upload/admin/controller/startup/sass.php
- upload/catalog/controller/startup/sass.php
sass is compiled on every http request now. This slows things down a lot
> Fix sass cache

- upload/system/library/db/pgsql.php
Improve PHPDoc blocks for all PostgreSQL driver methods with detailed descriptions, proper typing, and comprehensive parameter documentation to enhance code maintainability and developer experience.
> fix(phpdoc): enhance PostgreSQL driver method documentation

- .dockerignore
- .gitignore
- docker-compose.yml
- docker/apache/conf/httpd.conf
- docker/apache/conf/opencart.conf
- docker/php/Dockerfile
- docker/php/docker-opencart-entrypoint
This PR enables users to securely relocate the storage directory outside the web root through the admin panel, with changes persisting after container restarts.
> [!CAUTION]
> **Breaking Change**: This update changes Docker volume mount structure. Existing containers must be recreated.
> 
> **Required steps for existing installations:**
> 1. Backup your data before updating
> 2. Stop containers: `docker compose down -v` 
> 3. **⚠️ The `-v` flag will remove volumes and delete all data**
> 4. Delete configuration files:
>    - `upload/install.lock`
>    - `upload/config.php` 
>    - `upload/admin/config.php`
> 5. Rebuild and restart: `docker compose build && docker compose up -d`
> 6. **OpenCart will reinstall automatically on first startup**
> 
> **Data will be lost** if not backed up …
> feat(docker): enable secure storage relocation outside webroot

- upload/catalog/controller/checkout/payment_address.php
> payment address validation fix

- upload/catalog/controller/extension/feed/google_sitemap.php
remove CDATA, it's already UTF-8 encoding
> sitemap fix

- upload/admin/language/en-gb/extension/payment/paypal.php
- upload/admin/view/template/extension/payment/paypal/general.twig
- upload/catalog/controller/extension/payment/paypal.php
- upload/catalog/controller/extension/recurring/paypal.php
- upload/catalog/view/javascript/paypal/paypal.js
- upload/system/config/paypal.php
- upload/system/config/paypal_carrier.php
> [3.0.x.x] Update PayPal Checkout Integration

- upload/system/config/paypal_carrier.php
Added missing semi-colon in system/config/paypal_carrier.php
> [3.0.x.x] Bugfix PayPal Checkout Integration

- docker-compose.yml
This PR adds production-ready configuration improvements to enhance monitoring, resource management, and operational capabilities:
- Configures structured JSON logging with automatic rotation (10MB max size, 3 files) for all services
- Implements memory and CPU limits with reservations to prevent resource exhaustion
- Adds appropriate resource allocation based on service type (database, cache, web services)
- Improves container monitoring and log management for production deployments
> [!NOTE]
> ### Notes for developers
> 
> This PR focuses on improving the internal structure of the Docker setup. The **Docker configuration is still not considered production-ready** and further work will continue on enhancing its robustness and features.
> feat(docker): add production-ready logging and resource limits

- upload/admin/view/template/sale/order.twig
- upload/extension/opencart/admin/controller/report/customer_activity.php
- upload/extension/opencart/admin/controller/report/customer_reward.php
- upload/extension/opencart/admin/controller/report/customer_search.php
- upload/extension/opencart/admin/controller/report/customer_transaction.php
- upload/extension/opencart/admin/controller/report/marketing.php
- upload/extension/opencart/admin/controller/report/product_purchased.php
- upload/extension/opencart/admin/controller/report/sale_coupon.php
- upload/extension/opencart/admin/controller/report/sale_return.php
- upload/extension/opencart/admin/controller/report/sale_tax.php
> Update reports with the error like #15041

- upload/admin/controller/marketplace/installer.php
- upload/admin/language/en-gb/marketplace/installer.php
Just slightly improves user experience
> Added validation error message for install.json while uploading extension

- .gitignore
- Makefile
- docker/apache/conf/httpd.conf
- docker/apache/conf/opencart.conf
- docker/php/Dockerfile
- docker/php/docker-opencart-entrypoint
This PR simplifies the Docker container structure and improves developer experience by removing unnecessary complexity:
- Removes public_html symlink to eliminate confusion between upload/ and public_html/
- Configures separate home directory for www-data user to prevent bash history cluttering project root
- Sets proper file permissions to enable OpenCart storage relocation operations
- Updates `make php` command to start directly in OpenCart directory for better developer workflow
> [!WARNING]
> ### Important: Storage Relocation
> 
> When relocating OpenCart storage via admin panel, **always choose paths within `/var/www/`** (e.g., `/var/www/storage_new/`). 
> 
> Choosing paths outside this directory (like `/var/storage/`) will result in **data loss** when containers are recreated, as …
> refactor(docker): cleanup container structure and improve user experience

- docker-compose.yml
- docker/.env.docker.example
- docker/nginx/Dockerfile
- docker/nginx/conf/default.conf
- docker/nginx/conf/nginx.conf
This PR introduces an initial **Nginx** setup to the Docker configuration. It focuses on a flexible and optimized build process, leveraging multi-stage Docker builds.
The key changes include:
* **Multi-stage Dockerfile**: Nginx is built from source within a dedicated stage (`nginx-base`). This allows for creating optimized `development` and `production` images that only contain the necessary runtime files, reducing their size.
* **Custom Modules**: The build includes essential modules for enhanced performance and security:
* `ngx_http_brotli_static_module` & `ngx_http_brotli_filter_module` for modern compression.
* `ngx_http_headers_more_filter_module` to hide sensitive information like the Nginx version from response headers.
* **Configuration**: A new Nginx configuration (`nginx.conf`) …
> feat(docker): add nginx configuration

- docker/php/Dockerfile
This PR introduces the **`intl` PHP extension** to the Docker PHP image and sorts the extension list. This change improves the container's capabilities while also enhancing the maintainability of the `Dockerfile`.
The key changes include:
* **`intl` Extension:** The `intl` extension is added to provide a more robust and native way to handle international domain names. This is beneficial for functions like [`idn_to_ascii()`](https://github.com/opencart/opencart/blob/master/upload/system/helper/general.php#L305), which may be used in `oc_validate_email()` for more comprehensive validation.
* **Extension Sorting:** The list of installed PHP extensions is now sorted alphabetically. This small change makes it easier to quickly scan the list, check for existing extensions, and prevent …
> feat(docker): add intl extension and sort php extensions

- upload/system/startup.php
> [3.0.x.x] PHP version check

- upload/catalog/controller/affiliate/register.php
https://github.com/opencart/opencart/pull/15156#issuecomment-3378748018
> [3.0.x.x]Update register.php
