upload/admin/model/catalog/manufacturer.php
Including $manufacturer_id as argument for event trigger for post.admin.manufacturer.edit as per the documentation.
=> Fix event bug in manufacturer.php

upload/admin/controller/catalog/review.php
OpenCart lists reviews ordered by date added in ascending order (oldest first) by default. This patch reverses the default order (newest first) so that the reviews awaiting moderation are shown first.
This tweak in the Admin Panel can save us a click or two, and in day-to-day operations, these clicks add up.
This is one of the functions performed by one of the two functions performed by my extension http://www.opencart.com/index.php?route=extension/extension/info&extension_id=7841&filter_username=OC2PS&page=2
=> Admin Tweak - Reverse Default Order of Reviews

upload/install/index.php, upload/install/view/template/header.tpl
When installing opencart in secure mode, page layout was broken because of browser security regarding non-secure resources (scripts, links, fonts...).
Thanks
=> Add HTTPS support during installation

upload/admin/model/catalog/product.php
- when adding product there is no need to remove any attribute belonging to it (as there are none yet)
- when updating the product the attributes related to the product are already cleared with
```php
$this->db->query("DELETE FROM " . DB_PREFIX . "product_attribute WHERE product_id = '" . (int)$product_id . "'");
```
no need to issue more specific deletion queries inside the loop
```php
$this->db->query("DELETE FROM " . DB_PREFIX . "product_attribute WHERE product_id = '" . (int)$product_id . "' AND attribute_id = '" . (int)$product_attribute['attribute_id'] . "'");
``
=> redundant product_attribute queries

upload/catalog/view/theme/default/stylesheet/stylesheet.css
I've set a minimum width on the quantity input in the cart to allow 3 characters to fit.
=> fix cart quantity input width on mobile

upload/admin/model/catalog/product.php
all 'product_*' keys are non existent in $data since it's a product table only query result row. I removed those calls more then 2 years ago in my code. array_merge is used for merging values for existing keys.
No point in initializing $data to an array and then overwriting it in the next line. btw, $query->row is always an array (at least an empty array)
(Techically, there is no need here to left join to product_description in the query either other then to ensure the product has a valid description)
=> remove unneeded array_merge calls

upload/admin/model/catalog/product.php
https://github.com/opencart/opencart/issues/2977
=> Remove 2 ")" extra

upload/admin/controller/common/login.php, upload/admin/controller/error/not_found.php
In admin panel, if you are not logged in, and generate a `404 Not Found` error with something like `<youdomain>/admin/index.php?route=common/login/XXX` an `Undefined index` warning will appears leading to `Full Path Disclosure` issue.
=> Full path disclosure due to Undefined index

upload/install/opencart.sql
Historically known as Pondicherry, the territory changed its official name to Puducherry on 20 September 2006
=> State name changed

upload/admin/model/report/customer.php
`customer` model in `admin/model/report` use the following query in `getOrders` method:
```
SELECT c.customer_id, CONCAT(c.firstname, ' ', c.lastname) AS customer, c.email, cgd.name AS customer_group, c.status, COUNT(o.order_id) AS orders, SUM(op.quantity) AS products, SUM(o.total) AS `total`
FROM `oc_order` as o
LEFT JOIN `oc_order_product` as op
ON (o.order_id = op.order_id)
LEFT JOIN `oc_customer` as c
ON (o.customer_id = c.customer_id)
LEFT JOIN `oc_customer_group_description` as cgd
ON (c.customer_group_id = cgd.customer_group_id)
WHERE o.customer_id > 0
AND cgd.language_id = '1'
GROUP BY o.customer_id
ORDER BY total DESC;
```
This query produce wrong value in `orders` and `total` fields, because it sum the total order for every product in the order itself.
customer_id | ... | orders …
=> Fixed issue 3101

upload/catalog/model/checkout/order.php
Added order_id, order_status_id, comment and notify data to the pre.order.history.add event trigger.
If accepted, the wiki would have to be updated to reflect the changes.
Joel.
=> Modification to pre.order.history.add event trigger

upload/catalog/controller/affiliate/login.php, upload/catalog/controller/affiliate/register.php
In the following controllers are used two method not belonging to the used model.
In particular:
in `catalog/controller/affiliate/register.php`:
```
// Clear any previous login attempts in not registered.
$this->model_affiliate_affiliate->deleteLoginAttempts($this->request->post['email']);
```
and
in `catalog/controller/affiliate/login.php`
```
// Check how many login attempts have been made.
$login_info = $this->model_affiliate_affiliate->getLoginAttempts($this->request->post['email']);
```
The problem is that in affiliate model (`catalog/model/affiliate/affiliate.php`) there are no methods like `deleteLoginAttempts` and `getLoginAttempts`, because they belongs to customer model (`catalog/model/account/customer.php`).
=> Fixed issue #3116

upload/system/helper/general.php
As per PHP documentation, mt_rand() is a drop-in replacement for rand() with the following advantages:
- it generates better random values (using stronger algorithm)
- it is four times faster than rand()
=> use mt_rand() instead of rand()

upload/admin/view/template/localisation/language_form.tpl
The Locale field throws a "Locale required" error if you don't fill it in, so I have added a required flag in the form.
=> Add "required" asterisk to locale field

upload/catalog/controller/payment/pp_express.php
In PayPal Express module 'expressComplete' function, there's no need to decrypt the 'File' type option or to return the file name because this data is to be saved into the order table in the database, not for view display. So the raw upload 'code' should be saved instead.
=> Encryption is not required for 'File' type option

upload/catalog/controller/product/category.php, upload/catalog/controller/product/manufacturer.php, upload/catalog/controller/product/search.php, upload/catalog/controller/product/special.php
Converted limit from GET to be an integer.  This is to avoid customers overriding the limit value in the URL triggering a division by zero error.
This is similar to @eka7a pull request except updated for the latest master.
=> Convert Limit to Integer

upload/admin/language/english/catalog/product.php
The term "SEO Keyword" has been causing a lot of confusion for OpenCart shop owners.  I've lost count the number of times I've worked on a customer's site only to find their SEO Keyword field stuffed with Google keywords.
It's pretty obvious why they believe that the SEO Keyword field is to input Google keywords. If you Google the term "SEO Keyword" the results are all related to Google keywords, and nothing to do with SEO friendly URLs.
I am proposing that we finally eliminate this issue by changing the field text to read "SEO URL".
This will lessen the issues of shop owners using the field for Google keywords.  It also now makes the field text correspond with the system setting "Use SEO URLs", so it's easier to identify that the two fields work together.
Joel.
=> Change SEO Keyword Text to SEO URL

upload/admin/view/template/design/banner_form.tpl
Fixed the broken layout issue appearing on the admin panel, when someone adds the first image to a banner.
Before:
After:
=> Fixed broken layout when adding a new image to a banner

upload/system/library/mail.php
If someone would ever use
```php
$mail = new Mail();
$mail->setReplyTo($reply_to);
...
$mail->send();
```
Make sure the reply-to email address that is being set in ```$mail->setReplyTo($reply_to);``` is being used, instead of the ```$mail->from```, when creating the email headers here:
```php
$header .= 'Reply-To: =?UTF-8?B?' . base64_encode($this->reply_to) . '?=' . 
' <' . $this->reply_to . '>' . $this->newline;
```
Bug was introduced here https://github.com/opencart/opencart/commit/7851910af42eaaee84492ca62d2bbce34434418e
Note: although setReplyTo() is not used anywhere yet, it's very useful when sending an email on somebody else's behalf. So if one would every use it, this bug is fixed here.
=> Bug fix: if $mail->reply_to is set, use that (instead of $mail->from) in the email headers 

upload/admin/controller/design/layout.php
Some developers include HTML content inside module heading_title language like base64 images, text decorations, etc which causes javascript conflict and blocks 'Add Module' button.
=> Prevent html content inside modules dropdown

upload/system/library/tax.php
Please verify:
the condition in line 113
```php
if (isset($tax_rate_data[$tax_rate['tax_rate_id']])) {
//...
}
```
is never met.
the loop can be written as
```php
foreach ($this->tax_rates[$tax_class_id] as $tax_rate_id => $tax_rate) {
//...
}
```
the keys are $tax_rate['tax_rate_id'] and the same key will be never called again.
The class tax doesn't support having the same tax rate set more than once (with different "based") for the same tax class, because the keys are the tax rates' ids. To support that we need to add a new level in the tax_rates property as for instance:
```php
$this->tax_rates[$tax_class_id][$based][$tax_rate_id] = $tax_rate;
//instead of just
$this->tax_rates[$tax_class_id][$tax_rate_id] = $tax_rate; // current implementation
```
the getRates loop would look like …
=> never met condition

upload/admin/controller/extension/installer.php
Hi guys,
I suppose this is a bug. First we're fetching a data via `ftp_nlist` function as array data.
Next we're going to loop over this variable, but in the 1st iteration this array is being overwritten by it's value.
=> Fixed variable overwrite within a `foreach` loop.

upload/admin/controller/catalog/category.php
the $this->error['warning'] should be outside the keyword validation to show warning for other error
=> [category.php] show warning on all error

upload/catalog/controller/payment/pp_express.php
According to https://www.paypal.com/uk/custom the header image size should be maximum 750x90, and the pp_express controller incorrectly sets it to 790px, which results in cropping of the image on PayPal. Changed both instances of the wrong size to the correct one.
=> [pp_express] Changed the logo's width to 750px

upload/admin/view/template/payment/pp_express.tpl
Adding a logo on the Checkout tab of the PayPal Express module was not working (it was not saving the image URL to the database), because of the lack of ID tag on the logo's hidden input field. Added it, and now it works properly.
=> [pp_express] Added an ID tag to the logo's hidden input

upload/admin/model/catalog/product.php
- we just need product table columns her, we are not displayin localized infos.
- i still believe array_merge is not necessary here, a simple key assignment would be better: keys starting with "product_" are not present in $data (i.e. ) $query->row
=> copyProduct: unused var assignment and db join

upload/catalog/controller/common/maintenance.php
Hi guys,
Please merge this fix.
It fixes `PHP Fatal error:  Class 'User' not found in .../catalog/controller/common/maintenance.php on line 16`.
[Here](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/common/maintenance.php#L16) is user a `User` class which has not been imported.
Thanks.
=> Add `use Cart\User` namespace/class

upload/admin/model/report/product.php
Daniel, please verify:
According to Cart/Cart  and ControllerCheckoutConfirm  the order_product table rows are populated like this:
total = cart product total = unit price * quantity
tax = unit tax amount ( see ControllerCheckoutConfirm populating$order_data['products'] ~ line 224) 
so we need to sum op.total + op.tax*op.quantity to get the order product total tax included instead of 1st adding up total + single tax
i believe (not 100% sure) that some time ago (maybe version 1.5.1~2 the tax column in order_product held the total product tax)
regards
=> product report total

upload/install/opencart.sql
There are no cities with such name in Russia (Russian Federation).
The right city is 'GoRNo-Altaysk', not 'GoMo-Altaysk'. It is OCR mistake, probably.
Please, keep this string:
(2738, 176, 'Gorno-Altaysk', 'GA', 1),
And delete this:
(2737, 176, 'Gomo-Altaysk', 'GA', 1),
=> Delete a non-existent city 'Gomo-Altaysk' from Russia country

upload/catalog/model/total/reward.php
I later tested and realized in some conditions when user uses all of his reward points this conditon fails to work.
it shuld be >= not just >
=> Incorrect Comparision condition

upload/catalog/view/theme/default/template/checkout/checkout.tpl
Reproduce:
- Go to checkout page
- Stay at step 5 - Choose Payment Method
- Choose any payment methods
- Don't click on the Terms & Conditions checkbox
- Click the Continue button
You will see the warning message but the Continue button will be disabled endlessly
=> Reset continue button on payment method step 5 in case of error

README.md
Update the link to the new sub forum OpenCart 2.0 Support -> Bug Reports; instead of OpenCart 1.5+ Support -> Bug reports. 
Might take ppl to report buts in the proper zone.
=> Minor Fix: Update Link to 2.0 Support on Readme.MD

upload/catalog/model/tool/image.php
Non-ASCII letters in URLs should be encoded through %-encoding (see RFC). Users with non-ASCII alphabet still use non-ASCII letters and whitespaces in images and image folders. Modern browsers is not take care of wrong image URLs, but image URLs into data feeds are still incorrect. Data feed readers raise image URL error.
=> Rawurlencode for non-URL letters in image URLs

upload/catalog/view/javascript/common.js
- Reason:
When using default theme to create another theme, sometimes you need to
change search input location and when remove it from header the
javascript selector isn't work anymore.
=> Changed search selector in common javascript.

upload/system/library/cart/currency.php
Hello Daniel/James,
please verify carefully my changes and thoughts.
1. No need to set $value = $value
2. Using $value both as the conversion parameter name and the soon-to-be formatted value name can be a little confusing. I changed it to $amount (I could have re-used $number as well)
3. If we are not returning a formatted string we could simply return the rounded value without calling number_format.
regards
=> simplified format method

upload/catalog/model/shipping/usps.php
Submitting over 70 pounds causes a fatal error, which prevents all shipping methods from working.  This patch will silently ignore all weights over 70, allowing other shipping methods to work.
=> Weight limit error check

upload/admin/model/catalog/product.php
Issue #3706 fixed.
```php
$this->db->query("DELETE FROM " . DB_PREFIX . "product_attribute WHERE product_id = '" . (int)$product_id . "' AND attribute_id = '" . (int)$product_attribute['attribute_id'] . "', language_id = '" . (int)$language_id . "'");
```
Amended to: 
```php
$this->db->query("DELETE FROM " . DB_PREFIX . "product_attribute WHERE product_id = '" . (int)$product_id . "' AND attribute_id = '" . (int)$product_attribute['attribute_id'] . "' AND language_id = '" . (int)$language_id . "'");
```
Thank you.
=> Issue #3706 fixed

upload/admin/model/report/customer.php
The SQL query part where it limits the number of rows is wrongly appended in the sub query instead of at the end of the query. This produces incorrect returned results.
=> getOrders query limit at wrong place

upload/system/engine/front.php
Hello Daniel, James
please verify
- i believe it would be better to typehint methods and have conditionals with `instanceof Action`.
- when defaulting $error and $action i believe it would be better to set them `null` instead of empty string as they are expected to be objects
- renaming $error to $error_action would make the code a little clearer about the role of the $error property
(btw i also usually typehint the $registry dependency with Registry in constructors)
...as usual this is just a suggestion (based on changes i already made in my implementation), feel free to close this pr at once if not interested...
kind regards
=> $action, $error, $pre_action elements typehinting

upload/system/engine/action.php
call_user_func_array requires the second parameter to be an array
=> execute(...) $args array type-hinting

upload/catalog/model/openbay/ebay_product.php
There are three occurrences of the string 'now()' in the file that should probably read now() instead as 'now()' is a literal string and not the function call that the original author intended.
=> Fix possible issue in ebay_product.php

upload/admin/controller/sale/order.php
Scenario:
Admin with https.
The variable contains URL with http:
admin/controller/sale/order.php
$data['store_url'] = $order_info['store_url'];
Problem with ajax http:
admin/view/template/sale/order_info.tpl
// Login to the API
$.ajax({
url: '<?php echo $store_url; ?>index.php?route=api/login',
=> Bug fix admin sales->orders->view with https

upload/admin/controller/catalog/product.php, upload/admin/language/en-gb/catalog/product.php, upload/admin/view/template/catalog/product_form.tpl
re-styling image tab content and add new additional images language
string for not confusing the back-end user(admin/staff) between product
image and product additional image
=> product edit tab-image content

upload/catalog/view/theme/default/template/account/address_form.tpl, upload/catalog/view/theme/default/template/account/edit.tpl, upload/catalog/view/theme/default/template/account/register.tpl, upload/catalog/view/theme/default/template/checkout/guest.tpl, upload/catalog/view/theme/default/template/checkout/guest_shipping.tpl, upload/catalog/view/theme/default/template/checkout/payment_address.tpl, upload/catalog/view/theme/default/template/checkout/register.tpl, upload/catalog/view/theme/default/template/checkout/shipping_address.tpl
- Scenario 1 (register):
If '$('#account .form-group').length' or '$('#address .form-group').length' is equal to '$(this).attr('data-sort')'
Result: hidden  custom field
- Scenario 2 (new address):
If '$('#collapse-payment-address .form-group').length' or '$('#collapse-shipping-address .form-group').length' is equal to '$(this).attr('data-sort')'
Result: hidden custom field
- Scenario 3 (new address):
There are the firstname and lastname fields, these fields are added to '$('#* .form-group').length'
Result: custom field data-sort error position
=> Bug fix custom field sort order the catalog

upload/system/config/catalog.php
Event on front site is not trigered because it's registered after the _startup/seo_url_.
Both _startup/seo_url_ and _maintenance_ have side effect by returning new action.
After change the sequence, Events is working as expected.
Note: the reason _action_event_ in config/catalog.php working because it's registered before the _pre_action_ on framework.php
=> Fix startup/event pre_action order

upload/admin/controller/extension/modification.php
Correction for #3793. <operation error="skip"> then will behave like in vqmod and will skip if explicitely written.
=> Correction for error="skip" attribute in ocmods

upload/admin/controller/startup/event.php, upload/catalog/model/extension/event.php
Events doesn't have explicit priority order; and there is no guarante sql use primary index in asc ordering.
Order clause is required to ensure Events is registered in guaranteed order.
=> make sure Events ordered asc by event_id

upload/catalog/controller/payment/worldpay.php
If a user changes the store currency display, adds items to cart, checks out and pays with Worldpay Online the store sends the incorrect order total to the payment processor.
Actual data sent:
- order amount - eg. 10 GBP (incorrect)
- currency - user selected eg. EUR (correct)
What it should be:
- order amount - cart default currency converted to user selected currency eg. 10 GBP becomes 11.29 EUR
This results in the user's card being charged 10 EUR for what should be a 11.29 EUR sale.
=> Update worldpay.php - fix total sent to payment processor

upload/admin/model/sale/order.php
Suggest reverting lines order to ASC (same as OC1.5)
This is a more natural way to read the lines from top (old ones) to bottom (last ones).
And when adding new history lines, prevent srolling the page to see what just has been added.
Note that returns were always ASC.
=> [2.2.0.0.b1] History lines ordered ascending

upload/admin/model/localisation/language.php
If 'directory' has been replaced by 'code', we always need 'locale' which is not in the cache.
=> [2.2.0.0.b1] locale is missing in cache

upload/system/library/db/mysqli.php
Functions `mysql_error ` and `mysql_errno ` were removed in PHP7. http://php.net/manual/en/migration70.removed-exts-sapis.php
Variable `trace` not exists.
Object `mysqli` doesn't have method `connected()` http://php.net/manual/en/class.mysqli.php
=> Refactored exception message in MySQLi class

upload/system/library/mail.php
Some SMTP servers respond with 220 code before responding with 250 response code. Hence, we need to ignore 220 response string if its sent from server before 250 and keep reading for the next empty space at 4th location of SMTP response string line. Look at the sample response below from one of the server, now, when existing code parse the below strings, it breaks in the "while" loop after reading line "220 and/or bulk e-mail." from server. Hence, the next "if" statement fails when it doesn't get the code "250" in the variable $reply as it contains 220 in this case. Now, in this example, 220 is a valid response that "Server is Ready" and the next response code is "250" but existing code is failing to cater this. Hence proposing a change which should just ignore the 220 response as its not …
=> Skipping SMTP Server's 220 response code

upload/system/engine/loader.php
There can be multiple loads of a same model in each request. The current implementation creates new model instance on each load and puts it in the registry. Additionally - it creates new instance on each model method call, since the model class is proxied. 
There is no need to create additional instances on each `$this->load->model('foo');` as they exist in the registry anyway. Also, creating a model instance of each proxy call provokes side effects like the one described in #4040. Also related to #4038 
This pull request fixes this behavior. It also adds a return statement for convenient uses like $this->load->model('model/test')->myMethod();
=> No need to create same model instance on each call

upload/catalog/view/theme/default/template/product/product.tpl
by default, when you add 4 or more related product, it will show 3 product on the first row and 1 product for second row which this should be 4 product per row, also corrected the class for (if column_left or right or both)
=> update catalog product.tpl for corrected product related class

upload/admin/controller/extension/modification.php
Allow module or extension refresh modification without having redirected to Extension/Modification
Example usage for module/extension. add this line of code
$this->load->controller('extension/modification/refresh', array('redirect' => 'shipping/productbase'));
https://forum.opencart.com/viewtopic.php?f=24&t=131995&start=20#p559546
=> Update modification for module/extension refresh

upload/catalog/controller/feed/google_base.php
Google limits the descriptions field to 5,000 characters and, last time I wrote a product export, they went out of their way to say HTML formatting was NOT allowed.
Personally, I like to jazz up my descriptions with bold lettering, images and other formatting.  strip_tags() removes all of that, plus any other tags left by the WYSIWYG editor, during the creation of the feed to keep it compliant.
=> Remove Formatting from Descriptions When Creating Google Base Feed

upload/install/model/install/install.php
This fix will eventually decode back the DB parameters sent by the form in the install process, so that the connection will be executed succesfully
=> Fix for DB parameters in install process

upload/system/library/template/php.php
`ob_get_clean()` acts like `ob_get_contents()` + `ob_end_clean()` combined call, we can return directly without assigning the buffer to a variable.
returning inside conditional allows us to get rid of `else` as well
=> returning directly via ob_get_clean

upload/system/engine/action.php, upload/system/engine/event.php
Currently the event implementation removes all of the actions for a given event trigger. Related to #4074
This pull request makes possible to unregister a certain action only. It also adds typehint for the action argument to allow registering of Action class instances only. The current possibility to unregister the entire trigger has been kept as the action argument is optional.
The $data class variable has been made protected in order to prevent unneeded modifications through direct access (they should happen via register/unregister methods only). A getData() method has been added if someone wants to inspect the events though.
=> Allow unregister of single event actions

upload/system/library/cart/cart.php
No reason to do a JOIN on a table that isn't being called upon, since the index value is the same in the ovd table.  The ov table just sits there looking like the loser that wasn't invited to the party, but showed up anyway.
Saving a few milliseconds here and there on a query make a big difference when a site gets a lot of traffic.
=> Redundant JOIN

upload/admin/model/extension/event.php
This is useful when you need to update an extension/module/theme and be sure it kept the events, or even for manipulating and solve conflicts.
The function will return the events using the same variables of the add event function.
=> Add get event to the event extension in the admin

upload/admin/controller/payment/eway.php
Amended ticket #4223. 
1) Line 298: 
```$json['message'] = $this->config->get('text_refund_failed') . $reason;```
Changed to: 
```$reason = $this->language->get('text_unknown_failure');```
2) Line 305:
```$json['message'] = $this->config->get('text_refund_failed') . $reason;```
Changed to: 
```$json['message'] = $this->language->get('text_refund_failed') . $reason;```
3) Line 361: 
```$json['message'] = $this->config->get('text_capture_failed') . $reason;```
Changed to: 
```$json['message'] = $this->language->get('text_capture_failed') . $reason;```
The ```$json``` array should now pick it's data from right method. 
Thanks.
=> Fix to issue #4223

upload/system/helper/utf8.php
Exression
` ($chr == 252 && $chr == 253)`
is always false.
This possible defect found by [static code analyzer AppСhecker](cnpo.ru/en/solutions/appchecker.php)
=> fix: expression is always false

upload/system/engine/loader.php
Questions:
1) Should we also add
```php
if ($result) {
return $result;
}
```
before the last return?
2) Should we move the return false on Exception before the after event so it does not get triggered or do we want to trigger the after event even for actions that return exceptions (call to magic methods, private methods, nonexistent controller files)?
=> remove unneeded else (shortcircuit return)

upload/admin/view/javascript/common.js
- calling $(selector) or even $(this) will create new jQuery object for each call.
- on is the recommended method to handle events: it superseeded live and delegate since jquery v 1.7:
```js
$(alwaysPresentWrapperElementSelector).on(events, dynamicOrNotInnerElementsSelector, handler);
```
=> cache $(this) and use jQuery dom obj for dropdown

upload/system/engine/event.php
1. the variable name `$key` is used as the numeric index placeholder for actions under the same `$trigger` key in `unregister()` and `removeAction()` methods, while is been used as a placeholder for a trigger key in the `trigger(...)` method
2. every `$this->data[$trigger]` is an array of actions, so i believe it's clearer to use that name instead of `$value` ($action->execute(..) is also more consistent with the resto of oc code)
3. renaming the argument in `trigger($event, ...)` allows us to consistenty use the name `$trigger` for event keys in `$this->data` throughout the whole class
=> renaming for clarity

upload/admin/controller/sale/order.php, upload/admin/view/template/sale/order_shipping.tpl
The shipping list AKA dispatch note's shipping address is mislabeled as payment address.
=> Shipping list's shipping address mislabeled

upload/admin/view/javascript/common.js
- fix image-modal flickering on second (close-action click)
- using bootstrap popover api to determine it's existence
- caching $element
- caching $('#button-image') and its icon inside the callback variables
- icon is not replaced, only the class attribute is replaced
=> fix image-modal flickering + cache jQuery objects

upload/catalog/controller/payment/divido.php
When accepting status updates from Divido, a new status code (referred) is
required to support certain banks.
Attention @davidteal
=> Added status code

upload/system/library/cache/mem.php
Deletion from memcached server(s) should have the same effect of the file cache adapter deletion.
When we use `$this->cache->delete('product')`, this call will delete all cache files with basename starting with 'product'. The same should happen with memcache adapter, but in the current imlementation it only deletes the `CACHE_PREFIX . 'product'` key.
Pls Daniel verify/test (I'm porting this mod from my memcache adapter that i have been using on production for 3+ year. I tested the mod in my setup, pls make sure to test it in your environment too as my original class extends a common abstract adapter with more properties and methods and sometimes different visibility).
=> memcache entries deletion 

upload/admin/view/javascript/common.js
`$(outerContainerSelector).on(events, innerPresentAndFutureElementsSelector, handler);`
out of curiosity: why escaping single quotes ` 'a[data-toggle=\'image\']'` ? Why not just  `a[data-toggle="image"]`?
=> replace jquery deprecated delegate() with on()

upload/system/library/mail.php
Content-Type: multipart/related creates a visualization issue on iOS email clients.
"multipart/mixed" solves this issue and the emails are still visualized correctly on multiple clients.
=> changed main content type of email

upload/admin/view/stylesheet/stylesheet.css
Responsive fixed and color updated on menu
=> Update CSS file

upload/install/model/upgrade/1006.php
fix copy/paste mistake for moving download to system/storage/upload instead of download
=> fix copy/paste mistake for moving download to system/storage/upload

upload/catalog/controller/api/order.php
fixes #4286
The problem with the issue was even after an order is completed from the back-end the oc_cart table entries remained and that resulted in them showing up again in another new order's product list.
Solution was to clear the cart once the order has been successfully added.
=> Fixes Create new order from admin panel always show the last created order products list #4286

upload/admin/model/catalog/category.php
To select category we must type beginning of category. Often names of categories starts same. Then find right category is hard. Now we can type text from any place in category name.
=>  Search in categories not only by starting text

upload/system/library/mail.php
The first parameter of the function should be a "path". The path will have been changed after we have used 'urlencode'
=> fix header of attachment

upload/catalog/controller/extension/payment/klarna_invoice.php
When activating the klarna module, a lot of notices and warnings came up in the checkout page. This was caused by array keys missing in the totals. This commit fixes this problem.
=> Fix klarna totals

upload/admin/view/javascript/common.js
Fixed issue #4739 with admin menu button not working to make vertical
menu slide out from the left on Safari browser, in Private Mode.
=> Fixed Issue #4739

upload/catalog/model/tool/image.php
Issue #4728 has been amended. 
Added extra ```str_replace()``` call to replace the sub-string on the right side.
This should stop the paths from breaking. 
Thank you.
=> Fixed Issue #4728

upload/admin/view/javascript/summernote/summernote.js
**Problem:**
When using multiple instances of summernote on admin this error come to console "node is null", this break the js flow and besides not letting the summernote take more than one textarea it break other js parts
**Solution:**
Instead of just making sure the node is text it also checks if the node really exists before trying to get its proprieties
**Now:**
If the node does not exist or for some reason is not true or do not have value we return false to the function.
PS: Also in the **master** branch, into the **dist**
https://github.com/summernote/summernote/blob/master/dist/summernote.js#L661
They changed it in the summernote core.
=> Fixing summernote core file

upload/admin/model/catalog/category.php, upload/admin/model/catalog/information.php
When new category and information pages are created, it adds empty seo keyword.
Fixed it.
=> Fixed empty keyword entry on new category and information page

upload/catalog/controller/extension/payment/securetrading_ws.php, upload/catalog/model/extension/payment/securetrading_ws.php
Fix for problem appearing with value being passed to the format method in Currency class and the last zero being dropped when amount was passed into round function.
Added new format method into the Secure Trading model.
Replaced round functionality with number_format and result conforms with XML spec Secure Trading require
=> Secure Trading Fix

upload/system/library/cart/user.php
Even if every class inherits from stdClass allowing us to add properties on runtime, i believe it's better to declare them.
I also think that we should add service properties (those fetched from the registry/service-provider), smt like:
```php
// User properties
private $user_id;
private $user_group_id;
private $username;
private $permission = array();
// services
private $db;
private $request;
private $session;
```
or as i always do, with doc-blocks to allow type-hinting and code completion
```php
class User {
// User properties
/** 
* @var int 
*/
private $user_id;
/** 
* @var int 
*/
private $user_group_id;
/** 
* @var string
*/
private $username;
/** 
* @var array 
*/
private $permission = array();
//services
/** 
* @var DB 
*/
private $db;
/** 
* @var Request 
*/
private $request; …
```
=> add missing property $user_group_id;

upload/admin/view/template/catalog/attribute_form.twig, upload/admin/view/template/catalog/attribute_group_form.twig, upload/admin/view/template/catalog/category_form.twig, upload/admin/view/template/catalog/download_form.twig, upload/admin/view/template/catalog/filter_form.twig, upload/admin/view/template/catalog/information_form.twig, upload/admin/view/template/catalog/option_form.twig, upload/admin/view/template/catalog/product_form.twig, upload/admin/view/template/catalog/recurring_form.twig, upload/admin/view/template/customer/custom_field_form.twig, upload/admin/view/template/customer/customer_form.twig, upload/admin/view/template/customer/customer_group_form.twig, upload/admin/view/template/extension/module/html.twig, upload/admin/view/template/extension/payment/bank_transfer.twig, upload/admin/view/template/extension/payment/klarna_account.twig, upload/admin/view/template/extension/payment/klarna_invoice.twig, upload/admin/view/template/extension/shipping/weight.twig, upload/admin/view/template/extension/total/klarna_fee.twig, upload/admin/view/template/localisation/length_class_form.twig, upload/admin/view/template/localisation/order_status_form.twig, upload/admin/view/template/localisation/return_action_form.twig, upload/admin/view/template/localisation/return_reason_form.twig, upload/admin/view/template/localisation/return_status_form.twig, upload/admin/view/template/localisation/stock_status_form.twig, upload/admin/view/template/localisation/weight_class_form.twig, upload/admin/view/template/sale/order_form.twig, upload/admin/view/template/sale/voucher_theme_form.twig
```twig
<input type="text" value="{% if foo %} {{ foo }} {% endif %}" />
```
```twig
<textarea name="text">{% if foo %} {{ foo }} {% endif %}</textarea>
```
If you click "Save" for the second time, the form will be **saved**! As you can see for yourself - it's wrong.
Replaced all inputs and textareas
```twig
<input type="text" value="{% if foo %} {{ foo }} {% endif %}" />
<input type="text" value="{% if foo %} {{ foo }} {% else %} {{ bar }} {% endif %}" />
<textarea name="text">{% if foo %} {{ foo }} {% endif %}</textarea>
<textarea name="text">{% if foo %} {{ foo }} {% else %} {{ bar }} {% endif %}</textarea>
```
on
```twig
<input type="text" value="{{ foo ? foo }}" />
<input type="text" value="{{ foo ? foo : bar }}" />
<textarea name="text">{{ foo ? foo }}</textarea>
<textarea …
```
=> Bug - whitespace in input and textarea

upload/system/startup.php
as `magic_quotes_gpc` was removed in php 5.4.0, the minimum php version now supported by opencart.
for the same reason we can now start using the "new" array syntax `[]`, which looks less like a function call :-)
=> remove magic_quotes_gpc cleanup code

tests/phpcs/OpenCart/IDE/README.md, tests/phpcs/OpenCart/IDE/opencart_phpstorm.xml
Suggesting IDE auto formatters settings to format code automatically.
* PHPStorm
Copy the file ```opencart_phpstorm.xml``` to:
- Mac ```~/Library/Preferences/<PRODUCT><VERSION>/codestyles/OpenCart.xml```
- Windows ```<User home>\.<PRODUCT><VERSION>\config\codestyles\OpenCart.xml```
- Linux ```~/.<PRODUCT><VERSION>/config/codestyles/OpenCart.xml```
* PHPStorm https://www.jetbrains.com/phpstorm/webhelp/code-style-xml.html
* PHPStorm https://www.jetbrains.com/help/phpstorm/2016.1/directories-used-by-phpstorm-to-store-settings-caches-plugins-and-logs.html
Thanks.
=> [phpcs] Adding code style auto formatters for PhpStorm

upload/system/library/image.php
I personally ran into an issue where my entire site would 500 internal server error due to upgrading PHP recently and not having GD installed with the new install of PHP. It was difficult to track down due to the issue arising in the cart header dropdown images so literally every page (minus admin pages) seemed to error making it appear like a site wide problem. I had to ssh into my server and browse PHP's error logs to figure out that it was the imagecreatefromjpeg function that was causing the issue. 
I put just a basic exit error to handle it and notify the developer of the issue at hand.
=> Added check for the PHP GD extension prior to using it in system/library/image.php

upload/admin/view/template/common/login.tpl
If you have your logins saved in your browser, this update will make it
faster for you to log in -- you just press the arrow down and submit.
This gets better if you have only one login saved -- the browser will
choose it by default for you and all you will have to do to log in is
just press the return/enter key
References:
- https://developer.mozilla.org/en/docs/Web/HTML/Element/input#attr-autofocus
- http://stackoverflow.com/a/4445824
=> Add autofocus to the admin login form username input

upload/admin/language/en-gb/customer/customer.php
$_['error_custom_field'] is missing and $_['error_zone'] was pointing to $_['error_custom_field'] error message. I think it was removed unintentionally when doing https://github.com/opencart/opencart/commit/0ecb05e6d49686fcbe426e857ad640d19d7fb298.
=> Missing $_['error_custom_field']

upload/system/library/db/mpdo.php
Also switched to fetchAll rather than loop with fetch and finally closed statement immediately after use to free up resources.  Leaving the statement open can leave the cursor open and cause issues.
Finally, upon enabling errors as exceptions, statement executions with empty result sets throw on fetch(), thus a guard around fetch to check that rowCount > 0 to work around this is added.
=> Set DB Errors to be thrown as exceptions in mPDO to eliminate silent fails

upload/admin/view/template/common/header.tpl
The Opencart logo at the admin panel is replaced with fa-opencart in order to adjust the mobile view.
=> Replace opencart logo with fa icon for mobile view

upload/system/library/db/postgre.php
Apparently no one has ever tested the Postgre Database Adaptor. The following change properly establishes a connection then checks the database connection.
=> Postgre Adaptor Correction

upload/catalog/model/account/order.php, upload/catalog/model/checkout/order.php
Customer group is missing on return array in get order function. If custom fields are needed in some modules, this is important field to have.. Else extra code in each module needs to be added for this.
=> Missing customer group id on getorder function

upload/admin/controller/marketplace/install.php
- Removed check for existing extension files as this prevents customers from being able to update extensions.
- Changed if modification already exists, the existing modification is deleted and the new modification file is installed.  Before, any extension with an install.xml file would be blocked from updating unless the customer manually deleted the existing modification prior to uploading the new extension files.
=> Fixed Extension Updating

upload/install/opencart.sql
Increased Event `code` column to 64 chars.  Allows for longer code names and will help prevent duplicate names.
=> Increased Code character limit in Event table

upload/catalog/model/extension/payment/amazon_login_pay.php
The function `getAdditionalCharges` was disregarding order totals with negative values, which was causing any discounts (which have negative values) to not be applied when calculating the total sum to be payed in Amazon.
=> Fix for discounts in Amazon Login Pay

upload/admin/language/en-gb/localisation/language.php
Fixed an error message which was output to the user when trying to add a new language where a code had already been assigned. This error message didn't make sense or tell the user what had happened.
=> Translation Fix: New language error_exists text fix

upload/admin/controller/extension/extension/dashboard.php
Hi, I believe you have missed one prefix of Dashboard which needs to be removed for the extension to be uninstalled.
=> Missed one Prefix of Dashboard

upload/catalog/controller/extension/captcha/google.php
Return error if not isset g-recaptcha-response, because maybe captcha was removed from the form.
=> Return error if not isset g-recaptcha-response

upload/catalog/controller/account/account.php
Catalog account/account page now properly lists payment extensions supporting credit card management.
=> Fix: Catalog account/account credit card extensions list now working.

upload/admin/controller/common/security.php
Fatal error: Uncaught Error: [] operator not supported for strings in ...admin\controller\common\security.php on line 30
=> Fix security.php PHP 7.0 and 7.1

upload/admin/controller/common/security.php
Fatal error: Uncaught Error: [] operator not supported for strings in ...\admin\controller\common\security.php on line 21
=> Fix error security.php in PHP 7.0 and PHP 7.1

upload/catalog/controller/extension/payment/squareup.php, upload/catalog/model/extension/payment/squareup.php, upload/system/library/squareup.php
As per the requirements of Square, they need this in order to track revenue share transaction attribution from 3rd party merchant/developer hosted apps (where the application id will not be known up front).
=> Square payment extension: Add integration_id parameter to API charge() requests.

upload/admin/language/en-gb/design/translation.php
Removed duplicate:
$_['text_edit']        = 'Edit Translation';
=> Fix duplicate language in translation.php

upload/catalog/model/extension/payment/mastercard_pgs.php
Fixed issue where the payment addresses of a successful order was overriding the payment addresses for all previous existing orders.
=> Mastercard payment extension bug fix

upload/catalog/model/extension/total/coupon.php
Since OC 2.2.x, $total is an Array so $discount_total should be compared with $total['total'] instead of $total which is an Array.
=> Comparing with wrong total

upload/install/cli_install.php
the cli installer includes the startup.php script, which references the DIR_STORAGE constant. This is triggering a PHP_NOTICE. DIR_STORAGE was added to remove this behaviour.
=> fix: added DIR_STORAGE constant

upload/system/library/db/mysql.php
should fix vulnerability to SQL injection via multi-byte attack when improper character set is set at the server level,
see http://php.net/manual/en/mysqlinfo.concepts.charset.php for details
I have spotted this issue while answering a question on Stack Overflow https://stackoverflow.com/questions/45378258/php-sql-injection-possibility/45379001.
I hope I am not mistaken as it is some time I've worked with `mysql_*` functions.
=> Fix possible SQL injection vulnerability

upload/catalog/controller/extension/payment/pp_standard.php, upload/catalog/view/theme/default/template/extension/payment/pp_standard.twig
Fix for state code not being sent to PayPal shopping cart in 'confirm' stage of shopping cart when using PayPal Payments Pro extension. Issue #5861
=> Fix for state code not being sent to PayPal shopping in PayPal Payments Standard extension

upload/admin/controller/extension/payment/squareup.php, upload/admin/language/en-gb/extension/payment/squareup.php, upload/admin/view/template/extension/payment/squareup.twig
This change is in accordance with Square's latest requirements.
=> Square payments: Video tutorial button now has text. Video link changed.

upload/system/engine/controller.php
This PR enables code completion for common magic properties by adding the @property in the DocBlock of the Controller class.
https://stackoverflow.com/questions/3814733/code-completion-for-private-protected-member-variables-when-using-magic-get/3815198#3815198
If you agree I will add @property annotations to other classes.
=> Enabling code completion for common magic properties

upload/catalog/view/theme/default/template/extension/payment/squareup.twig
On some themes, the checkout inputs are initialized with height=0. This fix adds a min-height style to the checkout input fields.
=> Square Payment Extension bug fix

upload/admin/model/sale/recurring.php, upload/admin/model/tool/upload.php
There was missing argument in getTotalUploads() function, causing uploads pagination not showing correctly after filtering data. Also for consistency added variable type in getTotalRecurrings() function, cause  all similar functions was using that.
=> Fixed uploads pagination bug

upload/admin/language/en-gb/tool/backup.php, upload/admin/view/template/tool/backup.twig
- Added in admin/language/en-gb/tool/**backup.php**:
`$_['text_history']      = 'Backup History';`
- Replacing in  admin/view/template/tool/**backup.twig**:
`Backup History`
For:
`{{ text_history }}`
=> Fix admin missing backup language

upload/admin/model/extension/payment/globalpay.php, upload/admin/model/extension/payment/globalpay_remote.php, upload/admin/model/extension/payment/realex.php, upload/admin/model/extension/payment/realex_remote.php, upload/catalog/model/extension/payment/globalpay_remote.php, upload/catalog/model/extension/payment/realex_remote.php
Amended cURL options to always verify peer, fixed security code presence indicator and treat the code itself as a string instead of an int.
=> Small amendments for Realex / Global Payments integrations 

upload/admin/model/extension/payment/globalpay.php, upload/admin/model/extension/payment/globalpay_remote.php, upload/admin/model/extension/payment/realex.php, upload/admin/model/extension/payment/realex_remote.php, upload/catalog/model/extension/payment/globalpay_remote.php, upload/catalog/model/extension/payment/realex_remote.php
Amended cURL options to always verify peer, fixed security code presence indicator and treat the code itself as a string instead of an int.
=> Small amendments for Realex / Global Payments integrations for 2.3.x

upload/install/controller/install/step_3.php
Revert change made in opencart/opencart#6182
I noticed this in: opencart/opencart#6230.
The preg_match was wrong, it was preventing underscores from being used in the db_prefix.
=> Fix preg_match in step 3

upload/catalog/controller/extension/payment/divido.php
Removed the string mexico44 from the request data array. It was causing a PHP Parse error
=> Fix issue with random string breaking the request data array

upload/system/library/cart/cart.php
The cart library is executing the same query multiple time.
if you check the 
`public function getProducts() {`
you will find that the function is called multiple time and each time is is executing database queries. The previous version of opencart have this covered and didn't have this issue. The previous version(1.5.6) set the $data variable and then use that variable for later function call. 
I think we should do the same for new version.
=> Cart Library getProducts function executing database query multiple time

upload/admin/controller/sale/order.php, upload/admin/model/customer/custom_field.php
If custom field is disabled it should not be shown on order form page. Currently the method get custom fields gets all custom fields even if status is disabled. So have added a filter code to filter by status. And then sending filter status as 1 for order form. So only enabled status would be shown on order form page.
=> don't show disabled custom field on order form page

upload/catalog/view/theme/default/template/product/product.twig
I think the share code should work alone without checking the status of the review. So maybe we should move AddThis share code outside of $review_status if statement on the product page?
=> Move AddThis share code outside of $review_status if statement on product page

upload/install/opencart.sql
Put this together for testing and I couldn't find any other incorrect event paths.
```php
$sql = "SELECT * FROM " . DB_PREFIX . "event";
$result = $db->query($sql);
foreach ($result->rows as $event) {
if (!$event['trigger']) continue;
$trigger = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$event['trigger']);
// Break apart the route
$parts = explode('/', $trigger);
$route = false;
$method = false;
while ($parts) {
$file = $root . implode('/', $parts) . '.php';
if (is_file($file)) {
$route = implode('/', $parts);
break;
} else {
$method = array_pop($parts);
}
}
// Remove everything before first slash e.g catalog/admin
$class = preg_replace('/[^a-zA-Z0-9]/', '', substr($route, strpos($route, '/')));
// Initialize the class
if (is_file($file)) {
include_once($file);
$controller = new …
```
=> Fix event path for add affiliate

upload/install/opencart.sql
Errors:
Notice: date_default_timezone_set(): Timezone ID '' is invalid in admin\controller\startup\startup.php on line 16
Notice: date_default_timezone_set(): Timezone ID '' is invalid in catalog\controller\startup\startup.php on line 31
Added in opencart.sql:
(0, 'config', 'config_timezone', 'UTC', 0),
=> Fix Notice: date_default_timezone_set()

upload/catalog/controller/common/footer.php
When using CDN remote addr is same, added http_x_real_ip for customer online. So it is possible to see the total number of customers online. Else it always shows 1 as Ip remains same.
=> When using CDN remote addr is same, added http_x_real_ip 

upload/admin/controller/marketplace/marketplace.php
Error:
When the member has a space in the name, the extensions are not displayed.
Added urlencode:
urlencode($this->request->get['filter_member'])
=> Fixed View all extensions in Marketplace

upload/catalog/controller/extension/captcha/google.php
There is a typo in the Google validate function allowing users to bypass the Google Captcha
=> Fixing typo

upload/admin/controller/mail/return.php, upload/catalog/view/theme/default/template/mail/order_alert.twig
[Issue Fix #7048 : Product's Options are not showing in Order Email Notification.]
**1) Issue Fix : **  Ordered Product's Options are not showing in email Notification. **Status- Resolved.**
**2) Issue Fix :**  Ordered Product Return History update at admin end. **Status- Resolved.**
**Error : ** <b>Error</b>: Call to a member function getLanguage() on null in <b>/home/users/viveksh047/www/html/official_oc/admin/controller/mail/return.php</b> on line <b>36</b>
**Reason : ** The issue was due to Language Model wasn't Load before calling the getLanguage() Method.
=> [Issue Fix #7048 : Product's Options are not showing in Order Email Notification.]

upload/admin/model/extension/payment/amazon_login_pay.php, upload/catalog/model/extension/payment/amazon_login_pay.php
- Fix an issue where the Amazon authorization is not changed to the Closed state after a successful capture.
- Add the missing `zone_code` address key.
- Change the meaning of the `zone` address key to contain the name instead of the code.
=> Bug fixes on Amazon Pay and Login with Amazon

upload/admin/language/en-gb/extension/extension/advertise.php, upload/admin/view/template/extension/extension/advertise.twig
This helps solve the issue where merchants are not able to install extensions under Extensions > Advertising.
=> Include an ad blocker error in Extensions > Advertising

upload/catalog/controller/extension/payment/amazon_login_pay.php, upload/catalog/model/extension/payment/amazon_login_pay.php
Suppress error messages triggered after the payment gets processed. This is to ensure the checkout flow does not get interrupted.
=> Improvement on Amazon Pay and Login with Amazon pay

upload/system/library/db/mysqli.php
The connection was not being closed since condition will always be false in case connection was made.
=> Connection was not being closed.

upload/system/library/session/file.php
When writing the session file on disk in the system/library/session/file.php, the fopen function in mode 'w' erases the file BEFORE acquiring the lock. This creates a race condition with the fopen in the read function, resulting in an empty session.
This resulted in annoying disconnections from the admin panel, but can be easily fixed by changing the fopen access mode from 'w' to 'c' and by emptying the file AFTER acquiring the lock by calling ftruncate.
=> Solving race condition in session file handling

upload/admin/model/extension/dashboard/map.php
If you have multiple complete statuses then you would get a statement like "WHERE o.order_status_id IN('5,3')" which gives 0 results because of the quotes. If you leave the int() declaration before the implode() function you get "WHERE o.order_status_id IN(5)".
Removing both the quotes and the (int) declaration before the implode() function gives a working map again.
=> Update map.php - Fix for empty map

upload/system/library/cache/redis.php
setTimeout is an alias for expire and will be removed in future versions of phpredis (is already deprecated when used on AWS).
=> Replace setTimeout with expire

upload/admin/controller/marketing/marketing.php
The alias name is missing in the controller (marketing.php) file. It should be m.name instead of the name.
Error code:- 
if (isset($this->request->get['sort'])) {
$sort = $this->request->get['sort'];
} else {
$sort = 'name';
}
Resolved code :-  
if (isset($this->request->get['sort'])) {
$sort = $this->request->get['sort'];
} else {
$sort = 'm.name';
}
=> Fixed default sorting for column Campaign Name on the Marketing page

upload/system/library/cache/redis.php
Removing deprecated function delete(), which will be removed in a future version of phpredis
Please refer.
https://github.com/phpredis/phpredis#del-delete-unlink
=> updation of deprecat function del

upload/catalog/controller/checkout/cart.php, upload/catalog/controller/common/cart.php
It's probably better to display a placeholder image for product items in cart that doesn't have any images instead of just leaving the column empty.
=> Add placeholder image to cart item for products without images

upload/admin/controller/customer/custom_field.php
Custom field is checked although it is not required.
It is already defined before foreach (custom_field_customer_group and custom_field_required).
No need to define for null array value again.
=> Custom field is checked although it is not required.

upload/catalog/view/theme/default/template/extension/payment/pp_standard.twig
When new web browsers start to change the default of SameSite to Lax for cookies (https://www.chromium.org/updates/same-site). PayPal needs to return to the store with a GET and not a POST or the session will be lost.
Changing 'rm' to 1 will force PayPal to return using a GET. https://www.paypal.com/ee/smarthelp/article/how-do-i-use-the-rm-variable-for-website-payments-ts1011
=> Fix PayPal Standard when session has SameSite=Lax

upload/admin/language/en-gb/localisation/currency.php, upload/admin/language/en-gb/localisation/length_class.php, upload/admin/language/en-gb/localisation/weight_class.php
The value field settings (for length, weight and currency) is confusing and unintuitive. For example, if my store is in HKD as the main currency, when I create USD as an alternative currency, I am tempted to type in 7.8 as the "value" because the value of USD is 7.8 HKD. This is the exact opposite of how the system work.
This pull request clarify the help message in order to assist the user to type in the correct value.
=> clarify help message for value settings

upload/.htaccess.txt
Added missing escape character for .twig extension in .htaccess.txt and fixed a typo.
=> Added missing escape character in .htaccess.txt

upload/admin/controller/marketing/contact.php
Fix multiple marketing email sending for **Customers** and **Affiliates** on admin `marketing/contact` page, as reported in #8051 by @eka7a.
Issue caused by the absent of pagination in retrieving individual customer info by calling `$this->model_customer_customer->getCustomer()` function repetitively from ajax call in the template:
https://github.com/opencart/opencart/blob/7d156508fd2cf6b1d12313db5c7b8e8c4291cbc3/upload/admin/view/template/marketing/contact.twig#L269-L271
Therefore, the fix involves chunking the function call in pages of 10.
=> Fix Multiple Marketing Email Sending for Customers and Affiliates from Issue #8051

upload/system/modification.xml
**Issue (Reference in issue #8094):**
When applying modifications from admin > Extensions > Modifications > Refresh button, the following error will occur in Modification Log:
```
FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!
```
All .twig modifications from any other 3rd party modifications will therefore fail to apply.
**Cause:**
Since twig has been updated to autoload from `storage/vendor` directory, OCMOD modification.xml needs to be updated as well to reflect the new twig loader changes.
=> [Important!] Fix OCMOD modification.xml not working for .twig files (Issue #8094)

upload/catalog/controller/checkout/cart.php
This PR changes the `edit` action from `ControllerCheckoutCart` to make it compatible with `cart.update` function from [common.js](https://github.com/opencart/opencart/blob/master/upload/catalog/view/javascript/common.js). Currently, that Javascript function is broken since the `key` param is ignored by the backend and the action responds with a redirect instead of a valid JSON response.
The changes aren't supposed to side-effect existing parts of the system that use the same route with the former behavior, i.e. expecting an array parameter named `quantity` having quantities indexed by cart keys.
=> Handle single item update with separate params in checkout/cart/edit

upload/install/controller/install/step_2.php
During Installation in **Step 2**:
1. `/config.php` check will show '_Writable_' even if it doesn't have writable permission.
2. `/admin/config.php` check will show '_Unwritable_' even if it's missing. Supposed to show '_Missing_'.
3. `~/upload/system/storage/cache/` check will always show '_Writable_' even if it doesn't have writable permission.
4. `~/upload/system/storage/logs/` check will always show '_Writable_' even if it doesn't have writable permission.
Various typos in variable names and missing checks.
=> Fix File & Directories Permission Checks in Install Script step_2.php

upload/catalog/model/catalog/product.php
Tested with 11,000 products, the MySql CPU resources is 4.7%, after this modification the CPU resources down to 2%
=> Updated Latest Module

upload/admin/model/catalog/category.php
In mysql, when using the LIKE operator, '_' means any one character, so the path for categories is not working correctly. For example
UPDATE `oc_seo_url` SET `query` = REPLACE(query, 'path=1', 'path=10_1') WHERE `query` LIKE 'path=1_%'
The code above will replace the path 10_1 in the database with 10_10_1
=> Important. Fix method editCategory

upload/admin/controller/design/layout.php
Refer to issue #8153 for detailed description.
Module language is loaded without 2nd `key` parameter, causing overwrite of certain language text, such as `'heading_title'` of the current Layout page.
The code is removed altogether as it was never used in its template file in `upload/admin/view/template/design/layout_form.twig`
=> Fix Unintended Heading Title Overwrite by Unused Module Language Load - Issue #8153

upload/catalog/controller/extension/module/latest.php
https://github.com/opencart/opencart/pull/6962 for 3.0.x.x as latest module can slow down sites with lot of products.
=> Use getLatestProducts in latest module

upload/catalog/controller/information/information.php
Only have to do a Google search for ```inurl:route=information/information/agree``` or a Bing search for ```instreamset:url:route=information/information/agree```, to see how many site have the terms pop up indexed.
=> Prevent terms pop up from being indexed

upload/system/engine/loader.php
The reason why we need to add this is due to the fact that the extension folder is now located outside of the admin and catalog folder. Prior to this change, Github users were suggesting similar solutions while it was not really necessary since the extension folder was still inside each core folders.
The system/engine/action.php file only validates the string of the method with | being entered but has no server functions to validate the controllers' method names being parametered into the ```$this->url->link``` method. While it is not necessary to edit the system/library/url.php file in this scenario, the system/engine/loader.php file does need to ensure that each extension lookups are loading with valid method names where only one method name is expected to be defined especially when an …
=> Added validateController into the loader engine - system/engine/loader.php file.

upload/catalog/controller/mail/order.php
Regarding this issue here: https://github.com/opencart/opencart/issues/8659
If additional admin alert emails are defined like (space after the comma):
> admin1@opencart.com, admin2@opencart.com 
only the first will receive an email.
Trim would prevent in future such issues, the more because there is no help (text) for this.
=> Admin additional emails when a space is used between

upload/admin/controller/common/filemanager.php
Mixing single-byte substr with the multi-byte utf8_strlen will cause issues if DIR_IMAGE does include any multi-byte characters.
See https://github.com/opencart/opencart/pull/8718#issuecomment-728902719 for an explanation.
=> Fix path check mixing byte and multi-byte functions

upload/system/helper/db_schema.php
Cause now it also includes extension code prefix
What was `my_beautiful_module` now will look like `my_awesome_extension.my_beautiful_module`
=> Allow longer module code

upload/admin/controller/common/column_left.php
Since FontAwesome5 may contain not only fas class, it is preferred to pass both classes in controller.
3d party extensions may use far, fab, etc. classes in left_column menu.
=> Fix FontAwesome5 left menu icons - p1

upload/admin/view/template/common/column_left.twig
Since FontAwesome5 may contain not only fas class, it is preferred to pass both classes in controller.
3d party extensions may use far, fab, etc. classes in left_column menu.
Sorry for two separate pull requests. Web version of GitHub seems does not allow pulling several files in one request
=> Fix FontAwesome5 left menu icons - p2

upload/admin/language/en-gb/tool/upgrade.php
if people read 1st message...
`Make a complete backup of your web site`
Then
`Backup here`
will understand that can make a full website backup...and not database backup...so should be changed from **Backup** in **Database Backup** and will become: **Database Backup here**
=> More language explanation Upgrade

upload/catalog/model/account/address.php
Deleting the customers default address should clear the address_id to reflect that they no longer have a default address.
see also issue #8148
=> Deleting the default address doesn't clear the customers default setting

.editorconfig
https://github.com/opencart/opencart/wiki/Coding-Standards#indentation
Always going to have issues due to the mixed indentation in the .twig files.
=> Update .editorconfig to match Coding Standards

upload/admin/model/sale/order.php
Otherwise the original order of the purchased products may be lost. See https://stackoverflow.com/questions/1949641/what-is-mysql-row-order-for-select-from-table-name/1949663#1949663
=> Make product order consistent on fragmented tables

upload/system/library/mail/smtp.php
=> SMTP changes

upload/catalog/controller/extension/payment/pp_standard.php
Redo https://github.com/opencart/opencart/commit/bc8603cd1a43a68db2324604b6e7ea6f8203792e which seems to have been undone.
=> Remove html_entity_decode from PayPal Standard

upload/catalog/controller/extension/payment/pp_standard.php, upload/catalog/view/theme/default/template/extension/payment/pp_standard.twig
https://github.com/opencart/opencart/issues/5861 for 3.0.x.x_Maintenance but with state names for other countries. Also required for https://github.com/opencart/opencart/issues/9463.
State codes used for Brazil, Canada, Italy, Mexico and USA (same as the PayPal Express module). More may be needed.
https://developer.paypal.com/docs/nvp-soap-api/state-codes/
=> Add state to PayPal Standard

upload/system/library/session/db.php
mt_rand() / mt_getrandmax() SHOULD BE LESS THAN $gc_probability / $gc_divisor.
so, setting up higher gc_divisor we will decrase gc startup chance.
=> fix for gc into session\db

upload/system/library/mail/smtp.php
https://github.com/opencart/opencart/pull/9552 for 3.0.x.x_Maintenance. smtp_username isn't guaranteed to be an email address.
=> Change SMTP MAIL FROM to be actual email address

upload/system/library/mail/smtp.php
This fixes the error "Error: MAIL FROM not accepted from server!" when using SMTP with Amazon SES, Sendgrid or any other provider where the username to authenticate with the SMTP server is not as same as the from email address.
I understand you guys may not want to use external libraries in your code, but this is where time tested stuff like PHPMailer comes very handy.
=> Fixes "Error: MAIL FROM not accepted from server!" with SMTP.

upload/catalog/model/catalog/product.php
```diff
public function getPopular(int $limit): array {
$product_data = $this->cache->get('product.popular.' . (int)$this->config->get('config_language_id') . '.' . (int)$this->config->get('config_store_id') . '.' . $this->config->get('config_customer_group_id') . '.' . (int)$limit);
if (!$product_data) {
+             $product_data = [];
$query = $this->db->query("SELECT p.`product_id` FROM `" . DB_PREFIX . "product` p LEFT JOIN `" . DB_PREFIX . "product_to_store` p2s ON (p.`product_id` = p2s.`product_id`) WHERE p.`status` = '1' AND p.`date_available` <= NOW() AND p2s.`store_id` = '" . (int)$this->config->get('config_store_id') . "' ORDER BY p.`viewed` DESC, p.`date_added` DESC LIMIT " . (int)$limit);
foreach ($query->rows as $result) {
$product_data[$result['product_id']] = …
```
=> Fix: null return

upload/admin/controller/design/theme.php
OC 3.0.3.6 & Custom Theme (only a few files from the default)
If OpenCart is used with a custom theme (e.g. default Theme but only a view modified templates), those custom templates are not affected.
Because the config setting is not **theme_default**, only **default**
=> Theme Editor > using default and custom templates side by side

upload/catalog/controller/extension/feed/google_sitemap.php
Having non-canonical URLs in the sitemap wastes crawl budget and gives mixed signals to search engines. Also fixes issue of products without images not being listed.
=> Fix non-canonical URLs in sitemap

upload/extension/opencart/admin/view/template/module/banner.twig
Twig\Error\SyntaxError: Unknown "endif" tag. in \extension\opencart\admin\view\template\module\banner.twig on line 44
=> Fix banner.twig - excess endif

upload/admin/controller/marketplace/marketplace.php
Fixes hash_hmac(): Passing null to parameter 3 ($key) of type string is
deprecated and urlencode(): Passing null to parameter 1 ($string) of
type string is deprecated.
=> Fix null credentials in marketplace for PHP 8

upload/admin/controller/user/user_permission.php
'event/currency',
'event/debug',
'event/language',
'event/statistics',
'startup/application',
'startup/error',
'startup/event',
'startup/extension',
'startup/language',
'startup/login',
'startup/notification',
'startup/permission',
'startup/sass',
'startup/session',
'startup/setting',
'startup/startup'
=> Disable unnecessary controller output

upload/install/opencart.sql
Crimea and Sevastopol already exist in DB and these are Ukrainian regions.
https://github.com/opencart/opencart/blob/1fcadadbe2506fb81b4600147518bec6d3255d6f/upload/install/opencart.sql#L5641
https://github.com/opencart/opencart/blob/1fcadadbe2506fb81b4600147518bec6d3255d6f/upload/install/opencart.sql#L5656
@danielkerr Please fix this.
I don't think it is a good idea to commit these regions as russian now.
This is an insult for the whole Ukrainian nation.
https://github.com/opencart/opencart/pull/8802
=> OC4: Fix Ukrainian Crimea and Sevastopol

upload/system/library/db/mysqli.php
https://github.com/opencart/opencart/blob/8c5b3da32fc2be141283e5fcedbb04f96122a556/upload/system/helper/db_schema.php#L119
If OC4 is going to use `utf8mb4` charset and collation you need to set connection charset to `utf8mb4` too. Otherwise it has no sense.
Just try to store any emoji icon 🏘 in product name and you will see the difference. With connection charset `utf8` it will be converted and stored in DB as ???.
In my opinion it is time to move to advanced `utf8mb4` because it allows to store more data in different languages plus emoji.
=> OC4: utf8mb4 in mysqli.php

upload/catalog/controller/information/contact.php
The from address can't be the customers address. If the customer has DMARC (using SPF & DKIM) correctly set up on their domain, then the email could likely be rejected by the store owners mail server.
Setting the from address as the customers email address was a workaround for some buggy Microsoft email clients that ignored the reply-to address.
=> Revert change made to contact from address

upload/system/helper/db_schema.php
`utf8mb4_general_ci` cannot be used with charset `utf8`. Installation fails with SQL error.
Perhaps this is a last change needed for moving OC4 to `utf8mb4` charset.
=> OC4: utf8mb4 charset fix in db_schema

upload/admin/model/setting/module.php
IMHO every single model function, creating a row in DB, must return this row id after executed.
I can check `$module_id = $this->db->getLastId();` in my code on clean opencart installation.
But what if this model function calls any `after` events which also insert rows into DB?
This is not a developer friendly software architecture when you need to create hacks, hooks, workarounds and other voodoo magic to get a single value for page redirect.
BUG:
By the way, on creating, for example a banner module, on save you are not redirected to created module page. 
So every click on Save button just creates a duplicate of a module.
=> OC4 return created module_id

upload/system/startup.php
REQUEST_URI has leading slash, so don't remove it when using PHP_SELF.
=> Don't remove leading slash from PHP_SELF

upload/system/helper/utf8.php
Now it always returns an empty string
=> OC4: fix broken utf8_substr with default 0 length

upload/system/library/cart/user.php
TypeError: Opencart\System\Library\Cart\User::isLogged(): Return value must be of type int, null returned in
https://github.com/opencart/opencart/issues/10971
=> TypeError: Cart\User::isLogged():

upload/catalog/controller/account/address.php, upload/catalog/controller/account/register.php, upload/catalog/controller/account/tracking.php, upload/catalog/view/template/account/address_form.twig, upload/catalog/view/template/account/register.twig, upload/catalog/view/template/account/tracking.twig, upload/catalog/view/template/product/product.twig, upload/extension/opencart/catalog/controller/total/shipping.php, upload/extension/opencart/catalog/view/template/payment/bank_transfer.twig, upload/extension/opencart/catalog/view/template/payment/cheque.twig, upload/extension/opencart/catalog/view/template/payment/cod.twig, upload/extension/opencart/catalog/view/template/payment/free_checkout.twig, upload/extension/opencart/catalog/view/template/total/shipping.twig
Thi resolves the issue #10887
Description: Since in Opencart 4 the selected language in the front part of the site is transmitted as a GET parameter, for all links and ajax calls that depend on the language, they must contain the selected language as a parameter. This is done in general, in this PR are added in places where it is missing and this leads to unexpected changes in the language for the user.
=> Add language parameter where missing in catalog side

upload/admin/view/template/user/api_list.twig
=> Fix issue #11020, missing sort by username link

upload/system/helper/utf8.php
Zero length needs to return an empty string. No length needs to return
the full string.
=> Fix utf8_substr

upload/catalog/model/account/subscription.php
Without these extra mandatory fields, it is likely that the insert into query will fail since all fields are mandatory from the database with NOT NULL.
=> Added extra mandatory fields in transaction method - catalog/model/account/subscription.php file

upload/admin/controller/marketplace/installer.php
This PR resolves problem in deleting extension files on linux server
**Problem**
In line:
https://github.com/opencart/opencart/blob/0fdb8b9bbe4fd5aa4fdda2e955bb982f33b3a10d/upload/admin/controller/marketplace/installer.php#L409
is used:
`glob(trim($next, '/') . '/{*,.[!.]*,..?*}', GLOB_BRACE)`
where in linux file names starting slash is removed. It results in nothing deleted on the server.
**Resolution**
Just use rtrim instead of trim
`glob(rtrim($next, '/') . '/{*,.[!.]*,..?*}', GLOB_BRACE)`
=> [OC 4 Master] installer.php uninstal wrong trim in glob

upload/admin/view/javascript/common.js
This PR resolves problem and javascript error in common.js when submit ajax form by jQuery.submit()
**Current state**
All works fine when ajax form is submitted by pressing a button.
**Problem**
Imagine you like to write on click handler for the button to check conditions, and in the handler you submit the form by jQuery.submit().
In this case in the line
`if (e.originalEvent.submitter !== undefined) {`
the script generates error, because e.originalEvent is not defined, and this prevent script to continue.
**Resolution**
Above line is replaced by
`if (e.originalEvent !== undefined && e.originalEvent.submitter !== undefined) {`
=> [OC 4.0 Master] Resolve undefined originalEvent on ajax form submit

upload/admin/view/template/setting/setting.twig
This PR removes a inconvenience in config settings, namely when the value is toggled between 0 and 1 with a checkbox, and the  checkbox is unchecked, in the oc_settings table is missing an entry with value 0.
**Issue**
In principle, in many cases there is no problem, except when the value is relied upon to be available. In general, this is a violation of backward compatibility with Opencart 3.
**Solution**
The solution is what is generally recommended in these cases, namely placing a hidden input with a value of 0 immediately before the checkbox inpu with value 1.
**Note**
I think this will improve the performance of the system and make it more stable.
If this PR is accepted, I can add the improvement to other places in the system where it occurs.
In the picture below you can see after …
=> [OC 4.0 Master] Admin Settings Checkboxes Unchecked Values

upload/catalog/view/template/common/footer.twig
Before, when including the scripts, it generated the error below:
```html
<script src="[<b>Warning</b>: Array to string conversion in <b>/var/www/html/system/storage/cache/template/a1/a18ed9f2bc607ccb53f3b90175ba5382.php</b> on line <b>206</b>Array](http://localhost/%3Cb%3EWarning%3C/b%3E:%20Array%20to%20string%20conversion%20in%20%3Cb%3E/var/www/html/system/storage/cache/template/a1/a18ed9f2bc607ccb53f3b90175ba5382.php%3C/b%3E%20on%20line%20%3Cb%3E206%3C/b%3EArray)" type="text/javascript"></script>
```
The error happens as Twig tries to print an array
=> fix: crash when listing scripts in footer

upload/catalog/controller/mail/order.php
currently when you add history to an order and select notify customer, the email that is sent out contains the back-end's url instead of the storefront url.
=> fix email url

upload/catalog/controller/checkout/register.php
Maybe we should use a different success message when a user has selected "Guest Checkout" while checking out, to avoid confusion. Because the message right now says "Success: Your account has been created!".
=> Use seperate success message for guest checkout

upload/admin/controller/marketplace/installer.php
Some libraries don't add slash at the end of directory when setting autoload (psr-4)
When generating the autoload.php file, OpenCart does not check and ends up generating a wrong path to the file.
**Monolog Composer**
```json
{
"name": "monolog/monolog",
...
"autoload": {
"psr-4": {"Monolog\\": "src/Monolog"}
}
}
```
**system/autoload.php with error (after extension install)**
```php
// monolog/monolog
$autoloader->register('Monolog', DIR_STORAGE . 'vendor/monolog/monolog/src/Monolog', true); // No slash at the end
```
**How should system/autoload.php be generated (after extension install)**
```php
// monolog/monolog
$autoloader->register('Monolog', DIR_STORAGE . 'vendor/monolog/monolog/src/Monolog/', true);
```
The extension below uses Monolog, when installing it you can check the error …
=> fix: add slash ("/") at the end of the directory when generating autoload

upload/admin/view/javascript/common.js, upload/catalog/view/javascript/common.js
Tooltips are shown in the bottom of a page when hovered second time. 
Added a fix destroying an old tooltip instance before showing.
First hover:
Second hover:
=> Bootstrap 5.2.1 fix tooltips

upload/admin/view/template/design/banner_form.twig
Editing or clearing an image from a existing banner row would not save correctly. Existing rows were missing the language id in the data-oc-target attribute on the edit/clear buttons causing a mismatch between them and the image input tag. The JavaScript to create additional rows already had the language id on them and would thus correctly save change done to them. Though they had slightly different id names that I normalized adding in the -image to the end of them like the existing ones for -title, -link, and -sort-order which both the existing and added rows have.
You can see this behavior if you open up an existing banner design and try changing or clearing an existing image. When saved if you refresh the previous image will still be set.
Steps to reproduce issue:
1. Navigate to …
=> Banner images don't update on existing rows

upload/install/controller/upgrade/upgrade_8.php
OC 3 won't have this field. If the store gets upgraded from OC-3, the extension field needs to be added accordingly since this is a mandatory field on the database.
=> Need to add the extension field - customer_payment - install/controller/upgrade/upgrade_8.php file

upload/admin/controller/sale/subscription.php
The subscription plan ID would be needed since #form-subscription allows selection of the subscription_plan_id in the select form.
=> Replaced editSubscriptionPlan parameters - admin/controller/sale/subscription.php file

upload/catalog/model/account/customer.php
model/checkout/cart indicates a float with the getBalance() method when using SUM(`amount`) AS the total
=> Changed from int to float - catalog/model/account/customer.php file

upload/admin/controller/sale/subscription.php
The subscription status ID from sale/subscription_info indicates an option value of: "" by default and requests to select a value. However, the serialized form submitted through AJAX does not validate on the target PHP controller/method if the subscription status ID has been selected or not. Therefore, the current code will only show a popup error message in regard to the ```$this->request->post['subscription_status_id']``` .
=> Added validation on subscription status ID - admin/controller/sale/subscription.php file

upload/admin/model/sale/subscription.php
catalog/model/account/customer also pulls the getTransactionTotal() method. Should access be restricted to see this information by subscriptions, user groups can be managed by authorized users. Besides, extensions can already managed the amount by service types which means that extensions can also restrict these information by their service amounts.
=> Adding getTransactionTotal to admin subscriptions - admin/model/sale/subscription.php file

upload/catalog/model/design/seo_url.php
Error: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens Error Code : HY093
SELECT * FROM `oc_seo_url` WHERE (`keyword` = :0 OR `keyword` LIKE '%/:1') AND `store_id` = '0' AND `language_id` = '1' in /app/system/library/db/pdo.php
=> Fix seo url PDO error

upload/admin/view/template/sale/order_info.twig
We are using the filter_data from the controller which means the description key from the order_products array does not contain the description key but rather the subscription key of the subscription_info['name] key . The values are, then, matched accordingly.
=> Fixed description array key - admin/view/template/sale/order_info.twig file

upload/catalog/model/checkout/subscription.php
catalog/model/checkout/order.php file - $order_product_id already returns a unique order product ID in the foreach loop. Therefore, it is impossible to have multiple identical order product IDs in the subscriptions for each $order_id that is also unique.
=> Removed multiple rows for order product ID - catalog/model/checkout/subscription.php file

upload/catalog/model/checkout/order.php
As per this issue commit's explanation: https://github.com/opencart/opencart/issues/11935 . As a solution, the charge() method in the cron/subscription needs to create a new order by extension prior to return the subscription_status_id. If active, the addTransaction() gets added based on this (which we already have in the cron/subscription). Therefore, to ensure that a new order gets created, we need to ensure the subscription is removed from the editOrder().
=> Removing subscriptions in editOrder() method - catalog/model/checkout/order.php file

upload/admin/view/template/mail/subscription_history.twig
The subscription ID should not be shown to the customer unless a URL is provided. Currently, a customer token is required to access that information. Therefore, minimal information should be provided to both parties.
=> Edited mail/subscription_history.twig file - admin/view/template/mail/subscription_history.twig file

upload/admin/model/sale/order.php
As per the title: When getting order options for an ordered product, keep the original sort order by order_option_id.
=> Keep order options sort order

upload/admin/model/tool/backup.php
For admin/model/tool/backup.php, method backup: Some fields can contain NULL value, which isn't compatible with string nor array!
=> bugfix backup / restore

upload/system/library/mail/smtp.php
If stream_socket_enable_crypto failed to negotiation encryption SMTP credentials could be sent unencrypted. Added a check to prevent this.
Also fixed the duplicate EHLO when STARTTLS isn't sent.
=> Check if encryption negotiation failed

upload/catalog/controller/api/sale/order.php
**Steps to check error**
1. Go to 'Admin->Sales->Order'
2. Click on 'Plus Button to add order'
3. Scroll down to 'Confirm Button and click it without selecting anything'
4. See error
**Expected behavior**
It will now display 1 line understandable error
=> Fixed admin order editor incorrect error display

upload/admin/model/catalog/category.php
Issue: Update sub-category URL using unescape wildcard underscore `WHERE `value` LIKE 'x_%'`.
Example: change to category_id `2` also changes all match path values `20`, `234_567`, `2xxx`, etc.
=> Fixed sub category URL update match all value start with old path

upload/admin/view/template/catalog/product.twig
The new AJAX filter breaks page location and browser behavior.
If you refresh a page or click browser Back button you will loose current product filter.
pushState changes current location address and adds it to browser history.
This should be done for all filtered admin lists like products, reviews, customers, customer approvals, seo urls, orders
=> Change page location on admin product filter

upload/catalog/language/en-gb/mail/forgotten.php
Without a leading space before "the" the word "The" ends up getting appended to the reset link resulting in users clicking on it and getting an "invalid reset link" message.
=> need leading space to prevent appending to link

upload/catalog/view/stylesheet/stylesheet.css, upload/catalog/view/template/product/thumb.twig
This PR adjusts the layout of `upload/catalog/view/template/product/thumb.twig`. In previous Opencart releases the product-thumb is cut off when it's content is over. Which this adjustment it will be equally sized across the entire store.
Examples:
Featured Old: 
Featured New:
Categories Old:
Categories New:
=> Improve flexbox to show button groups in product thumb

upload/extension/opencart/install.json
With an empty instruction, the extension parser has a bad time with the install.json and never loads. There needs to be another update to the opencart.ocmod as well, but I'm not sure what the policy is for outsiders proposing changes on zip files. When trying to upload the opencart.ocmod.zip, the error_install message is returned (Warning: Could not find install.json)
=> empty instruction on the default extensions causes a bad time

upload/catalog/controller/startup/session.php
Now we have different samesite, one from the config file and another from site settings. At many points we get $config->get('session samesite'), then we get the value from the config file and not from the settings. It needs to be fixed.
=> Fix session_samesite

upload/system/config/admin.php
A small addition to my PR #12465
Since the translation event is not used on the admin side, it must be removed from the configuration.
=> fix #12465 Removed unused event

upload/catalog/controller/common/language.php
Need to set config_language_id before each $this->url->link() in the language loop, becuase $this->model_design_seo_url->getSeoUrlByKeyValue use config_language_id
=> Correct multilingual SEO URLs in the catalog language switcher

upload/admin/controller/sale/order.php
This PR is to fix the Fraud Order Tab naming issue to use the Fraud Extension name instead of the output.
Screenshot of the issue:
Screenshot of the order details page after the fixes:
=> Update admin/controller/sale/order.php to fix Fraud Order Tab issue

upload/extension/opencart/admin/language/en-gb/currency/fixer.php, upload/extension/opencart/admin/view/template/currency/fixer.twig
The Fixer module in the settings has an incorrect warning that this service requires the Euro currency.
In fact, the Fixer does not require this and the warning should be removed.
=> Removed Euro requirement

upload/catalog/controller/product/product.php
PHP 8.2
Fatal error: A function with return type must return a value (did you mean "return null;" instead of "return;"?) in \catalog\controller\product\product.php on line 522
=> Fix product controller

upload/admin/model/localisation/zone.php
Even if the zone status is 'Disabled', the zone list still shows the status 'Enabled'
=> Fix Zone list - status always "Enabled"

upload/admin/view/javascript/ckeditor/config.js
Here is an alternate ShowBlocks config.
It disables ShowBlocks by default and adds ShowBlocks toolbar switch. 
https://github.com/opencart/opencart/issues/12692
In my opinion Blocks should be always visible. It does nothing to the source code but allows you to control the HTML structure better. It's just a matter of habit.
=> CKEditor ShowBlocks alternate config

upload/catalog/controller/account/returns.php
The ID in the captcha extensions search is  `returns`, not `return`. Anti-spam validation does not work on the Returns page due to this error.
=> Fix anti-spam validate in the Returns page

upload/admin/view/stylesheet/stylesheet.css, upload/admin/view/template/catalog/product.twig, upload/admin/view/template/catalog/review.twig, upload/admin/view/template/cms/comment.twig, upload/admin/view/template/customer/customer.twig, upload/admin/view/template/customer/customer_approval.twig, upload/admin/view/template/customer/gdpr.twig, upload/admin/view/template/design/seo_url.twig, upload/admin/view/template/localisation/country.twig, upload/admin/view/template/localisation/zone.twig, upload/admin/view/template/marketing/affiliate.twig, upload/admin/view/template/marketing/marketing.twig, upload/admin/view/template/report/online.twig, upload/admin/view/template/sale/order.twig, upload/admin/view/template/sale/returns.twig, upload/admin/view/template/sale/subscription.twig, upload/admin/view/template/tool/upload.twig
Make right filter sticky when scrolling a page.
Very useful if you have set more then 10 items per page in admin area.
Also lists look more aesthetically pleasing now without empty space in the right column.
=> Sticky admin filters

upload/system/library/session/redis.php
This isn't strictly causing any issues but it's best to have all utilized properties declared as that gives an opportunity to set there viability and type which can help to catch issues with the code that accesses it.
It was probably intended to be private, but I have set it to public to keep comparability with prior versions.
=> Add missing prefix property to redis session class

upload/system/library/template/twig.php
This line was not properly updated when the system was updated from Twig 2.4 to 3.0: https://github.com/opencart/opencart/commit/ba5509e986cf4c05e9df8e0111b5839bfdb3582c
=> Fix leftover from Twig 2.4 to 3.0 migrating

upload/catalog/model/cms/article.php
This one appears to have been an issue since the functions introduction in https://github.com/opencart/opencart/commit/aaae7efc3b83da5b550e17a88c1dd84df781191f
=> Fix getTotalArticles() not accepting the given filter

upload/admin/model/sale/subscription.php
You cannot append to a new element on an array.
This one can be traced all the way back to the release of 2.2 when it was changed from a string to and array: https://github.com/opencart/opencart/commit/9e0b04f153b8803cfc8d98bf9b351a0dda5ed5e6
=> Fix bad array push

upload/catalog/controller/cron/subscription.php
This was introduced with https://github.com/opencart/opencart/commit/66fa3b1693f4b91fc1cd4c3505addc3b8322f27d
=> Fix missing $order_info in subscription cron

upload/extension/opencart/catalog/controller/module/store.php
This one sort of goes all the way back to https://github.com/opencart/opencart/commit/60827089ecea70dc599f830e0f4f87cabc0113d3 but probably didn't become a real issue before the return types where added in 4.0.0
=> Correct catalog store return value when locked

upload/admin/model/sale/order.php
As there is no way to feed the $data array to the function this code can never be activated. Also it does not look to have been and omission as the call site has no trace of filter variables that would fit here.
The offending code was introduced in this commit which also does not appear to have intended for it usage: https://github.com/opencart/opencart/commit/e49531f95b7a1d5b66001fb4530b938a43ee420e
=> Remove dead code from getTotalProductsByProductId

upload/system/library/mail.php
PHP 7.4 does not support union type but we can add it to the phpdoc instead.
=> Fixed PHP 7.4 warning for mail library

upload/system/library/cache/apcu.php
PHP 7.4 does not support union types, but we still have it in the phpdoc above
=> Fixed PHP 7.4 warning for apcu

upload/system/library/db/pdo.php
Union type is not supported, but we can use nullable to express the same type in 7.4 syntax
=> Fixed PHP 7.4 warning for PDO

upload/system/library/db/pgsql.php
The return type of [pg_connect() was changed](https://www.php.net/manual/en/function.pg-connect.php) in 8.1 and 7.4 does not support union type so this has to be left to the phpdoc
=> Fixed PHP 7.4 warning for postgreSQL

upload/admin/controller/marketplace/modification.php
The namespace was omitted when this code was added in https://github.com/opencart/opencart/commit/0da669409629a3aca01aefe40c49765b34eb9491, this appears to have been missed when fixes from https://github.com/opencart/opencart/pull/12898 where copied in https://github.com/opencart/opencart/commit/18ec814086ed5603791f87258e30d0429ffbc86b
=> Fix namespace errors in marketplace modification admin controller

.github/workflows/Lint.yml, README.md
This adds a GitHub action that checks to see if the code can be parsed by all the supported versions of PHP (7.4, 8.0, 8.1, and 8.2).
An example of what this looks like in a Pull Request:
This should help with the review process as developers get instant feedback of potential issues with there code.
Clicking details next to the failing test will also give you details regarding the errors that where found in various files.
Also it updates to badge in the read me to say that `PHP >= 7.4` rather then `PHP >= 8.0` to better clarify things.
=> Check that code passes for supported versions of PHP

upload/admin/controller/sale/subscription.php
This code was commented out in https://github.com/opencart/opencart/commit/66fa3b1693f4b91fc1cd4c3505addc3b8322f27d which causes subsequent conditions to fail as $product_info hasn't been populated. No clear reason is given to I'm assuming this was just a left over from local debugging.
=> Fix getting product info in subscription data

upload/catalog/view/template/account/account.twig, upload/catalog/view/template/cms/blog_info.twig, upload/catalog/view/template/cms/blog_list.twig, upload/catalog/view/template/product/category.twig, upload/catalog/view/template/product/manufacturer_info.twig, upload/catalog/view/template/product/special.twig
Frontend pages must have H1 tag.
Not sure about account.twig, but it looks good. H1 there is both page and list heading. All other account templates have this tag.
=> Frontend H1 page tags

upload/admin/controller/common/security.php
I think the '[^a-zA-z0-9_]' is meant to be '/[^a-zA-Z0-9_]/' that is, if not  letter, digit, or underscore.
And the '[^a-zA-z0-9_\:\/]' should be '/[^a-zA-Z0-9_\:\/]/' that is, if not letter, digit, underscore, colon, or forward-slash.
=> fix preg_replace calls

upload/extension/ocmod/system/engine/loader.php, upload/system/engine/controller.php, upload/system/engine/loader.php, upload/system/engine/model.php, upload/system/engine/registry.php
This enables IDEs and other tools to resolve properties in 22,169 instances where they previously couldn't understand the context of the object. As a result, it provides more accurate feedback and improves autocompletion. Depending on your IDE, this should significantly ease the development of both the system itself and extensions.
=> Hint classes being resolved during framework bootup

upload/admin/controller/common/filemanager.php
The invalid code was introduced in https://github.com/opencart/opencart/commit/4cb541e3ca1c51b6d17bbf1321cbba2916db96a3
=> Fix invalid regex in filemanager

upload/admin/controller/extension/dashboard.php, upload/admin/controller/extension/feed.php
The property was removed in https://github.com/opencart/opencart/commit/992411d0eedb937cfb58249ce35ea98c9e6180aa but remains in use in the validation function.
=> Add missing error property

upload/extension/oc_payment_example/admin/controller/payment/credit_card.php
This was introduced here when the class was added: https://github.com/opencart/opencart/commit/3df3ec018e376ec07dcc668a4fd25999a12e50b5
=> Fix misspelled property in example extension

upload/admin/controller/startup/notification.php
The wrong property name was used and the model was never loaded. This looks to have been introduced in https://github.com/opencart/opencart/commit/08be346a14e107b71e6fb62d3cc42208a35f456f
=> Correct loading of notification model

upload/system/engine/action.php
Fix error on PHP 8:
PHP Unknown:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /system/engine/action.php on line 65
=> PHP 8 - null parameter

.github/workflows/Lint.yml, phpstan.neon
All issues related to unknown classes/functions/variables have now been fixed. and OpenCart can pass a [PHPStan](https://phpstan.org/) scan at level 0 (the simplest level).
This pull request improves the GitHub Action to include a PHPStan scans when developer submit a Pull Request, ensuring that new code does not have any such issues.
Developers can also use PHPStan on there own computers, to find and fix issues.
=> Check for missing symbols in code with GitHub Action

upload/catalog/controller/startup/seo_url.php
Fix issue #12228 
Test cases to check the code changes:
1. https://domain.com => Home Page
2. https://domain.com/en-gb => Home Page
3. https://domain.com/index.php?route=checkout/cart.add&language=en-gb => Add Product to Cart
4. https://domain.com/en-gb?route=common/cart.removeProduct => Remove Product from Cart
5. https://domain.com/404qwerty or any page which is not exist => 404 Page
=> 404 page recognition fix

upload/catalog/view/template/information/sitemap.twig
Incorrect link to the Cart in the Site Map page.
I have submitted this issue before and it was closed without a fix.
=> Fix the cart url in the Sitemap page

upload/system/library/cart/cart.php
https://github.com/opencart/opencart/blob/1be6112ad2a522ac9f3d6fa36c8888173b82175c/upload/system/library/cart/cart.php#L398
Basically this line means `$this->data = $this->data;` and it has no sense without clearing `data` property.
If you try to `add/update` cart and then call `getProducts` in one request you cannot see your updates cause results are returned from outdated `data` property.
=> Clear cart data on update

upload/admin/controller/event/language.php, upload/admin/controller/localisation/return_action.php
This was done using php-cs-fixer's no_blank_lines_after_class_opening rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Remove blank line after class decleration

upload/admin/controller/event/modification.php
This was done using php-cs-fixer's void_return rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Apply missing void return

upload/admin/controller/common/security.php
This was done using php-cs-fixer's binary_operator_spaces rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Correct spaces around comparisons

upload/admin/controller/marketplace/modification.php, upload/admin/model/localisation/location.php, upload/catalog/controller/checkout/cart.php
This was done using php-cs-fixer's statement_indentation rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Correct indentation of statments

upload/admin/model/localisation/return_status.php
This was done using php-cs-fixer's return_type_declaration rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Correct position of return type declaration

upload/admin/controller/sale/voucher.php, upload/cron.php, upload/system/framework.php, upload/system/library/db/pgsql.php, upload/system/library/session/redis.php
This fixes all instances of where the opening braces have not been positioned correctly. This was done using php-cs-fixer's braces_position rule. Once all oustanding PR regarding code formatting have been merged this process can be automated.
=> Correct placment of opening braces

upload/admin/controller/common/filemanager.php, upload/admin/controller/extension/captcha.php, upload/admin/controller/localisation/country.php, upload/admin/controller/localisation/tax_rate.php, upload/admin/controller/marketplace/marketplace.php, upload/admin/controller/sale/subscription.php, upload/admin/model/catalog/attribute.php, upload/admin/model/catalog/attribute_group.php, upload/admin/model/customer/customer.php, upload/admin/model/setting/event.php
This was done using php-cs-fixer's indentation_type rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Fix incorrect indentation in admin

upload/install/cli_install.php, upload/install/controller/upgrade/upgrade_5.php, upload/install/controller/upgrade/upgrade_8.php, upload/system/config/admin.php, upload/system/engine/controller.php, upload/system/engine/event.php, upload/system/engine/factory.php, upload/system/engine/loader.php, upload/system/engine/model.php, upload/system/engine/registry.php
This was done using php-cs-fixer's indentation_type rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Fix incorrect indentation in base

upload/extension/opencart/admin/controller/report/subscription.php, upload/extension/opencart/admin/model/report/subscription.php, upload/extension/opencart/catalog/controller/module/bestseller.php, upload/extension/opencart/catalog/controller/module/blog.php
This was done using php-cs-fixer's indentation_type rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Fix incorrect indentation in extensions

upload/catalog/controller/account/returns.php, upload/catalog/controller/api/account/login.php, upload/catalog/controller/cms/comment.php, upload/catalog/controller/product/category.php, upload/catalog/controller/product/manufacturer.php, upload/catalog/controller/product/special.php, upload/catalog/model/account/subscription.php
This was done using php-cs-fixer's indentation_type rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Fix incorrect indentation in catalog

upload/system/library/mail/smtp.php
The function names used here where aliases and not the real function names. This was done using php-cs-fixer's no_alias_functions rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Use real function names

upload/catalog/controller/account/download.php, upload/catalog/controller/account/login.php, upload/catalog/controller/account/order.php, upload/catalog/controller/event/activity.php, upload/catalog/controller/event/statistics.php, upload/catalog/controller/startup/error.php, upload/catalog/controller/startup/event.php, upload/catalog/controller/startup/language.php, upload/catalog/model/design/layout.php, upload/catalog/model/localisation/order_status.php, upload/catalog/model/setting/module.php, upload/catalog/model/tool/image.php
=> Remove trailing whitespace from empty lines in catalog

upload/install/cli_install.php, upload/install/controller/common/footer.php, upload/install/controller/common/header.php, upload/install/controller/error/not_found.php, upload/install/controller/install/step_3.php, upload/install/controller/startup/database.php, upload/install/controller/upgrade/upgrade_5.php, upload/install/controller/upgrade/upgrade_8.php, upload/install/model/install/install.php
=> Remove trailing whitespace from empty lines in installer

upload/extension/opencart/admin/controller/dashboard/customer.php, upload/extension/opencart/admin/controller/dashboard/order.php, upload/extension/opencart/admin/controller/dashboard/recent.php, upload/extension/opencart/admin/controller/module/banner.php, upload/extension/opencart/admin/controller/module/bestseller.php, upload/extension/opencart/admin/controller/module/featured.php, upload/extension/opencart/admin/controller/module/html.php, upload/extension/opencart/admin/controller/module/latest.php, upload/extension/opencart/admin/controller/module/special.php, upload/extension/opencart/admin/controller/payment/bank_transfer.php, upload/extension/opencart/admin/controller/report/subscription.php, upload/extension/opencart/admin/model/report/subscription.php
=> Remove trailing whitespace from empty lines in extensions

upload/admin/controller/catalog/review.php, upload/admin/controller/common/developer.php, upload/admin/controller/customer/customer_approval.php, upload/admin/controller/design/banner.php, upload/admin/controller/error/not_found.php, upload/admin/controller/event/debug.php, upload/admin/controller/localisation/language.php, upload/admin/controller/localisation/location.php, upload/admin/controller/localisation/tax_class.php, upload/admin/controller/mail/returns.php, upload/admin/controller/mail/transaction.php, upload/admin/controller/marketplace/api.php, upload/admin/controller/marketplace/marketplace.php, upload/admin/controller/report/online.php, upload/admin/controller/report/statistics.php, upload/admin/controller/sale/voucher.php, upload/admin/controller/startup/application.php, upload/admin/controller/startup/event.php, upload/admin/controller/tool/log.php, upload/admin/controller/tool/notification.php, upload/admin/model/localisation/return_reason.php, upload/admin/model/tool/image.php, upload/admin/model/user/user_group.php
=> Remove trailing whitespace from empty lines in admin

upload/admin/controller/common/developer.php, upload/admin/controller/event/statistics.php, upload/catalog/controller/event/debug.php, upload/system/library/cache.php, upload/system/library/cache/apcu.php, upload/system/library/cache/redis.php, upload/system/library/document.php, upload/system/library/url.php
This was done using php-cs-fixer's no_trailing_whitespace_in_comment rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Remove trailing whitespace in comments

upload/admin/controller/common/developer.php, upload/admin/controller/customer/customer_approval.php, upload/admin/controller/event/debug.php, upload/admin/controller/mail/transaction.php, upload/admin/controller/marketplace/api.php, upload/admin/controller/sale/voucher.php, upload/admin/model/catalog/attribute.php, upload/catalog/controller/event/activity.php, upload/catalog/controller/event/statistics.php, upload/catalog/controller/event/translation.php, upload/catalog/model/report/statistics.php, upload/catalog/model/setting/module.php, upload/catalog/model/setting/setting.php, upload/extension/opencart/catalog/controller/module/category.php, upload/install/controller/install/step_3.php, upload/install/controller/upgrade/upgrade_8.php, upload/system/engine/autoloader.php, upload/system/engine/event.php
This was done using php-cs-fixer's no_trailing_whitespace rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.
=> Remove trailing whitespace in code

upload/catalog/controller/product/category.php
Also in manufacturer.php, special.php, cms/blog.php 
But I think we should ditch the redundant code as Google [no longer uses](https://developers.google.com/search/docs/specialty/ecommerce/pagination-and-incremental-page-loading?hl=en&sjid=7744963422977639390-EU#:~:text=Google%20no%20longer%20uses%20these%20tags) the `rel="next"` and `rel="prev"` tags.
=> Broken URL in code comments

.php-cs-fixer.php, upload/admin/controller/marketing/contact.php, upload/admin/controller/startup/error.php, upload/admin/controller/tool/upload.php, upload/catalog/controller/account/download.php, upload/catalog/model/catalog/product.php
When the first and secound part of a ternary are the same the secound can be omitted, this can help avoid mistakes where one is miss typed and also makes for less code to go over when reading it.
=> Simplify use of ternary statments

upload/catalog/controller/account/order.php
This function does not take any arguments, but both `info()` and `getHistory()` resolves the order id in the same way which is why this hasn't resulted in any errors so fare. Removing it to avoid confusion, the alternative is to change `getHistory()` to accept order id as an argument, but that would require some refactoring.
This issue has existed in various forms since https://github.com/opencart/opencart/commit/e75532d9f3b17647fbbbb6f918bc108e5900bff4
=> Correct call to getHistory in order controller

upload/system/engine/factory.php
From what I can see this has no known meaning, was it supposed to be something else?
It was added in https://github.com/opencart/opencart/commit/eaa91609e10158802a5d67ed369d72aced6f16fb
=> Remove unknown notation

upload/system/library/mail/smtp.php
Since the previous line throws an exception this is not reachable. This has been the case since https://github.com/opencart/opencart/commit/0b5119515fa1350ebf214cc9aa1ac5ae83f79ce5
=> Remove unreacable code

upload/system/library/db/pdo.php
`$statement->closeCursor();` was never reached since both branches of the previous statement returned from the function.
Additionally `return false` was not reachable since at that point the function will either have returned or thrown an exception.
This issue was introduced in https://github.com/opencart/opencart/commit/657a55d0d7ddecb5d2e24cc815d1baa864cd29eb
Also I corrected the return type and made `isConnected()` do an explicit check on the connection.
=> Correctly close the statment after use

upload/catalog/controller/checkout/voucher.php, upload/catalog/controller/common/cart.php, upload/catalog/language/en-gb/checkout/voucher.php, upload/catalog/model/checkout/cart.php
In 4.0.2.3, you're unable to remove gift vouchers from the shopping cart.
This PR implements the changes proposed in #13090 to fix this.
=> Fix removing gift vouchers from cart

upload/admin/controller/marketplace/modification.php
Since $modification is initialized as an array it is always defined and never null, as such the code can be simplified to a single copy assignment, unless something else was intended? 
This looks to have been introduced when the class was originally created in dcc597d1c61652dcdf47eac3de4e2dbf1900bd7d
=> Remove redundant code

upload/system/library/template/template.php
File is always set and will always have some string value.
Introduced in https://github.com/opencart/opencart/commit/78306cc026505023cd6437faef1a092e31214f7d
=> Remove redundant check on filename

upload/system/library/db/pdo.php, upload/system/library/db/pgsql.php
The SSL arguments are never actually used inside the function, removing them doesn't affect comparability as PHP will silently ignore additional augments in invocations.
Intorudced here: https://github.com/opencart/opencart/commit/671d16272e397471e65f1d6a3748197d1953d3bd
=> Remove unused arguments

upload/system/library/db/mysqli.php
`mysqli_init()` returns `false` on error, which is not accepted by the property, swap it for `null` instead.
Introduced here: https://github.com/opencart/opencart/commit/671d16272e397471e65f1d6a3748197d1953d3bd
=> Avoid type error when MySQL connection fails

upload/system/library/image.php
Filename can be false (on error) or null (when uninitialized), simply return null in that case instead of throwing a type error.
This was previously improperly fixed here: https://github.com/opencart/opencart/commit/da308c65667e52583e0a257ba2c9410b6dd8e417
=> Fix type error when getting unitialized image

upload/system/library/session/db.php
This is the same as https://github.com/opencart/opencart/pull/9633 that was never applied to the 3.0.x.x branch. Should fix https://github.com/opencart/opencart/issues/9237 that prenvented admin login when the timezone was a negative value. However, it won't fix the issue a negative value causes with the API https://github.com/opencart/opencart/issues/9492. That would require a change in the API session code or a change in the startup order.
=> Fix for timezone change breaking session expiration

upload/admin/controller/customer/address.php
This does not take other argument then the id:
https://github.com/opencart/opencart/blob/3c766c228374b00918e63725c3aa1892b93acafa/upload/admin/model/customer/customer.php#L69
Introduced here: https://github.com/opencart/opencart/commit/f8d602951dd37c2ce74e4d002fb4964e3dfb716c
=> Remove unused argument from deleteAddress()

upload/admin/controller/sale/subscription.php, upload/catalog/controller/account/order.php
Neither `getOrdersBySubscriptionId()` nor `getHistories()` accepts arguments for paging there data. This likely means that the UI for this is broken, so a more proper solution would likely be to either implement support for this, or fully remove the paging variables and possibly update the UI. 
Introduced here: https://github.com/opencart/opencart/commit/efbc1d44ead5c7c6eefbd3bcc6a8bed051495f1c and here https://github.com/opencart/opencart/commit/c6bf54bbd8dbb5c4fdacf8b7bc47da66ded49567
=> Remove broken pagination arguments

upload/admin/controller/extension/module.php
`addModule()` takes a data array as the second argument, not a title.
https://github.com/opencart/opencart/blob/3f42879ced0f65ac16b0cc80b3402cfc46246e93/upload/admin/model/setting/module.php#L15
This issue was introduced in https://github.com/opencart/opencart/commit/0ce03aab7e9c19457805b7f91483be70d6d09a29
=> Correct call to addModule() in extension module

upload/admin/controller/marketplace/modification.php, upload/extension/opencart/catalog/model/total/reward.php
Determining the data type early one ensure we don't have any incorrect usage later in the code. Also this saves us the need for manually converting empty string to 0.
This could potential give hard to debug errors on none expected input, instead it is halted early with an error regarding the none well formed numerics.
=> Cast input type early

upload/admin/controller/design/translation.php
`Translation::addTranslation()` does not return the translation_id of the new translation. It has a void return and the value would then always be set to `null`.
Alternatively this could be fixed by letting `Translation::addTranslation()` actually return the new row id, maybe something in the other end is dependent on it :shrug: 
Introduced in https://github.com/opencart/opencart/commit/1cadd3c691c8a5da6ae4152fa68bfe7b5ef20a8f
=> Remove incorrect use of return value

upload/admin/controller/marketplace/cron.php
This does not take an id:
https://github.com/opencart/opencart/blob/3c766c228374b00918e63725c3aa1892b93acafa/upload/system/library/session.php#L108
Issue was introduced here: https://github.com/opencart/opencart/commit/bb5c6606b1d7c20e13c05e60b15cb466e6504667
=> Remove unused argument for Session::destroy()

upload/admin/controller/tool/backup.php
There is no need to track `$start` and `$sql` individually as there state is always following the condition of the first check, which also is not affected by any in-between operations.
This avoid a bit of string copying which should help performance a some.
Introduced in https://github.com/opencart/opencart/commit/8a17e05e4f1f3b1b0f005b956efc9cfd166a3bd2
=> Clean up Backup::restore()

upload/admin/model/localisation/order_status.php, upload/admin/model/localisation/return_reason.php, upload/admin/model/localisation/return_status.php, upload/admin/model/localisation/stock_status.php, upload/admin/model/localisation/subscription_status.php
These functions would return an uninitialized variable if the given data does not contain any language elements.
This would result in a `TypeError` exception. This PR changes things so that the variable is null initialized and permit a null return from the functions.
This issue was introduced in 55edabfedb3e9854098973b4f7dd8f87629b8fbe and https://github.com/opencart/opencart/commit/c2640263dd4ecb0074b2cde85df2a385f7b0dfa8
=> Correct return value of localization functions

upload/admin/controller/mail/subscription.php
It appears this was missed when changing the format in https://github.com/opencart/opencart/commit/613b29f352a22e8a9ef5c16bae4fe38b7b70d01d
=> Fix mail configuration for subcription

upload/admin/controller/customer/customer.php, upload/admin/controller/mail/subscription.php, upload/admin/controller/sale/subscription.php, upload/admin/model/sale/subscription.php, upload/catalog/controller/cron/subscription.php, upload/catalog/controller/mail/subscription.php
`upload/admin/controller/sale/subscription.php` had an inverted case on line 791 meaning it never loaded the subscription data. This was introduced here: https://github.com/opencart/opencart/commit/e586908b1b17899d62133a13e65b95017e22e053
In `upload/catalog/controller/cron/subscription.php` the editDateNext() is called on a model that does not implement it looks to have been introduced in https://github.com/opencart/opencart/commit/0da669409629a3aca01aefe40c49765b34eb9491
`upload/admin/controller/sale/subscription.php`, `upload/catalog/controller/mail/subscription.php`, `upload/admin/controller/mail/subscription.php` and `upload/admin/controller/customer/customer.php` appears to have been broken since https://github.com/opencart/opencart/commit/23e7072059f9bf2987ec82e204be721a0caba257 and …
=> Fix loading subscription data

upload/system/library/db/pdo.php
The native return type is a string, cast it to `int`. Additionally when nothing was inserted it will return `false`, swap it for `null` and correct return type.
Introduced in https://github.com/opencart/opencart/commit/977710c5ba995d49261f20273e971482c584970b
=> Correct getLastId() return value

upload/catalog/model/account/subscription.php
These methods are used here:
https://github.com/opencart/opencart/blob/549381fe854cfd43baf1b1522e52a3e00734ad39/upload/catalog/controller/cron/subscription.php#L391
But where not implemented on the correct model, copied from `Opencart\Admin\Model\Sale\Subscription`.
=> Copy missing edit functions for catalog account subscription model

upload/system/library/cart/currency.php
If $format is set to false the function will return the value in a float form. Issue introduced in 977710c5ba995d49261f20273e971482c584970b
=> Correct return type for format()

upload/system/engine/proxy.php
`Ref` does not exist ([and it doesn't appear it ever did](https://github.com/opencart/opencart/commits/master/upload/system/engine/ref.php)) so checking for it is pointless.
The check was originally added here: https://github.com/opencart/opencart/commit/248bf46d897385bd6de70404fa37d3a6a2857453
Then got changed to `Reference` in OC4, with comments about being broken from other devs:
https://github.com/opencart/opencart/commit/bca8e10322475bf3fc9c9b4ffa8d7c3f680b2413
`Reference` then got added here: https://github.com/opencart/opencart/commit/fe0b6910c5a2fd2ab1f2980faf3196b56f7cb853
Then fully removed here: https://github.com/opencart/opencart/commit/c705bc46fc48922c3154b6f07f1ae9a5ca9753c9
=> [3.0.x.x] Remove Ref check from proxy.php

upload/admin/controller/customer/customer.php, upload/admin/controller/user/user.php
`getAuthorize()` doesn't exist, use `getAuthorizes()`. Correct use of the array was detected after applying https://github.com/opencart/opencart/pull/13428 locally.
Issue introduced in https://github.com/opencart/opencart/commit/bdc79c4db07f170c1a41add4566cfe2c0f529f20 and https://github.com/opencart/opencart/commit/56f257e024d4ee54f6e8b9ec8b776a1ab082c67a
=> Fix deleteAuthorize()

upload/admin/controller/startup/error.php, upload/catalog/controller/startup/error.php, upload/cron.php, upload/install/cli_cloud.php, upload/install/cli_install.php, upload/system/framework.php
The 5th parameter was deprecated in PHP 7.2 and is unused by OC. Since it does not have a default this will also cause an error in 8.0+: https://www.php.net/manual/en/function.set-error-handler.php
=> Fix error handeling for PHP 8.0+

docker-compose.yml, tools/Dockerfile
This fully automates the process of setting up a developer environment for testing for OC, the only requirement is that you have [Docker Compose](https://docs.docker.com/compose/install/) installed.
You will then be able to start the shop by either pressing play in Docker Desktop (or you IDE if it supports it), or by running this command `docker-compose up`.
The setup also provides a redis, memcached, and postgres server for anyone wanting to test with them.
You can use [docker-compose.override.yml](https://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html) to change versions of various services as well to test things on PHP 7.4 and MySQL 8.0 etc
=> Docker Compose based developer environment

upload/system/library/log.php
With commit [https://github.com/opencart/opencart/commit/6440e653694b92da4c3fa7ead794bd915f6995ec](https://github.com/opencart/opencart/commit/6440e653694b92da4c3fa7ead794bd915f6995ec) made on Oct 14, 2023,  
`$this->log->write()` method no longer support _'array'_
However, it is required to add error log with **arrays** also.
so replaced 'string' type with 'mixed' type for `write()` method, so as it can support string as well as array
=> Update log.php (Replaced string with mixed to accept array)

upload/extension/opencart/catalog/model/payment/opayo.php
The signature of `calculateSchedule()` was was causing `$next_payment` to be cast to a string which was worked around with some string parsing, but the function would still fail when trying to call `->modify()` and so would any function that tried to use the return value.
Also `$cycle` should have been an `int` and not a string.
=> Fix Opayo::calculateSchedule()

upload/extension/opencart/admin/controller/currency/ecb.php, upload/extension/opencart/catalog/controller/currency/ecb.php
The check would always trigger as the table would always contain `EUR => 1`, instead only run the conversion if more then one currency conversion is known.
=> Only process currencies if there are more then one

upload/system/library/db/pdo.php
If creating the PDO object fails an exception will be emitted and the code will never reach this section so there is no need to check if the PDO object exists.
=> Remove redundant check for pdo

upload/system/library/session.php
$registry is not nullable so will always be provided, no need to check if it was.
=> Remove redundant check for registry

upload/admin/controller/common/login.php
This section is already guarded by a `isset($this->request->get['route'])` check, so this will always be true.
=> Remove redundant check on request->get

upload/admin/model/sale/order.php, upload/catalog/model/cms/article.php
The result of explode() is always true as even empty values will result in at least once string pice
`explode(',', null) === [''] == true`
But we can use array_filter() to remove empty elements which would result in an empty array instead and have the later operations and checks on the result behave as intended.
=> Filter empty result from explode()

upload/system/library/db/pdo.php
It's not possible to suppress errors on construct like `new`, and there isn't really an error that it will emit either
https://www.php.net/manual/en/language.operators.errorcontrol.php
https://www.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.new
=> Remove inoperable error suppresion

upload/extension/opencart/admin/controller/total/tax.php
This is never used in the class, and cannot be reached from outside.
=> Remove unused property from Tax

upload/system/library/image.php
Emit an exception if `watermark()` is being used incorrectly, previously it would have acted the same as if `topleft` had been selected, possibly with error notices in the output, which may have broken the image if sent directly to the output.
=> Emmit error on unknown position

upload/system/engine/controller.php, upload/system/engine/model.php, upload/system/engine/proxy.php, upload/system/engine/registry.php
This lets PHPStan better reason about object relations in OC.
This works by using `@mixin`to document that the `Controller`, `Model`, and `Proxy` class has magic properties where for any none local will fetch them from the `Registry`, and there for allows calling it's properties directly on them.
And of cause document the classes that are commonly loaded into the registry during startup.
=> [3.0.x.x] Hint classes loaded during framework bootup

upload/system/library/session.php
gc() does not take an id
https://github.com/opencart/opencart/blob/393fe7019d4695e8cbc202c923393f5b03a28035/upload/system/library/session/file.php#L71
=> Remove unused argument

upload/system/engine/autoloader.php
This makes sure that the signature matches the expectation
=> Use a closure when assining the autoloader

upload/catalog/view/template/account/returns_form.twig
Remove space from the breadcrumb line in order to be the same with the other .twig files in account folder.
=> Remove space from returns_form.twig

phpstan.neon, upload/admin/controller/extension/extension/advertise.php, upload/admin/controller/extension/extension/analytics.php, upload/admin/controller/extension/extension/captcha.php, upload/admin/controller/extension/extension/currency.php, upload/admin/controller/extension/extension/dashboard.php, upload/admin/controller/extension/extension/feed.php, upload/admin/controller/extension/extension/fraud.php, upload/admin/controller/extension/extension/menu.php, upload/admin/controller/extension/extension/module.php, upload/admin/controller/extension/extension/payment.php, upload/admin/controller/extension/extension/report.php, upload/admin/controller/extension/extension/shipping.php, upload/admin/controller/extension/extension/theme.php, upload/admin/controller/extension/extension/total.php, upload/admin/model/user/user_group.php
When an extension gets uninstalled, the access/modify permissions are now removed from the oc_user_group DB table, too.
=> extensions uninstall fixes: remove permissions, + fixes for phpstan.neon

upload/catalog/model/localisation/currency.php
currency_id should not be escaped but casted instead, because it is supposed to always be an integrer.
=> currency_id wrongly escaped in getCurrency method

upload/admin/view/javascript/ckeditor/config.js
Remove version warning. 4.22.1 is the last free opensource version.
This annoying message have no relation to security.
=> CKEditor disable version check

upload/system/framework.php
Still regular posts on the forum with issues cause by lack of cache control headers, which have never been added to 3.0.x.x.
Use header instead of $response->addHeader to prevent redirects being cached. Which can be a problem on hosting with an ExpiresDefault set. A better way would be to modify the response library to include headers on redirects and only send when a session is started.
Also probably needed to comply with data protection regulations.
=> [3.0.x.x] Add cache control headers

upload/system/library/db/mysqli.php
real_connect() expects the port to be an int and not a string.
=> Correct port type for mysqli

upload/system/library/mail/mail.php, upload/system/library/mail/smtp.php
md5() expects a string, time() returns an int.
=> Correct type of arguments given to md5

upload/extension/opencart/catalog/controller/captcha/basic.php
mt_rand() will always return an int so nothing to rund: https://www.php.net/manual/en/function.mt-rand.php
=> Remove redundant ceil() calls

upload/system/library/image.php
This code was wrong and would always result in true:
`('image/png' != 'image/png' || 'image/png' != 'image/webp')`
There is no value you can set `$this->mime` to that would ever result in the expression evaluating to false since it will always be unequal the first or second value.
=> Fix check for image type

upload/admin/model/extension/payment/opayo.php, upload/catalog/model/extension/payment/worldpay.php
@mhcwebdesign nice progress on the PHPStan issues. This PR should make the branch pass the check fully.
The reason it's failing is that there are multiple classes with the same name and namespace, coatning method with the same name but different signatures.
This is just a proposed solution, idk if you prefer to solve it by renaming them or some other way.
=> [3.0.x.x] Make identically identified functions have the same signature

upload/install/controller/upgrade/upgrade_3.php
$result['Key_name'] is gathered in the previous step, so this would only evaluate correctly if there is only one key and it is the last result.
=> Fix dropping primary key when upgrading

upload/system/library/db/pgsql.php
There isn't a proper context to give `pg_result_error()` when `pg_query()` fails, see https://www.php.net/manual/en/function.pg-result-error.php
=> Fix getting error messages for pgsql

upload/admin/controller/catalog/download.php, upload/admin/controller/tool/backup.php, upload/admin/controller/tool/upload.php, upload/catalog/controller/account/download.php
This looks like someone thought readfile() takes the same arguments as fopen(), but that is not the case: https://www.php.net/manual/en/function.readfile.php
=> Remove incorect input for readfile()

upload/install/controller/upgrade/upgrade_1.php
secound argument of mkdir() should be an int and not a string: https://www.php.net/manual/en/function.mkdir.php
=> Correct types given to mkdir()

upload/catalog/controller/cron/subscription.php
4th argument should be subscription_plan_id:
https://github.com/opencart/opencart/blob/406a3fe1133856ff9ec16df153ac8d085fa0ac37/upload/system/library/cart/cart.php#L373
=> Fix missing paramter when calling cart->add() in cron subscription

upload/admin/controller/marketplace/modification.php, upload/admin/controller/startup/notification.php, upload/catalog/controller/common/cookie.php, upload/extension/opencart/admin/controller/currency/ecb.php, upload/extension/opencart/catalog/controller/currency/ecb.php
Use the proper type to avoid implicit casting of litterals
=> Use correct property type for various calls

upload/catalog/controller/account/download.php
The secound argument is the HTTP redirect code, true would have resulted in a 1 as the redirect code, leaving it out defaults to a 302
=> Fix HTTP response status codes on download

upload/admin/controller/catalog/attribute.php
rename called method
getTotalProductsByAttributeId -> getTotalAttributesByAttributeId 
"getTotalProductsByAttributeId" no longer exists
=> fix removing attributes in admin panel:

upload/catalog/view/theme/default/template/extension/module/filter.twig
A possible safer way, given that third party themes are not likely to be updated, would be to change the controller to.
```php
$data['action'] = str_replace('&amp;', '&', $this->url->link('product/category', '&path=' . preg_replace('/[^0-9_]/', '', $this->request->get['path']) . preg_replace('/[^a-zA-Z0-9_\.&=]/', '', $url)));
```
=> [3.0.x.x] Add missing escape to filter moule

upload/catalog/controller/account/forgotten.php
Use existing validated customer email address instead of the posted one for better security when sending an account forgotten email.
=> [3.0.x.x] Improved security for account forgotten

upload/admin/controller/tool/notification.php
If less then 1 sec has passed the values would not be set, so set defaults for that case.
=> Fix time for quickly dipslayed notifications

upload/admin/controller/tool/notification.php
Since `.` takes precedence over `?` the code would execute as:
```php
$code = ($range . ($value > 1)) ? ($range . 's') : '';
```
Meaning it would always return the plural form.
This was introduced here https://github.com/opencart/opencart/commit/b5884f048e1c38b38fb6c87759da7c3b26e4bd10 and improperly fixed here https://github.com/opencart/opencart/commit/d61ea04a79904a68c56bb4968e531cd5132ca908 despite the issue being pointed out https://github.com/opencart/opencart/pull/13121#pullrequestreview-1785429347
=> Fix plural form in notifications

upload/system/config/paypal.php
Update PayPal version number to reflect recent bugfixes, using V3.0.0.1, was V3.0.0
=> Update PayPal version number

upload/catalog/controller/checkout/voucher.php, upload/system/startup.php
- Added missing helper include for email validation in `startup.php`.
- Resolved the "Call to undefined function oc_validate_email()" error that was occurring on step 3 of the installation process (step_3.php, line 393).
- Successful installation verified after the inclusion of `validation.php`.
=> Fix undefined function error during installation

upload/admin/model/setting/extension.php
I found that I can't uninstall any module setting. pls check it
=> fix: unable to uninstall module setting

upload/admin/view/javascript/summernote/opencart.js
If we edit something in Code View in Summernote and click Save, those changes won't be saved because we need to switch back to visual mode before saving the data.
=> Fixed an issue with saving in Summernote Code View.

upload/admin/model/catalog/filter.php
It seems there was an omission in commit https://github.com/opencart/opencart/commit/6819abe710b64b1202aaa04ee3e07a96dee86ced where logic to read from `$data` was added. Alternatively, considering it's not currently utilized, the code using it could be removed instead.
Given recent similar issues, it might help to conduct a quick check for lint errors before or after making code changes to prevent similar issues.
=> Add missing attribute to getTotalFilters()

upload/admin/controller/extension/currency/ecb.php, upload/admin/controller/localisation/currency.php, upload/admin/controller/setting/setting.php, upload/admin/model/extension/currency/ecb.php, upload/admin/model/localisation/currency.php, upload/catalog/controller/extension/currency/ecb.php, upload/catalog/model/extension/currency/ecb.php
Move calls to ECB API to model files.
Make sure all calls to model/localisation/currency/refresh are now done to the selected currency engine's API, e.g. ECB.
=> More updates for currency refresh

upload/admin/controller/extension/payment/paypal.php
Bugfix for the admin PayPal event handler order_info_before: This event handler must not modify the main language data, such as the heading title.
See https://github.com/Dreamvention/paypal/issues/26 for more details.
=> Bugfix order info heading title

upload/admin/controller/marketing/affiliate.php
Remove redundant typecasting in balance formatting
- Updated balance formatting to remove unnecessary typecasting to integer in the `$result['balance']` variable. This ensures the balance is correctly formatted without altering the original value type.
=> Remove redundant typecasting in balance formatting

upload/admin/controller/customer/customer.php
in upload/admin/controller/customer/customer.php should change 
`oc_validate_length($this->request->post['telephone'], 3, 32) `
to 
`!oc_validate_length($this->request->post['telephone'], 3, 32)
`
because  telephone's length betwee  3 and 32 is not error.  
it's error when length is less than 3, or bigger than 32
=> fix error about validate_length for telephone

upload/admin/model/marketing/affiliate.php
Update query to include 'status' field in customer affiliate data
- Added the 'status' field to the SELECT statement in the customer affiliate query.
- This ensures that the affiliate status is retrieved along with other customer details.
=> Add 'status' field to customer affiliate query

upload/catalog/controller/product/product.php
Product tags with special characters (e.g., `&`, spaces) were not properly encoded, causing broken phrases
Updated the product controller to use rawurlencode() and html_entity_decode() to handle special characters and HTML entities correctly.
- upload/catalog/controller/product/product.php
- Tested with tags containing special characters (`&`, spaces, etc.) and verified correct URL encoding.
- Example: `Gas & Oil` now generates `tag=Gas%20%26%20Oil`.
https://www.carguygarage.com/index.php?route=product/search&tag=Gas%20%26%20Oil
=> Fix URL encoding for product tags in OpenCart 3

upload/catalog/controller/product/product.php, upload/catalog/controller/product/search.php
This fix allows for the usage of special characters like '&', '+', or blanks, in product tags.
=> urlencode for tag in query string

upload/admin/model/catalog/product.php
Trying to use `json_decode`on the indexes 'override' and 'variant', but in `function getProducts`, the json-string is already decoded into an array.
Triggering the errors:
```
Error: json_decode(): Argument #1 ($json) must be of type string, array given
File: .\admin\model\catalog\product.php
Line: 771
Backtrace: 0
File: .\admin\model\catalog\product.php
Line: 771
Function: json_decode
Backtrace: 1
File: .\system\engine\loader.php
Line: 343
Class: Opencart\Admin\Model\Catalog\Product
Function: editVariants
Backtrace: 2
File: .\system\engine\proxy.php
Line: 87
Class: Opencart\System\Engine\Loader
Function: Opencart\System\Engine\{closure}
Backtrace: 3
File: .\admin\controller\catalog\product.php
Line: 1261
Class: Opencart\System\Engine\Proxy
Function: __call
Backtrace: 4
File: …
```
=> Fix save product master with variants

upload/catalog/controller/common/language.php
In the header always shows the last language of the list as current, which is incorrect. It should show real current language.
=> Display current language in the language switcher

upload/catalog/controller/startup/seo_url.php
The problem with multilingual SEO URLs, its solution is to separate the $this->data by languages.
=> Cache by language in SEO URL

upload/admin/model/catalog/product.php
Added missing closing ` in query when creating a new product with a recurring payment profile
=> Fixed bug when saving new product with a recurring payment profile

upload/admin/controller/design/seo_url.php
Saving SEO URL with empty sort_order gives error:
Error: Opencart\Admin\Model\Design\SeoUrl::addSeoUrl(): Argument #6 ($sort_order) must be of type int, string given, called in \system\engine\loader.php on line 343 File: \admin-new\model\design\seo_url.php Line: 29
=> Fix saving SEO URL

upload/catalog/controller/account/login.php
After exceeding the login attempt limit, after refreshing the page you get an error: Undefined array key "customer_token".
This is because system doesn't allow you to log in but creates "customer_id".
=> Fix bug after exceeding login attempts.php

upload/catalog/model/catalog/product.php
Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CASE WHEN `discount` IS NOT NULL THEN `discount` ELSE `p`.`price` END) DESC, ...' at line 1
[#14437](https://github.com/opencart/opencart/issues/14437#issue-2809577516)
=> Fix sql error in sorting products by price

upload/catalog/controller/common/language.php
this is not necessary, as we have already found $data['code'] above.
=> deleted the extra code

upload/admin/view/stylesheet/scss/_progress.scss
FIX: addition to #14483
I missed the moment that CSS is formed from SCSS :)
An addition to my previous comit.
=> [continuation] fixed the color of the progressbar #14483

upload/admin/controller/common/language.php, upload/catalog/controller/common/cookie.php, upload/catalog/controller/startup/marketing.php
DESCRIPTION: If you set Cookie SameSite=None in the system settings, then the Admin Panel languages ​​will not switch.
REASON: for Cookie SameSite=None the "secure" parameter is mandatory. Without it the cookie will not be set at all.
=> [fix] Cookie SameSite

upload/catalog/controller/startup/session.php
Did anyone ever check cookies with lifetime set in php.ini?
```
; Lifetime in seconds of cookie or, if 0, until browser is restarted.
; http://php.net/session.cookie-lifetime
session.cookie_lifetime = 7776000
```
=> fix cookie_lifetime

upload/system/helper/db_schema.php
CLI installer was failing with this 2 errors
1)
Fatal error: Uncaught Exception: Error: Key column 'country_id' doesn't exist in table<br/>Error No: 1072<br/>CREATE TABLE `oc_zone_description` (
`zone_id` int(11),
`language_id` int(11),
`name` varchar(255),
PRIMARY KEY (`country_id`,`language_id`),
KEY `name` (`name`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
in /var/www/html/system/library/db/mysqli.php:122
Stack trace:
#0 /var/www/html/system/library/db.php(54): Opencart\System\Library\DB\MySQLi->query('CREATE TABLE `o...')
#1 /var/www/html/install/cli_install.php(340): Opencart\System\Library\DB->query('CREATE TABLE `o...')
#2 /var/www/html/install/cli_install.php(118): Install\CliInstall->install(Array)
#3 /var/www/html/install/cli_install.php(550): …
=> Fix schema errors in helper/db_schema.php to fix CLI installer errors

upload/install/controller/upgrade/upgrade_10.php, upload/install/model/upgrade/upgrade.php
There are critical error in the installer that make it impossible to update.
Steps 7, 8, 9 are not executed due to an error in the model.
Step 10 has an SQL error
@danielkerr possible errors `$json['error']` are not displayed in any way. This is very inconvenient and makes it very difficult to find and fix errors.
=> [fix] The update procedure does not work

upload/admin/controller/marketplace/installer.php, upload/admin/language/en-gb/marketplace/installer.php, upload/admin/language/fr-fr/marketplace/installer.php
I created an xml file and changed its extension to ocmod.zip and went to install. Thereafter, every time I attempted to load the extension installer page, I was greeted with a PHP unauthorised zip file error and the page just wouldn't load. This update checks for errors with the zip files, if there's an error it will delete the file and continue through the loop without crashing the page
=> Update to admin marketplace/installer.php

upload/admin/model/localisation/geo_zone.php
Here at
`upload\admin\controller\localisation\country.php`
for the delete method
`$zone_to_geo_zone_total = $this->model_localisation_geo_zone->getTotalZoneToGeoZoneByCountryId($country_id);`
made it crash. So **in the model** the name which had an incorrect name was changed to the correct one.
Same fix for the 
`upload\admin\controller\localisation\zone.php`
=> Renamed total function as they had an incorrect name

upload/admin/controller/user/user_permission.php
this is revised PR of previous https://github.com/opencart/opencart/pull/14751
Currently if controllers file is inside nested folder at more than 2 level then it is impossible to access it because of permission.
This PR will fix this issue
=> Retrieve more in depth files from extension directory for permission

upload/system/library/cache/file.php
Reverts #14778 
sorry daniel bet it seems warning cant be caught,
=> Revert "cache delete/unlink prevent error on file not found"

upload/catalog/controller/cron/subscription.php, upload/catalog/model/setting/store.php
As explained in issue #14823, the use of $this->autoloader fails to load certain classes—likely because they were already loaded earlier in the execution flow. To resolve this, a new $autoloader instance is created to ensure proper and consistent class loading within storeInstance.
=> Fix autoloader in storeInstance to ensure proper class loading

upload/admin/view/template/marketplace/installer.twig
PR fixes a mismatch in the `installer.twig` template where the `<div>` block was using `id="list"` but the associated JavaScript was targeting `#extension`. This mismatch caused AJAX operations (such as extension install/uninstall progress updates) to break, resulting in stuck progress indicators or raw JSON output in the browser.
- Updated `<div id="list">` to `<div id="extension">` in `upload/admin/view/template/marketplace/installer.twig`.
- Aligns the template markup with the JavaScript selectors used in `installer.twig`.
- Resolves backend extension installer UI breakage.
- Applied and tested on a live OpenCart 4.1.0.3 deployment.
- Verified successful extension installation and uninstallation without UI dumping AJAX payload or seeing browser console errors.
- No apparent side …
=> Fix: Correct div ID from 'list' to 'extension' in installer.twig for proper JS/AJAX binding

.gitignore, docker-compose.yml, upload/install/cli_install.php, upload/system/library/db/mysqli.php
Changes:
1. Fixes basic operation of docker-compose by ensuring commands are closed properly.
2. Updates initialization to match new constructors
3. Removes 'version' option from `docker-compose.yaml`
4. Ignores `install.lock` file
5. Adds support for latest MySQLi engine version - as well as support for development on `arm64` boxes by using `mariadb` image
If any of these changes should be modified in any way, let me know - happy to adjust.
=> Fix operation of docker-compose file/cli-install with recent class modifications.

upload/system/library/session/db.php
With standard MySQL operation, InnoDB does not free up disk space when deleting records. In fact, it is marked "Deleted", but there is no actual deletion. To free up space, you need to perform:
OPTIMIZE TABLE foo;
This will recreate the table and free up space.
https://dev.mysql.com/doc/refman/8.4/en/optimize-table.html#optimize-table-innodb-details
Adding optimization will help save space on the server over a long period of time and speed up work so that the table does not grow infinitely in size.
=> Add OPTIMIZE TABLE to db.php

docker-compose.yml
This PR improves the startup reliability of the Docker environment by replacing the `wait-for-it` script with a native Docker healthcheck.
This change ensures that the `opencart` and `adminer` services will patiently wait for the database to be fully initialized and ready for connections before they attempt to start. This resolves potential race conditions and makes the local setup more stable.
Please note that this is part of an ongoing effort to improve the Docker configuration, which is **not yet considered production-ready.** Further work will continue.
=> feat(docker): add healthcheck for database service

upload/install/cli_install.php
This PR fixes a fatal error that occurs after installing OpenCart using the command-line interface (`cli_install.php`).
When using the CLI installer without providing database SSL options, the constants DB_SSL_KEY, DB_SSL_CERT, and DB_SSL_CA are not defined in the generated config.php file.
This leads to a fatal error on the frontend and backend immediately after installation:
```
Fatal error: Uncaught Error: Undefined constant "DB_SSL_KEY" in /var/www/html/system/config/catalog.php on line 14
```
The web-based installer correctly handles this by defining these constants as empty strings if they are not provided, but the CLI installer was missing this logic.
This commit aligns the behavior of the CLI installer with the web installer. It adds the necessary `else` blocks to ensure that the …
=> fix(cli): ensure DB SSL constants are always defined

README.md, docker-compose.yml
This PR introduces Docker Compose profiles for optional services, allowing developers to enable only the services they need for a lighter and faster development environment. The documentation has also been updated with clear instructions and usage examples.
- Added Docker Compose profiles for `Adminer`, `Redis`, `Memcached`, and `PostgreSQL` in `docker-compose.yml`.
- Updated the documentation to explain how to enable optional services using the `--profile` flag.
Please note that this is part of an ongoing effort to improve the Docker configuration, which is **not yet considered production-ready**. Further work will continue.
=> feat(docker): add compose profiles for optional services and update docs

docker-compose.yml, docker/php/Dockerfile, docker/php/entrypoint.sh
This PR refactors the Docker configuration by moving the OpenCart initialization logic from the Docker Compose `command` section into a dedicated `entrypoint.sh` script.
This change is a straightforward refactoring that centralizes the container's startup process. By moving the existing OpenCart setup commands (including copying config files, running the CLI installer, and launching Apache via `exec` with the `install.lock` check) to `entrypoint.sh`, the configuration becomes:
- **Cleaner and More Readable:** The `docker-compose.yml` is simplified, with all container startup logic encapsulated in a single, dedicated script.
- **Easier to Maintain:** Future adjustments or extensions to the initialization process can be made in one place, streamlining development.
- **More Robust:** …
=> refactor(docker): move opencart init logic to entrypoint script

upload/admin/model/catalog/product.php
When editing an existing product, calling `Opencart\Admin\Model\Catalog\Product@editProduct()` would result in an exception with the message "Error: Could not call registry key model_design_seo_url!". This would happen only when `editProduct()` was the first method call after instantiation of `Opencart\Admin\Model\Catalog\Product` (via `$this->load->model('catalog/product')`). If the first method called after instantiation was one that included a call to `$this->load->model('design/seo_url')` such as `Product@deleteProduct()` or `Product@addProduct()`, the exception would not be thrown because the `design/seo_url` model was already loaded by one of the previous method calls.
=> Fix `Could not call registry key model_design_seo_url` exception

upload/catalog/controller/startup/api.php, upload/catalog/model/account/gdpr.php
Fix PHPStan type errors by using correct parameter types for hash_hmac and GDPR editStatus methods.
- Use boolean value `true` instead of integer `1` for hash_hmac binary parameter
- Change GDPR editStatus parameter type from `bool` to `int` to match actual usage patterns
- Update PHPDoc to reflect status codes based on controller documentation
- No functional changes, only type correctness improvements
- `Parameter #4 $binary of function hash_hmac expects bool, int given`
- `Parameter #2 $status of method editStatus() expects bool, int given`
@danielkerr, the GDPR editStatus method was typed as `bool $status` but the code passes integer status codes (0, 1, 2, 3). I found status documentation in [catalog/controller/information/gdpr.php#L65](https://github.com/opencart/opencart/blob/master/ …
=> fix(types): correct parameter types for hash_hmac and GDPR editStatus

upload/catalog/controller/account/address.php, upload/catalog/controller/account/wishlist.php, upload/catalog/model/account/address.php, upload/catalog/model/account/affiliate.php, upload/catalog/model/account/customer.php, upload/catalog/model/account/reward.php, upload/catalog/model/account/transaction.php, upload/catalog/model/account/wishlist.php, upload/catalog/model/checkout/order.php
Fix customer deletion functionality by correcting method names in account models to use plural forms for bulk delete operations.
The [`Customer::deleteCustomer()`](https://github.com/opencart/opencart/blob/master/upload/catalog/model/account/customer.php#L147) method was calling non-existent methods, causing related customer data (addresses, rewards, transactions, etc.) to not be properly cleaned up when deleting customers, leading to orphaned records in the database.
- **Address model**: `deleteAddress()` → `deleteAddresses()` 
- **Reward model**: `deleteReward()` → `deleteRewards()`
- **Transaction model**: `deleteTransaction()` → `deleteTransactions()`
- **Customer model**: `deleteHistory()` → `deleteHistories()`, `deleteIp()` → `deleteIps()`, `deleteAuthorize()` → `deleteAuthorizes()` …
=> fix(models): correct method names for bulk delete operations

upload/admin/model/design/seo_url.php
The default store's ID is 0, which evaluates to `false` in a boolean check. Because of this, when calling the `SeoUrl::*SeoUrlsByKeyValue()` methods, and searching by the default store, the additional `WHERE` check doesn't get added. This causes the search to be applied to all stores instead of the intended target store.
=> Enabled searching default store

upload/admin/model/localisation/language.php
Convert string ID parameters to `int` type when calling model methods in the language model `addLanguage()` method.
Database query results return ID values as strings, but model methods like `addDescription()` and `addAttribute()` expect `int` parameters. This causes type mismatch errors throughout the language model.
- `Parameter #1 $attribute_id of method addDescription() expects int, string given` (×22 occurrences)
- `Parameter #1 $product_id of method addAttribute() expects int, string given` 
- `Parameter #2 $attribute_id of method addAttribute() expects int, string given`
=> fix(types): correct parameter types from string to int in language model

upload/catalog/controller/api/order.php
Fix obvious typo `$thid` → `$this` in api/order controller.
- `Variable $thid in isset() is never defined`
=> fix(typo): correct $thid to $this in api/order controller

upload/admin/controller/ssr/admin/country.php, upload/admin/controller/ssr/admin/currency.php, upload/extension/opencart/admin/controller/fraud/ip.php, upload/install/model/upgrade/upgrade.php, upload/system/helper/general.php, upload/system/library/cart/api.php, upload/system/library/curl.php
Add missing return types and parameter types across system libraries, controllers, and helper functions to improve type safety and eliminate PHPStan errors.
- Missing return types for file handling functions (`oc_file_read`, `oc_file_write`, `oc_file_append`, `oc_file_delete`) in `system/helper/general.php`
- Missing return types for directory functions (`oc_directory_create`, `oc_directory_remove`, `oc_directory_read`) in `system/helper/general.php`
- Missing return types for API `send()` methods in `system/library/cart/api.php` and `system/library/curl.php`
- Missing return types for SSR controller methods (`info()`, `clear()`, `index()`) across admin/controller/ssr/ classes
- Missing parameter types for file/directory handling functions and API methods
- Incorrect PHPDoc parameter type …
=> feat(types): add missing return and parameter types

upload/admin/model/catalog/review.php, upload/admin/model/customer/customer_group.php, upload/admin/model/localisation/country.php, upload/admin/model/localisation/identifier.php, upload/admin/model/localisation/zone.php, upload/admin/model/tool/menu.php, upload/catalog/model/account/customer.php, upload/catalog/model/catalog/product.php, upload/catalog/model/checkout/order.php, upload/system/library/cart/cart.php
Remove incorrect `@param` tags that reference non-existent parameters across models and system libraries to eliminate PHPStan parameter.notFound errors.
- Invalid `@param $product_id` reference in `editStatus()` method (expects `$review_id`) in `admin/model/catalog/review.php`
- Invalid `@param $information_id` reference in `getStores()` method (expects `$country_id`) in `admin/model/localisation/country.php`
- Invalid `@param $data` references in parameterless methods `getTotalIdentifiers()` and `getMenus()` in `admin/model/localisation/identifier.php` and `admin/model/tool/menu.php`
- Invalid `@param $customer_id` reference in `deleteTokenByCode()` method (not used) in `catalog/model/account/customer.php`
- Invalid `@param $data` and incorrect `@return int` (should be `void`) in …
=> fix(phpdoc): remove invalid `@param` references across multiple files

upload/system/library/db/pgsql.php
Fix undefined variables in PostgreSQL driver exception handling and add required parameters validation following MySQLi driver standards.
- Undefined variables `$username` and `$hostname` in exception message (line 33) in `system/library/db/pgsql.php`
=> fix(pgsql): add required params validation and fix undefined variables

upload/admin/controller/startup/error.php, upload/catalog/controller/startup/error.php, upload/system/framework.php
Remove unreachable `return true;` statements that follow `throw new \ErrorException()` in error handlers and improve PHPDoc documentation.
- `Unreachable statement - code above always terminates` in admin/controller/startup/error.php:39
- `Unreachable statement - code above always terminates` in catalog/controller/startup/error.php:39  
- `Unreachable statement - code above always terminates` in system/framework.php:44
- Added `@throws \ErrorException` documentation to PHPDoc blocks
=> fix(error-handling): remove unreachable return statements after throw

upload/system/library/request.php
Remove unreachable `break` statements that follow `return` statements in switch cases within request parameter type casting methods.
Switch cases contained `break` statements immediately after `return` statements. Since `return` terminates function execution, these `break` statements are never reached, causing PHPStan to report multiple "Unreachable statement - code above always terminates" errors.
- 10 "Unreachable statement" errors in `system/library/request.php` (lines 58, 61, 64, 67, 70, 86, 89, 92, 95, 98)
- Affects both `get()` and `post()` methods with identical switch case structures
- Cleaner, more maintainable code structure
- Eliminates dead code that could confuse developers
- Follows PHP best practices for switch statements with early returns
- No functional changes - …
=> style(request): remove unreachable break statements

upload/catalog/controller/api/order.php
Add detailed PHPDoc return type annotations to resolve PHPStan missing iterable value type warnings in the Order API controller.
- `Method setCustomer() return type has no value type specified in iterable type array` in catalog/controller/api/order.php:80
- `Method setPaymentAddress() return type has no value type specified in iterable type array` in catalog/controller/api/order.php:89
- `Method setShippingAddress() return type has no value type specified in iterable type array` in catalog/controller/api/order.php:98
- `Method getShippingMethods() return type has no value type specified in iterable type array` in catalog/controller/api/order.php:113
- `Method setShippingMethod() return type has no value type specified in iterable type array` in catalog/controller/api/order.php:133
- …
=> docs(api): add specific return types for order controller methods

upload/admin/model/customer/customer_group.php, upload/admin/model/localisation/country.php, upload/admin/model/setting/cron.php, upload/admin/model/setting/ssr.php, upload/admin/model/setting/task.php, upload/admin/model/tool/menu.php, upload/catalog/controller/api/order.php, upload/catalog/controller/api/subscription.php, upload/system/library/cart/api.php, upload/system/library/cart/cart.php, upload/system/library/curl.php, upload/system/library/db.php
Add `array<string, mixed>` type annotations to method parameters and return types to resolve PHPStan missingType.iterableValue errors.
- `Method addCron() has parameter $data with no value type specified in iterable type array` in admin/model/setting/cron.php:31
- `Method addSsr() has parameter $data with no value type specified in iterable type array` in admin/model/setting/ssr.php:26
- `Method getDescription() return type has no value type specified in iterable type array` in admin/model/customer/customer_group.php:267
- `Method getDescription() return type has no value type specified in iterable type array` in admin/model/localisation/country.php:407
- `Method getCountriesByStoreId() return type has no value type specified in iterable type array` in …
=> fix(phpstan): add missing array type specifications in PHPDoc

upload/extension/opencart/admin/model/report/customer.php, upload/extension/opencart/admin/model/report/sale.php
Convert database string results to integers in report aggregation methods to match PHPDoc return type declarations from `array<int, array<string, mixed>>` to `array<int, array<string, int>>`.
- `Method Opencart\Admin\Model\Extension\Opencart\Report\Customer::getTotalCustomersByWeek() should return array<int, array<string, int>> but returns array<int, array<string, mixed>>` in extension/opencart/admin/model/report/customer.php:74
- `Method Opencart\Admin\Model\Extension\Opencart\Report\Customer::getTotalCustomersByMonth() should return array<int, array<string, int>> but returns array<int, array<string, mixed>>` in extension/opencart/admin/model/report/customer.php:107
- `Method Opencart\Admin\Model\Extension\Opencart\Report\Customer::getTotalCustomersByYear() should return array<int, …
=> fix(phpstan): correct return types in report models

Makefile, README.md
This PR introduces a comprehensive Makefile to simplify Docker Compose operations for OpenCart development and updates the documentation accordingly:
- Adds feature-rich Makefile with intuitive commands like `make up`, `make php`, `make logs`
- Replaces lengthy docker compose commands with simple make targets
- Includes service validation, error handling, and color-coded help system
- Updates README documentation to use make commands instead of docker compose
This significantly improves developer experience by:
- Reducing command complexity (`make up` vs `docker compose --env-file=./docker/.env.docker up -d`)
- Providing consistent interface across different environments
- Adding helpful validation and error messages
- Offering comprehensive help system with `make help`
> [!NOTE]
> ### …
=> feat(docker): add Makefile for simplified Docker operations and update documentation

upload/system/library/db/pdo.php
When a given query fails, the `$data` property is left alone. If a caller somewhere up the stack catches the exception, the `$data` property maintains the state from the failed query while the application continues to run. The data gets included in subsequent queries, thus causing the `SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens` exception.
This fix resets the `$data` property no matter the outcome.
=> Fix PDO invalid parameter number

upload/catalog/controller/extension/feed/google_sitemap.php
This PR changes two things for the Google Sitemap extension.
1. It adds `PHP_EOL` to each line to make the file readable when you open it as a human
2. It adds the use of `CDATA` for image caption and image title. Without this the feed generation will result in an invalid feed when your caption is using html formatted special characters. For example: `&auml;`
=> [3.0.x.x] Use CDATA for image caption and title and add linebreaks

upload/admin/controller/task/admin/subscription.php
This PR fixes a bug in the subscription task controller where the payment address was not being assigned correctly due to a syntax error.
=> fix(lint): resolve syntax error in subscription controller

README.md
Removes an extra space in the `[Chat]` link to fix the broken URL.
=> fix(docs): remove space and fix link in readme

upload/admin/model/catalog/product.php
On master edit all variants' codes are replaced even if variant has override enabled
=> fix: Master replacing variant codes

upload/extension/opencart/admin/controller/report/sale_order.php
Without .list, clicking pagination links in the Sales Order report redirected to the report extension settings page instead of showing the next set of results in the report list table.
Go to: https://yourdomain.com/admin/index.php?route=report/report
From the dropdown, select Sales Report.
Click Next Page in pagination.
Instead of showing the next set of results, it redirects to the report extension settings page within the table view.
=> Bugfix (Admin): Correct pagination route in sales order report
